- cmake/GodotJoltExternalGodotCpp.cmake
This bumps godot-cpp from godot-jolt/godot-cpp@7d08f38d8f39a003c124c2ee0acc38e6c8c07b82 aka `4.0-rc5` to godot-jolt/godot-cpp@27cdf763c7601400705adfc16a25a248ff47adc4 aka `4.0-rc6` (see diff [here](https://github.com/godot-jolt/godot-cpp/compare/7d08f38d8f39a003c124c2ee0acc38e6c8c07b82...27cdf763c7601400705adfc16a25a248ff47adc4)).
> Updated godot-cpp to 4.0-rc6

- src/jolt_body_3d.cpp
- src/jolt_body_3d.hpp
- src/jolt_physics_direct_body_state_3d.cpp
- src/jolt_space_3d.cpp
- src/jolt_space_3d.hpp
This PR adds support for the following methods (and matching properties) in [`PhysicsDirectBodyState3D`](https://docs.godotengine.org/en/latest/classes/class_physicsdirectbodystate3d.html):
- `get_step`
- `get_space_state`
- `set_transform`
- `set_linear_velocity`
- `set_angular_velocity`
- `get_center_of_mass`
- `get_center_of_mass_local`
- `get_total_gravity`
- `get_total_linear_damp`
- `get_total_angular_damp`
- `get_inverse_mass`
- `get_principal_inertia_axes`
- `get_inverse_inertia`
> Added support for the remaining body state methods

- src/jolt_body_3d.cpp
- src/jolt_body_3d.hpp
- src/jolt_collision_object_3d.cpp
- src/jolt_collision_object_3d.hpp
- src/jolt_physics_server_3d.cpp
- src/jolt_shape_3d.hpp
- src/jolt_shape_instance_3d.hpp
This PR adds support for the following methods in [`PhysicsServer3D`](https://docs.godotengine.org/en/latest/classes/class_physicsserver3d.html):
- `area_clear_shapes`
- `area_get_shape_count`
- `area_get_shape_transform`
- `area_get_shape`
- `area_get_space`
- `area_get_transform`
- `area_set_shape`
- `body_clear_shapes`
- `body_get_direct_state`
- `body_get_mode`
- `body_get_shape_count`
- `body_get_shape_transform`
- `body_get_shape`
- `body_get_space`
- `body_set_axis_velocity`
- `body_set_shape`
- `shape_get_type`
> Added support for various physics server methods

- src/jolt_physics_server_3d.cpp
- src/jolt_space_3d.cpp
- src/jolt_space_3d.hpp
This PR adds error/warning messages to indicate that certain (mostly minor) features are not supported by Godot Jolt. These consist of the following:
- Custom shapes
- Not supported by Godot Physics either
- Body user flags
- Not supported by Godot Physics either
- Contact depth threshold
- Not supported by Godot Physics either
- Contact debugging
- Only relevant for `dev_build=yes` builds of the engine, so I assume it's meant to be a developer tool
- Per-space physics parameters
- Most of them don't line up with what Jolt expects
- `SPACE_PARAM_BODY_TIME_TO_SLEEP` could probably be supported, but I'll hold off until someone requests it
> Added explicit non-support for various server methods

- cmake/GodotJoltExternalGodotCpp.cmake
This bumps godot-cpp from godot-jolt/godot-cpp@27cdf763c7601400705adfc16a25a248ff47adc4 aka `4.0-rc6` to godot-jolt/godot-cpp@d5f4e379948b69b131c1614ff971801477409988 aka `4.0-stable` (see diff [here](https://github.com/godot-jolt/godot-cpp/compare/27cdf763c7601400705adfc16a25a248ff47adc4...d5f4e379948b69b131c1614ff971801477409988)).
> Updated godot-cpp to 4.0-stable

- src/jolt_body_3d.cpp
- src/jolt_body_3d.hpp
- src/jolt_collision_object_3d.hpp
- src/jolt_physics_server_3d.cpp
- src/jolt_space_3d.cpp
- src/jolt_space_3d.hpp
This PR adds support for the "Axis Lock" property on [`PhysicsBody3D`](https://docs.godotengine.org/en/latest/classes/class_physicsbody3d.html) as well as the "Lock Rotation" property on [`RigidBody3D`](https://docs.godotengine.org/en/latest/classes/class_rigidbody3d.html).
> Added support for axis-locking

- src/jolt_contact_listener.cpp
- src/jolt_contact_listener.hpp
- src/jolt_physics_server_3d.cpp
- src/jolt_space_3d.cpp
- src/jolt_space_3d.hpp
- src/pch.hpp
This PR adds support for contact debugging, which is available through the [`debug_collisions_hint`](https://docs.godotengine.org/en/latest/classes/class_scenetree.html#class-scenetree-property-debug-collisions-hint) property on `SceneTree`.
Apparently I had mistaken `DEBUG_ENABLED` for `DEV_ENABLED` when I declared this as unsupported in #215. I was unaware of the above mentioned property and thought this was purely a developer feature for `dev_build` builds of the engine.
> Added support for contact debugging

- src/jolt_physics_server_3d.cpp
- src/jolt_shape_3d.cpp
- src/jolt_shape_3d.hpp
Since Jolt does not, and seemingly never will, support plane shapes (see jrouwe/JoltPhysics#126) for reasons that seem reasonable to me, I will opt to not support this shape type in Godot Jolt.
I took a crack at (somewhat naively) implementing a plane shape as a custom shape type, much in the same way that Bullet does it, and quickly ran into the precision problems mentioned in that issue.
> Added empty implementation of `WorldBoundaryShape3D`

- src/jolt_shape_3d.inl
Currently Jolt throws asserts due to it expecting normalized quaternions, so we fix that much in the same way we do with the root shape, by stripping the scale from the transform and wrapping the shape in a `JPH::ScaledShape` instead.
> Fixed inability to scale shapes within a compound shape

- cmake/GodotJoltExternalGodotCpp.cmake
This bumps godot-cpp from godot-jolt/godot-cpp@d5f4e379948b69b131c1614ff971801477409988 aka `4.0-stable` to godot-jolt/godot-cpp@a1ae7959da3ce52951b3fed37a018960d03eb785 aka `4.0-stable` (see diff [here](https://github.com/godot-jolt/godot-cpp/compare/d5f4e379948b69b131c1614ff971801477409988...a1ae7959da3ce52951b3fed37a018960d03eb785)).
This fixes a problem with the bindings of `PhysicsServer3DExtensionMotionCollision` and `PhysicsServer3DExtensionMotionResult`, where certain members were missing, leading to a mismatch of struct layouts between the engine and the extension.
> Updated godot-cpp to a1ae7959da (4.0-stable)

- cmake/GodotJoltExternalJolt.cmake
This bumps Jolt from godot-jolt/jolt@02e969864f763c88c45e45599f77573e94aa531c to godot-jolt/jolt@752f0c3e36c8bb324726496033cfbba45588207e (see diff [here](https://github.com/godot-jolt/jolt/compare/02e969864f763c88c45e45599f77573e94aa531c...752f0c3e36c8bb324726496033cfbba45588207e)).
This brings in user-defined convex sub shape types, which is needed for the implementation of `SeparationRayShape3D`.
It also brings in a lot of other goodies, such as...
- Large island splitting, which parallelizes large piles of bodies
- Option to disable determinism for a bump in performance, which I'll probably make the default
- Optimizations to `JPH::EstimateCollisionResponse`, making the calculation of contact impulses slightly faster
- Adding of `JPH::UnregisterTypes`, to match `JPH::RegisterTypes`
- …
> Updated Jolt to 752f0c3e36

- src/jolt_hooks.cpp
- src/jolt_physics_server_3d.cpp
- src/jolt_ray_shape.cpp
- src/jolt_ray_shape.hpp
- src/jolt_shape_3d.cpp
- src/jolt_shape_3d.hpp
Note that this deviates slightly from the implementation in Godot Physics, where convex shapes are seemingly not treated as solid, meaning their implementation does not resolve collisions where the ray is fully enveloped by a convex shape, whereas this one will.
> Added support for `SeparationRayShape3D`

- src/jolt_body_3d.cpp
- src/jolt_body_3d.hpp
- src/jolt_collision_object_3d.cpp
- src/jolt_collision_object_3d.hpp
- src/jolt_motion_filter_3d.cpp
- src/jolt_motion_filter_3d.hpp
- src/jolt_physics_direct_space_state_3d.cpp
- src/jolt_physics_direct_space_state_3d.hpp
- src/jolt_physics_server_3d.cpp
- src/jolt_query_collectors.hpp
This adds preliminary (somewhat broken) support for the [`body_test_motion`](https://docs.godotengine.org/en/latest/classes/class_physicsserver3d.html#class-physicsserver3d-method-body-test-motion) method on `PhysicsServer3D`, which is what powers methods like `PhysicsBody3D.move_and_collide` and `PhysicsBody3D.test_move`, which in turn powers `CharacterBody3D`.
The caveats here are as follows:
1. The `recovery_as_collision` parameter that gets passed to the above mentioned methods is not currently exposed to GDExtension, so this will always be treated as `true` currently, to cater to the needs of `CharacterBody3D`.
2. More work needs to be done with collision tolerances and how the `margin` parameter is incorporated into them, because you can currently get stuck randomly as you're …
> Added preliminary support for `body_test_motion`

- cmake/GodotJoltExternalJolt.cmake
- examples/capsule.tscn
- examples/character.gd
- src/jolt_motion_filter_3d.cpp
- src/jolt_motion_filter_3d.hpp
This bumps Jolt from godot-jolt/jolt@752f0c3e36c8bb324726496033cfbba45588207e to godot-jolt/jolt@bc4fa997f15f2953dc87ee5c1ba51ecf2077c287 (see diff [here](https://github.com/godot-jolt/jolt/compare/752f0c3e36c8bb324726496033cfbba45588207e...bc4fa997f15f2953dc87ee5c1ba51ecf2077c287)).
This brings in the revised `JPH::ShapeFilter`, which allows for discerning of compound shapes for the shape being cast during a shape-cast, which is needed for the `collide_separation_ray` parameter of `PhysicsServer3D.body_test_motion`.
> Updated Jolt to bc4fa997f1

- src/jolt_motion_filter_3d.hpp
- src/jolt_physics_direct_space_state_3d.cpp
- src/jolt_physics_direct_space_state_3d.hpp
Apparently this parameter was only meant to be applied during the motion phase of the motion test and not the recovery phase or the collision phase.
> Fixed `collide_separation_ray` test motion parameter

- src/jolt_hooks.cpp
This shouldn't make much of a difference in practice, since all of Jolt's memory usage would've been wiped at library unload anyway, but it's the correct thing to do I guess.
> Improved deinitialization of Jolt using `JPH::UnregisterTypes`

- src/jolt_physics_direct_space_state_3d.cpp
This should hopefully improve the accuracy and precision of the physics queries, and will likely be needed for any eventual double-precision support anyway.
> Added base offset to physics queries

- src/jolt_physics_direct_space_state_3d.cpp
- src/jolt_physics_direct_space_state_3d.hpp
This PR improves on the implementation of the `PhysicsServer3D.body_test_motion` method.
Firstly, it fixes the `margin` parameter. Previously this was passed into Jolt's `CollideShape` method as `mCollisionTolerance`. This was not correct, as it presumably only forced the solver to consider more shapes around it, but didn't seem to actually output any additional contacts. Now instead the `margin` parameter gets passed in as `mMaxSeparationDistance`, which seems to have the desired effect of actually outputting contacts within that distance.
I also made use of the `mActiveEdgeMovementDirection` setting, for no real good reason other than it being used by Jolt's own character controller as well. According to Jolt's documentation it's meant to have some (presumably positive) effect on the …
> Improved implementation of `body_test_motion`

- src/jolt_physics_direct_space_state_3d.cpp
- src/jolt_physics_server_3d.cpp
- src/jolt_shape_3d.cpp
- src/jolt_shape_3d.hpp
This PR adds support for the "Margin" property on `BoxShape3D`, `CylinderShape3D` and `ConvexPolygonShape3D`. Any other shapes are either not convex or not applicable, in which case the margin will be a no-op.
This PR also fixes the `margin` parameter on physics queries involving shapes, like `cast_motion`. This previously relied on Jolt's GJK collision tolerance to achieve this, which was probably not a good use of that parameter, and also wouldn't have worked for anything but convex-versus-convex collisions.
> Added support for shape margins

- src/jolt_physics_direct_space_state_3d.cpp
I forgot to push this change to #239 before merging.
Since we're now potentially passing on a non-zero margin to `JoltShape3D::try_build`, we can end up with a built shape that doesn't get stored/cached in the actual `JoltShape3D`, meaning we can't rely on it for fetching the center-of-mass. We have to instead go straight to the source and use the `JPH::Shape` directly.
> Fixed broken fetching of center-of-mass in physics queries

- src/jolt_shape_3d.cpp
These error messages didn't really work out and ended up triggering a lot of false positives, especially with larger margins, since Godot seems to set the margin before it sets the rest of the shape data.
I'm not sure what else to do other than to just let this silently fail. I suspect more than a few users will end up scratching their heads wondering why bodies with extents smaller than 0.04 just fall straight through the world.
> Removed error message when shape margin exceeds shape extents

- src/jolt_physics_direct_space_state_3d.cpp
- src/jolt_query_collectors.hpp
This PR replaces `JoltQueryCollectorAny`, which until now has allowed for multiple hits, with one that only allows a single hit. The previous one is now called `JoltQueryCollectorAnyMulti` instead.
This PR also adds a `reset` method to every collector, allowing them to be used in multiple queries, and also makes the inline capacity of the collectors an explicit template parameter.
Both of these changes are needed for an upcoming refactoring of `cast_motion`.
> Added new query collector and improved existing ones

- src/jolt_physics_direct_space_state_3d.cpp
It seems that currently, in certain random cases, a `CharacterBody3D` can end up standing on solid ground while still having `move_and_slide` report no collision, because `body_motion_recovery` ends up pushing the body above the ground which leads to `body_motion_collision` hitting nothing.
Godot seemed to have solved this problem by using a couple of magic numbers that essentially just restrict how much recovery motion you're allowed to do. I had deliberately ignored these when implementing `body_test_motion` because I didn't understand their purpose, but it seems they were indeed necessary.
There might be some better way of solving this, but I figured it'd be best to try and align with Godot Physics as much as possible, given how fragile everything related to `body_test_motion` is.
> Fixed issue where motion recovery inhibited rest info

- CMakeLists.txt
- src/jolt_motion_filter_3d.cpp
- src/jolt_motion_shape.cpp
- src/jolt_motion_shape.hpp
- src/jolt_physics_direct_space_state_3d.cpp
- src/jolt_physics_direct_space_state_3d.hpp
- src/jolt_shape_3d.hpp
- src/jolt_space_3d.cpp
- src/jolt_space_3d.hpp
- src/pch.hpp
This PR replaces the implementation of `cast_motion` and `body_motion_cast`, which previously relied on Jolt's `CastShape`, with a `CollideShape`-powered binary search.
It ended up being too difficult to iron out all the issues that came with trying to shoehorn Jolt's `CastShape` into the safe/unsafe fraction that Godot's `cast_motion` outputs, so I caved in and implemented the same binary search that Godot Physics uses.
I'll probably expose a more suitable shape-casting method, that uses `CastShape`, later down the road.
> Refactored shape-casting to use binary search

- cmake/GodotJoltExternalLibrary.cmake
Apparently the `CMAKE_C_COMPILER` variable is never set when using CMake's Visual Studio generators, such as `Visual Studio 17 2022`, presumably because they don't have a dedicated C compiler. So this PR makes sure to only forward it to the external libraries if it is defined.
> Fixed `CMAKE_C_COMPILER` warning when targeting Visual Studio

- cmake/GodotJoltExternalGodotCpp.cmake
This bumps godot-cpp from godot-jolt/godot-cpp@f9f0200fac1c122dc477269e7e9ef981dc620bfc aka `4.0.1-stable` to godot-jolt/godot-cpp@576431062f94ba19c43fc6733d03681090a89699 aka `4.0.1-stable` (see diff [here](https://github.com/godot-jolt/godot-cpp/compare/f9f0200fac1c122dc477269e7e9ef981dc620bfc...576431062f94ba19c43fc6733d03681090a89699)).
This introduces a (somewhat hacky) fix to a long-standing problem in godot-cpp where you weren't able to use many of the singleton classes because their engine counterpart would outlive the extension library. Once the engine counterpart got destroyed it would try and call the library-provided callback to also destroy the instance bindings, at which point the library would already be unloaded, leading to a use-after-free. See godotengine/godot-cpp#889 …
> Updated godot-cpp to 576431062f (4.0.1-stable)

- src/containers/free_list.hpp
- src/jolt_job_system.cpp
- src/jolt_job_system.hpp
- src/jolt_physics_server_3d.cpp
- src/jolt_physics_server_3d.hpp
- src/pch.hpp
This replaces Jolt's reference job system implementation (`JPH::JobSystemThreadPool`) with one powered by Godot's `WorkerThreadPool` instead, which should hopefully interact better with the rest of the engine and lessen any potential contention.
> Added job system based on `WorkerThreadPool`

- src/jolt_shape_3d.cpp
- src/jolt_shape_3d.hpp
- src/misc/scope_guard.hpp
- src/pch.hpp
This fixes an issue where if you modify any shape data, such as the radius of a `SphereShape3D` or the margin of a `BoxShape3D`, the bodies who currently use that shape would not have their `JPH::Shape` rebuilt. This could lead to problems in the editor where you would use the "Snap to Floor" feature after having changed the extents of a shape and find that it snapped to the old extents.
> Fixed issue with shapes not rebuilding when changed

- .clang-format
- src/jolt_area_3d.cpp
- src/jolt_body_3d.cpp
- src/jolt_contact_listener.cpp
- src/jolt_generic_6dof_joint_3d.cpp
- src/jolt_physics_direct_space_state_3d.cpp
- src/jolt_ray_shape.cpp
This makes all the clang-format penalties explicit and changes a couple of them. These are used to control how clang-format prioritizes things like line breaks versus indentation.
I was unhappy with the line breaks applied after assignment operators, so I cranked up `PenaltyBreakAssignment` to essentially prevent this from ever happening. I also slightly bumped `PenaltyIndentedWhitespace` in order to suppress some of clang-format's habit of making big blocks of whitespace. The rest of the changes had no real impact currently, but seemed appropriate either way.
> Changed clang-format penalties

- src/jolt_collision_object_3d.cpp
- src/jolt_collision_object_3d.hpp
- src/jolt_physics_server_3d.cpp
- src/jolt_shape_instance_3d.cpp
- src/jolt_shape_instance_3d.hpp
It seems I was a bit sloppy with #252 and left out a couple of `Transform3D` usages that needed to take scaling into account, so this PR addresses exactly that.
> Fixed issues with shape scaling

- src/jolt_body_3d.cpp
This was more of a theoretical problem than a practical one, since `principal_inertia_axes` is only accessible from `RigidBody3D.integrate_forces`, within which we can never actually lock the underlying Jolt body anyway.
> Fixed potential double-lock in `get_principal_inertia_axes`

- src/jolt_physics_direct_space_state_3d.cpp
- src/jolt_physics_direct_space_state_3d.hpp
This fixes some jitter and various other problems when (for example) a `CharacterBody3D` is wedged inbetween two shapes.
I had tried to skip the iterative solving done during the recovery phase, unlike what pretty much every other character controller does, but having a capsule-shaped `CharacterBody3D` walk up against a wedge at even low speeds showed how broken that approach was. So this PR adds that exact thing.
I also realized that shape-casting is done differently during `body_test_motion`, where it will actually respect initial overlaps, which also created problems when stuck, so I added a parameter to `cast_motion` to handle that.
I also snuck in a lower bound of 0.0001 to the `margin` parameter of `body_test_motion`, to better align with Godot Physics.
> Fixed issues with `body_test_motion` when stuck

- src/jolt_shape_3d.cpp
- src/jolt_shape_3d.hpp
Shape construction had become a bit of a mess lately, so I decided to simplify things a bit.
Here's a rough overview of the changes:
- All error-handling now happens in the shape's `build` method, instead of being split between `set_data` and `build`
- All invalid shapes now emit errors, even zero-sized shapes
- The `is_valid` method has been removed in favor of letting the error-handling in `build` deal with it
- The `clear` method has been removed in favor of just resetting `jolt_ref`
- All shapes now have a `to_string` method to make error-handling more manageable
- The `shape_changed` method has been renamed to `rebuild`
This also fixes setting shape margins to anything but their default value. I had been incorrectly calling `clear()` in `set_margin`, which of course cleared all the …
> Refactored construction of shapes

- src/jolt_area_3d.cpp
- src/jolt_area_3d.hpp
- src/jolt_body_3d.cpp
- src/jolt_body_3d.hpp
- src/jolt_collision_object_3d.cpp
- src/jolt_collision_object_3d.hpp
This changes the way collision objects (bodies and areas) deal with their "initial state", to allow for moving said collision objects inbetween two physics spaces.
Until now there's been a bunch of `initial_*` members in the collision objects, which has served to populate the eventual `JPH::BodyCreationSettings` once the body gets added to a space. Now instead the creation settings gets allocated along with the object itself and deallocated once the object is fully created within the space. This lets us remove all the previously mentioned `initial_*` members and instead use the creation settings directly as an intermediate storage.
What this also allows for is populating this intermediate `JPH::BodyCreationSettings`, using `JPH::Body::GetBodyCreationSettings`, when a body is moved between …
> Refactored object construction to allow moving between spaces

- src/jolt_body_3d.hpp
- src/jolt_physics_direct_space_state_3d.cpp
- src/jolt_physics_server_3d.cpp
This adds support for the `collision_priority` property on `CollisionObject3D`, which helps with preventing things like `CharacterBody3D` clipping through walls that absolutely shouldn't be clipped through.
As of writing this collision priority is only really a thing that affects `body_test_motion` in Godot Physics, but it seems like there are plans/hopes of adding this to Godot's general collision solver. Once that happens (if ever) then things will probably diverge a bit in terms of support.
> Added support for collision priority in `body_test_motion`

- src/jolt_physics_direct_body_state_3d.cpp
- src/jolt_physics_server_3d.cpp
- src/misc/error_macros.hpp
Until now there's been a ton of errors emitted into `stdout` when you start up the editor, from places related to `SoftBody3D` and `PhysicsDirectBodyState3D`. This seems to be because the editor will, during documentation generation, instantiate classes that have been registered in `ClassDB` and run any property getters in order to figure out the default values of those properties.
To fix the issue with `PhysicsDirectBodyState3D` I added a couple of extra error macros that not only do not emit error messages, but also disappear completely in non-editor builds. This removes any potential branching from checking the `body` pointer, which is more or less guaranteed to never be `nullptr` anyway.
For `SoftBody3D` there needed to be an actually valid RID allocated, so that the documentation …
> Fixed error spam when starting editor

- src/jolt_physics_direct_space_state_3d.cpp
- src/jolt_physics_direct_space_state_3d.hpp
- src/jolt_shape_3d.cpp
- src/jolt_shape_3d.hpp
This changes the way the `margin` parameter is implemented in physics queries, such as [`intersect_shape`](https://docs.godotengine.org/en/4.0/classes/class_physicsdirectspacestate3d.html#class-physicsdirectspacestate3d-method-intersect-shape).
I had originally implemented these the same way that the Bullet implementation in Godot 3 does, which was somewhat crude, by rebuilding the shape on every single query and extending its dimensions by the margin. This was not only potentially costly but also unnecessary since Jolt already supports this type of margin through `JPH::CollideShapeSettings::mMaxSeparationDistance`, which I was already using for `body_test_motion`. So this PR makes use of exactly that.
> Refactored how physics query margins are implemented

- src/jolt_area_3d.cpp
- src/jolt_body_3d.cpp
- src/jolt_body_3d.hpp
- src/jolt_collision_object_3d.cpp
- src/jolt_collision_object_3d.hpp
There were inconsistencies in the naming and usage of `*_changed` methods that needed to be addressed.
Instead of giving the name `*_changed` to any sort of reactive change, I now make the distinction between methods that are meant to represent a value changing and the methods are meant to produce some side effect. The former are still called `*_changed` and the latter are now instead called `update_*`.
This is needed for an upcoming PR that deals with waking up sleeping bodies.
> Refactored methods related to reactive changes

- src/jolt_area_3d.hpp
- src/jolt_body_3d.cpp
- src/jolt_body_3d.hpp
- src/jolt_collision_object_3d.cpp
- src/jolt_collision_object_3d.hpp
- src/jolt_physics_direct_body_state_3d.cpp
This changes a number of things related to the sleep state of bodies:
- More wake-ups have been added.
- Some places that previously did a wake-up now check that the relevant value has changed first.
- The `initial_sleep_state` member of `JoltBody3D` has been removed, since it doesn't serve much purpose currently, due to Godot disrupting any initial sleep state with `NOTIFICATION_ENTER_WORLD`.
- Only non-sleeping bodies will now integrate things like gravity and constant forces/torques, to prevent them from accumulating while sleeping.
> Changed various things related to sleeping

- cmake/GodotJoltExternalGodotCpp.cmake
This bumps godot-cpp from godot-jolt/godot-cpp@576431062f94ba19c43fc6733d03681090a89699 aka `4.0.1-stable` to godot-jolt/godot-cpp@716178a3d6c24b49df0fb6f1a1aa1782b8df7952 aka `4.0.2-stable` (see diff [here](https://github.com/godot-jolt/godot-cpp/compare/576431062f94ba19c43fc6733d03681090a89699...716178a3d6c24b49df0fb6f1a1aa1782b8df7952)).
> Updated godot-cpp to 4.0.2-stable

- src/jolt_collision_object_3d.cpp
- src/jolt_job_system.cpp
- src/jolt_job_system.hpp
- src/jolt_physics_direct_space_state_3d.cpp
- src/jolt_physics_server_3d.cpp
- src/jolt_project_settings.cpp
- src/jolt_project_settings.hpp
- src/jolt_space_3d.cpp
- src/jolt_temp_allocator.hpp
- src/pch.hpp
- src/register_types.cpp
This adds a number of project settings, under `physics/jolt_3d/...`, that help get rid of a bunch of hardcoded constants that were spread throughout the code.
Here's the list of project settings:
- Sleep enabled
- Sleep velocity threshold
- Sleep time threshold
- Kinematic recovery iterations (for `body_test_motion`)
- Kinematic recovery speed (for `body_test_motion`)
- Solver velocity iterations
- Solver position iterations
- Stabilization factor
- Speculative contact distance
- Allowed contact penetration
- More deterministic simulation (no guarantee, hence the wording)
- Max number of bodies
- Max number of body pairs
- Max number of contact constraints
- Max temporary memory
I need to add in-editor descriptions to all these new project settings somehow, but it doesn't seem like that's …
> Added project settings

- src/jolt_area_3d.cpp
- src/jolt_area_3d.hpp
This adds support for `disable_mode` in `Area3D`. More specifically it adds support for `DISABLE_MODE_REMOVE`, which was the only mode that wasn't working as intended previously.
I suspect this also fixes a more general issue with areas, where if you destroyed an area it wouldn't report its overlapping bodies/areas as having exited.
> Added support for `disable_mode` in `Area3D`

- src/jolt_body_3d.cpp
Apparently you must deactive a body that's about to become static, and activate it when it goes the other way. This was something I had been doing previously, but removed in #267, which turned out to be a mistake.
> Fixed assert triggering when changing body mode to static

- cmake/GodotJoltExternalJolt.cmake
This bumps Jolt from godot-jolt/jolt@bc4fa997f15f2953dc87ee5c1ba51ecf2077c287 to godot-jolt/jolt@3d36f7aea85fcea4b0de5404c953e40db0a749ba (see diff [here](https://github.com/godot-jolt/jolt/compare/bc4fa997f15f2953dc87ee5c1ba51ecf2077c287...3d36f7aea85fcea4b0de5404c953e40db0a749ba)).
This brings in error codes to `JPH::PhysicsSystem::Update`, which will be used to emit warnings about having exceeded some of the limits specified in the project settings.
This also brings in a fix for `JPH::OffsetCenterOfMassShape`, where it would ignore the scaling of any `JPH::ScaledShape` wrapped around it, which is needed to support the scaling of bodies.
> Updated Jolt to 3d36f7aea8

- src/jolt_area_3d.cpp
- src/jolt_body_3d.cpp
- src/jolt_collision_object_3d.cpp
- src/jolt_collision_object_3d.hpp
- src/jolt_cone_twist_joint_3d.cpp
- src/jolt_generic_6dof_joint_3d.cpp
- src/jolt_hinge_joint_3d.cpp
- src/jolt_physics_direct_body_state_3d.cpp
- src/jolt_physics_direct_space_state_3d.cpp
- src/jolt_physics_direct_space_state_3d.hpp
- src/jolt_physics_server_3d.cpp
- src/jolt_pin_joint_3d.cpp
- src/jolt_shape_3d.cpp
- src/jolt_shape_3d.hpp
- src/jolt_shape_instance_3d.hpp
- src/jolt_slider_joint_3d.cpp
I had been under the impression that Godot Physics ignored scaling on all types of bodies, and I had therefore discarded the body's scale completely in #252. This turned out to not be true. Godot Physics only seems to ignore scaling on `RigidBody3D`, so I did a bit of refactoring to accommodate for body scaling as well.
This does add support for scaling _all_ types of bodies, including `RigidBody3D`, although I can't speak to the soundness of actually using it on `RigidBody3D`. Considering that Godot Physics doesn't support it I wouldn't be surprised if some issues arose within the actual node. Either way, Godot will still emit a node configuration warning when you try to scale a `RigidBody3D`, which is the price we have to pay for piggybacking on the default node types I guess.
> Added support for scaling bodies

- src/jolt_body_3d.cpp
- src/jolt_body_accessor_3d.cpp
- src/jolt_collision_object_3d.cpp
- src/jolt_job_system.cpp
- src/jolt_space_3d.cpp
- src/jolt_temp_allocator.hpp
This makes use of the newly introduced `JPH::EPhysicsUpdateError` that allows for emitting log messages when some of Jolt's limits were hit, like the maximum number of contact constraints or maximum number of body pairs, as specified in the project settings.
I took the opportunity to modify some of the existing log messages as well changing the `CRASH_NOW` that happens when you exceed the maximum number of bodies to instead be `ERR_FAIL`. It's likely that it'll crash somewhere else anyway, but at least now we give it a fighting chance, which is important since this can technically happen while we're working in the editor.
> Added logging of Jolt errors

- src/shapes/jolt_shape_3d.cpp
`CSGCombiner3D` creates a `ConcavePolygonShape3D` that for whatever reason gets initialized with a vertex count of 0 to begin with, so we have to ignore that in order to not emit a bunch of pointless errors.
> Fixed error about vertex count when using `CSGCombiner3D`

- docs/building.md
Since people still seem to be running into #66, despite my changes in #69, I'm gonna try and be more explicit about Visual Studio's "Developer ..." command prompts not being supported for x64 builds.
> Updated the build documentation for Windows

- src/joints/jolt_generic_6dof_joint_3d.hpp
- src/objects/jolt_area_3d.hpp
- src/objects/jolt_body_3d.hpp
- src/objects/jolt_collision_object_3d.hpp
- src/servers/jolt_physics_server_3d.hpp
- src/shapes/jolt_ray_shape.hpp
- src/shapes/jolt_shape_3d.hpp
- src/spaces/jolt_contact_listener_3d.hpp
- src/spaces/jolt_debug_geometry_3d.cpp
- src/spaces/jolt_debug_geometry_3d.hpp
- src/spaces/jolt_debug_renderer_3d.hpp
- src/spaces/jolt_job_system.hpp
- src/spaces/jolt_layer_mapper.hpp
- src/spaces/jolt_space_3d.cpp
- src/spaces/jolt_space_3d.hpp
This reorders any class/struct members from largest to smallest in an effort to minimize any padding that might arise inbetween them. It doesn't do a perfect job, but it does shave off a couple of bytes here and there.
> Reordered class/struct members to reduce padding

- src/spaces/jolt_space_3d.cpp
The locking has never really been necessary, due to no multi-threading happening outside of `JPH::PhysicsSystem::Update`, so I'm disabling it in `Distribution` configurations in exchange for whatever performance benefit it might offer.
I'm leaving it enabled in `Debug` and `Development` configurations just to keep myself in check with regards to any potential deadlocks, for whenever I'm ready to make a decision on how to approach multi-threading.
> Disabled locking of bodies in `Distribution` configurations

- CMakeLists.txt
This adds compile definitions to allow for compile-time differences between the various platforms.
The definitions introduced are:
- `GJ_PLATFORM_WINDOWS`
- `GJ_PLATFORM_LINUX`
- `GJ_PLATFORM_MACOS`
I also took the opportunity to refactor the way the library suffix is constructed, by using generator expressions instead of regular if-statements.
> Added compile definitions for the various platforms

- cmake/GodotJoltExternalLibrary.cmake
I forgot to set this for the third-party dependencies in #294, which is really where the majority of the space-savings are gonna come from.
> Changed default symbol visibility for dependencies

- CMakeLists.txt
This makes it so debug symbols are extracted (and stripped) for `Distribution` and `EditorDistribution` builds on Linux and macOS, so as to not distribute gigantic binaries full of debug symbols.
> Added extraction of debug symbols on Linux and macOS

- src/spaces/jolt_body_accessor_3d.hpp
Fixes #298.
This reverts the removal of some null checks that I had removed from `JoltAccessibleBody3D` as part of the cleanup in #282.
I'm not quite sure what I was thinking there.
> Reverted removal of null checks from #282

- src/objects/jolt_body_3d.cpp
- src/servers/jolt_project_settings.cpp
- src/servers/jolt_project_settings.hpp
This adds two new project settings that allows configuring Jolt's maximum linear and angular velocities that a body can have. I figured this might be a good thing to expose since it might not otherwise be obvious that there's an upper bound on these.
The settings are:
- Max Linear Velocity (`physics/jolt_3d/limits/max_linear_velocity`)
- Max Angular Velocity (`physics/jolt_3d/limits/max_angular_velocity`)
> Added project settings for maximum velocities

- .github/actions/setup-linux/action.yml
- .github/actions/setup-macos/action.yml
- .github/actions/setup-windows/action.yml
- .github/workflows/analyze.yml
- .github/workflows/build-linux.yml
- .github/workflows/build-macos.yml
- .github/workflows/build-windows.yml
- scripts/ci_setup_linux.ps1
This PR removes the explicit toolchain versions that were strewn all over the CI workflows, in favor of default values in each platform's setup action.
I also added explicit installation of the relevant LLVM packages, because GitHub's Ubuntu runners seem to be lagging behind on updating to LLVM 15 for some reason, which I will switch to in an upcoming PR.
This PR also splits the `Version` parameter for `ci_setup_linux.ps1` to instead be `VersionGcc` and `VersionLlvm`. This allows for being explicit about the GCC version to install when setting up an LLVM environment, which is useful because Clang defaults to using libstdc++ on Linux.
This doesn't actually guarantee that this version will be the one actually used by Clang, since Clang will still pick the largest version number of GCC …
> Refactored toolchain version handling for CI builds

- CMakeLists.txt
- LICENSE.txt
I wasn't sure if I should update the copyright year at all, but it seems like most tech organizations are moving away from updating it, Godot included.
The [general consensus](https://hynek.me/til/copyright-years/) seems to be that the year is pointless from a legal perspective, so it might as well be removed altogether.
> Removed the copyright year

- .github/workflows/analyze.yml
- .github/workflows/build-linux.yml
- .github/workflows/build-macos.yml
- .github/workflows/build-windows.yml
- .github/workflows/package.yml
- scripts/ci_sign_macos.ps1
I'm gonna give myself one of these, due to the amount of work this took: 🎉
This workflow will build, prepare, sign (for macOS), package and upload builds for any version tag that's pushed.
It will however not create a GitHub release automatically, since the code signing for Windows binaries has to happen locally.
I also changed the event triggers for the regular build/analyze workflows to not trigger when pushing tags.
> Added CI workflow for packaging releases

- cmake/GodotJoltExternalMimalloc.cmake
This bumps mimalloc from godot-jolt/mimalloc@3e313478d91c04ac5821743688ce55fc27432c4f aka `v2.1.1` to godot-jolt/mimalloc@3e313478d91c04ac5821743688ce55fc27432c4f aka `v2.1.2` (see diff [here](https://github.com/godot-jolt/mimalloc/compare/3e313478d91c04ac5821743688ce55fc27432c4f...43ce4bd7fd34bcc730c1c7471c99995597415488)).
> Updated mimalloc to 2.1.2

- .github/workflows/build-linux.yml
- .github/workflows/build-macos.yml
- .github/workflows/build-windows.yml
- CMakeLists.txt
- CMakePresets.json
This removes the `/WX` and `-Werror` flags from MSVC-like and GCC-like builds respectively when just building normally, in favor of explicitly adding them to the CI builds and any CMake user preset instead.
I figured if people start using some new compiler version before I do, it'd be nice not to block them just because the newer compiler might have stricter warnings.
I also realized that the way these flags have been passed previously has actually been stomping the default `CMAKE_CXX_FLAGS`, which turned out to be why `/EHsc` had to be added explicitly. I went ahead and removed that (now redundant) flag as part of this change.
> Removed "warnings as errors" flags for non-dev builds

- README.md
It seems I missed this bit in #310.
> Fixed outdated reference to third-party notices in README

- CMakePresets.json
It seems I missed this one when removing the other similar flags in #318.
Similar to that one, this one also caused `CMAKE_CXX_FLAGS` to get stomped, meaning clang-cl builds have been running with exception-handling disabled since #318 was merged.
> Removed "warnings as errors" flag for clang-cl builds

- CMakeLists.txt
This disables support for exception-handling and thus removes the stack-unwinding needed for exception-handling, on all platforms.
Since there's not really any exception-handling happening anywhere in the code I figured I might as well disable support for exception-handling altogether. This mainly helps in saving a couple of kilobytes in binary size, from not having all the stack-unwinding code be generated anymore.
> Disabled support for exception-handling

- scripts/run_clang_format.ps1
Apparently the clang-format script that's run during CI has been globbing the wrong file extension for header files for who knows how long.
Thankfully there wasn't a single formatting issue in any of them.
> Fixed incorrect glob in clang-format script

- src/servers/jolt_physics_server_3d.cpp
- src/shapes/jolt_shape_impl_3d.cpp
- src/shapes/jolt_shape_impl_3d.hpp
This replaces the previous "Not implemented" error message, when trying to set the custom solver bias for shapes, with a more descriptive warning message. It also removes the previous "Not implemented" error message when the solver bias value is just being fetched.
> Added explicit non-support for shape solver bias

- .github/workflows/package.yml
This allows the CI packaging to trigger on version tags that look like `v0.1.0-beta1` as opposed to just `v0.1.0`.
> Updated CI packaging to allow version tags with status

- cmake/GodotJoltExternalJolt.cmake
This bumps Jolt from godot-jolt/jolt@3d36f7aea85fcea4b0de5404c953e40db0a749ba to godot-jolt/jolt@f340da6a18ef83f86ee46b8d7352c79d467c56d9 (see diff [here](https://github.com/godot-jolt/jolt/compare/3d36f7aea85fcea4b0de5404c953e40db0a749ba...f340da6a18ef83f86ee46b8d7352c79d467c56d9)).
This brings in fixes for warnings emitted when compiling with MSVC 14.36.
> Updated Jolt to f340da6a18

- cmake/GodotJoltExternalGodotCpp.cmake
This bumps godot-cpp from godot-jolt/godot-cpp@0274efdb07207c01ac15e74a50f875986c62b09b aka `4.0.2-stable` to godot-jolt/godot-cpp@78f709c74450d5dcfe1a3510dede8d5b67e42502 aka `4.0.3-stable` (see diff [here](https://github.com/godot-jolt/godot-cpp/compare/0274efdb07207c01ac15e74a50f875986c62b09b...78f709c74450d5dcfe1a3510dede8d5b67e42502)).
> Updated godot-cpp to 4.0.3

- .github/actions/setup-linux/action.yml
- .github/workflows/analyze.yml
- .github/workflows/build-linux.yml
- .github/workflows/package.yml
- README.md
- scripts/ci_setup_linux.ps1
Related to #378.
This downgrades the CI workflows from Ubuntu 22.04 (Jammy Jellyfish) to Ubuntu 20.04 (Focal Fossa).
This is an effort to provide broader support for Linux. The default toolchains in most (all?) Linux distros will tie you to a minimum version of glibc, so we're forced to use an earlier version of Ubuntu to provide support for distros like Debian ("bullseye") stable, which is on the same version of glibc as Ubuntu 20.04.
> Downgraded CI workflows to Ubuntu 20.04

- CHANGELOG.md
- src/joints/jolt_generic_6dof_joint_impl_3d.cpp
Fixes #395.
Angular motors for `Generic6DOFJoint` have been rotating in the opposite direction (counter-clockwise) compared to Godot Physics (clockwise).
> Fixed 6DOF angular motors rotating in the "wrong" direction

- src/precompiled.hpp
- src/spaces/jolt_layer_mapper.cpp
- src/spaces/jolt_layer_mapper.hpp
This changes `JoltLayerMapper` to use an `InlineVector` for its mapping between object layers and collision layers/masks, replacing the current `HashMap`.
This also removes all the mutex stuff in `JoltLayerMapper`, since none of that was ever necessary and more of a "just to be safe" development thing. There's never any writing happening concurrently with reading in that class.
> Simplified mapping of object layers

- cmake/GodotJoltExternalJolt.cmake
This bumps Jolt from godot-jolt/jolt@f340da6a18ef83f86ee46b8d7352c79d467c56d9 to godot-jolt/jolt@f084fd75376a3c1bcf99b1b63e41710f71d98004 (see diff [here](https://github.com/godot-jolt/jolt/compare/f340da6a18ef83f86ee46b8d7352c79d467c56d9...f084fd75376a3c1bcf99b1b63e41710f71d98004)).
- Removed limits on restitution
- Removed limits on friction
- Added functions to reset force/torque
- Bugfix to speculative contact handling
> Updated Jolt to f084fd7537

- CHANGELOG.md
- README.md
- src/objects/jolt_body_impl_3d.cpp
- src/objects/jolt_body_impl_3d.hpp
- src/servers/jolt_physics_server_3d.cpp
Fixes #332.
This adds support for the [`custom_integrator`](https://docs.godotengine.org/en/4.0/classes/class_rigidbody3d.html#class-rigidbody3d-property-custom-integrator) property on `RigidBody3D` as well as `PhysicalBone3D`, allowing you to omit the integration of gravity and damping, and instead integrate them yourself.
> Added support for custom integrators

- CHANGELOG.md
- docs/settings.md
- src/servers/jolt_project_settings.cpp
- src/servers/jolt_project_settings.hpp
- src/spaces/jolt_contact_listener_3d.cpp
- src/spaces/jolt_space_3d.cpp
Relates to #374.
This adds a new project setting called "Bounce Velocity Threshold" that controls the minimum velocity needed before a collision can be elastic.
> Added project setting "Bounce Velocity Threshold"

- CHANGELOG.md
- src/objects/jolt_body_impl_3d.cpp
- src/spaces/jolt_space_3d.cpp
Fixes #396.
This makes use of Jolt's custom friction/restitution combiners in order to better align with how Godot Physics behaves. This also has the side effect of enabling support for the "Rough" and "Absorbent" physics material properties.
I also found a bug where friction set on an already created/active/entered body would instead set restitution, so I included that fix here.
> Added custom combiners for friction and restitution

- CHANGELOG.md
- src/shapes/jolt_box_shape_impl_3d.cpp
- src/shapes/jolt_cylinder_shape_impl_3d.cpp
As discussed in #379.
This removes the warnings, for boxes and cylinders, that are emitted when the margin is greater than its minimum half extent.
The margin is now instead interpreted as an upper bound, and computed based on an arbitrary factor of the shape's minimum half extent.
> Changed shape margins to be interpreted as an upper bound

- cmake/GodotJoltExternalJolt.cmake
This bumps Jolt from godot-jolt/jolt@f084fd75376a3c1bcf99b1b63e41710f71d98004 to godot-jolt/jolt@8d3008e21baff6ce774b821adc73618bb3b891af (see diff [here](https://github.com/godot-jolt/jolt/compare/f084fd75376a3c1bcf99b1b63e41710f71d98004...8d3008e21baff6ce774b821adc73618bb3b891af)).
- Added ability to set a surface velocity through a ContactListener (needed for [#331](https://github.com/godot-jolt/godot-jolt/issues/331))
> Updated Jolt to 8d3008e21b

- CHANGELOG.md
- README.md
- src/objects/jolt_body_impl_3d.cpp
- src/objects/jolt_body_impl_3d.hpp
- src/spaces/jolt_contact_listener_3d.cpp
- src/spaces/jolt_contact_listener_3d.hpp
Fixes #331.
This adds support for the [`constant_linear_velocity`](https://docs.godotengine.org/en/4.0/classes/class_staticbody3d.html#class-staticbody3d-property-constant-linear-velocity) and [`constant_angular_velocity`](https://docs.godotengine.org/en/4.0/classes/class_staticbody3d.html#class-staticbody3d-property-constant-angular-velocity) properties on `StaticBody3D`, as well as changing the `linear_velocity` and `angular_velocity` properties on frozen bodies to instead be interpreted as surface/constant velocities.
> Added support for surface velocities on static/kinematic bodies

- src/objects/jolt_physics_direct_body_state_3d.cpp
Complements #332 and #403.
This adds support for the [`integrate_forces`](https://docs.godotengine.org/en/latest/classes/class_physicsdirectbodystate3d.html#class-physicsdirectbodystate3d-method-integrate-forces) method on `PhysicsDirectBodyState3D`, which performs the default force integration, integrating gravity and damping.
> Added support for manual force integration

- CHANGELOG.md
- src/objects/jolt_body_impl_3d.cpp
- src/objects/jolt_body_impl_3d.hpp
- src/spaces/jolt_space_3d.cpp
This is something I happened to stumble upon.
Right after freezing a moving `RigidBody3D`, using the "Static" freeze mode, you would end up with the actual underlying physics body having moved further ahead than the node itself.
This turned out to be because static bodies instantly go to sleep, which means they would get skipped over by `acquire_active` in `call_queries`, and therefore not have their `body_state_callback` invoked.
Now instead we mark bodies with a dirty flag if they've had `integrate_forces` called (i.e. they've been rigid/dynamic) in the past tick and we instead do `acquire_all` in `call_queries`, but only invoke `body_state_callback` if the dirty flag is set.
> Fixed de-sync between node and body when freezing

- src/joints/jolt_cone_twist_joint_impl_3d.cpp
- src/joints/jolt_generic_6dof_joint_impl_3d.cpp
- src/joints/jolt_hinge_joint_impl_3d.cpp
- src/joints/jolt_joint_impl_3d.cpp
- src/joints/jolt_joint_impl_3d.hpp
- src/joints/jolt_pin_joint_impl_3d.cpp
- src/joints/jolt_slider_joint_impl_3d.cpp
- src/objects/jolt_area_impl_3d.cpp
- src/objects/jolt_body_impl_3d.cpp
- src/objects/jolt_object_impl_3d.cpp
- src/objects/jolt_object_impl_3d.hpp
- src/servers/jolt_physics_server_3d.cpp
- src/shapes/jolt_box_shape_impl_3d.cpp
- src/shapes/jolt_capsule_shape_impl_3d.cpp
- src/shapes/jolt_concave_polygon_shape_impl_3d.cpp
- src/shapes/jolt_convex_polygon_shape_impl_3d.cpp
- src/shapes/jolt_cylinder_shape_impl_3d.cpp
- src/shapes/jolt_height_map_shape_impl_3d.cpp
- src/shapes/jolt_separation_ray_shape_impl_3d.cpp
- src/shapes/jolt_shape_impl_3d.cpp
- src/shapes/jolt_shape_impl_3d.hpp
- src/shapes/jolt_sphere_shape_impl_3d.cpp
- src/shapes/jolt_world_boundary_shape_impl_3d.cpp
- src/spaces/jolt_layer_mapper.cpp
Fixes #379.
This improves error/warning messages in the following ways:
- Messages regarding objects now include their name, or `<unknown>` if the instance ID is invalid
- Messages regarding shapes now include a random owner's name and owner count
- Messages regarding joints now include the names of the bodies they connect
- `JoltLayerMapper` now spells out more clearly what exceeding object layers actually means
- Failing to free an RID now explains why
> Added more context to error/warning messages

- cmake/GodotJoltExternalLibrary.cmake
- cmake/GodotJoltExternalMimalloc.cmake
Due to the need for disabling compiler warnings while compiling mimalloc it appears that some of the default compiler flags normally found in `CMAKE_C_ARGS` had been getting squashed, and overridden completely by `/W0` or `-w`.
This PR adds the ability to provide environment variables through `gdj_add_external_library` and uses the environment variable `CLFAGS` to instead properly merge `/W0` or `-w` with the default compiler flags.
> Fixed issue with mimalloc compiler flags getting squashed

- src/spaces/jolt_body_accessor_3d.cpp
When trying to acquire/lock a Jolt body without a valid space, you would end up crashing in one of these acquire methods.
I figured it's better to just early-out and have the user face whatever shower of subsequent errors there might be, so this PR adds exactly that.
> Added null checks to `acquire` methods on body accessor

- src/servers/jolt_globals.cpp
The assert function passed to Jolt has until now used `ERR_PRINT` followed by `CRASH_NOW` because there were issues with the stream not flushing fast enough when just using `CRASH_NOW_MSG`, but that has since been resolved, so I changed this back to use `CRASH_NOW_MSG` instead.
Note that this assert function is not used at all in regular distribution builds of Godot Jolt.
> Changed Jolt assert function to use `CRASH_NOW_MSG`

- src/objects/jolt_body_impl_3d.cpp
- src/objects/jolt_body_impl_3d.hpp
Until now the group filter held by the actual Jolt body has been used as the sole storage for collision exceptions. However, this doesn't carry over through `JPH::BodyCreationSettings`, and as such you end up losing all the collision exceptions when leaving or going between spaces. This also prevented one from adding collision exceptions before the body entered a scene tree.
This PR instead makes the group filter a part of `JoltBodyImpl3D` and sets/updates it on the Jolt body when appropriate.
> Refactored group filters to accommodate for space changes

- CHANGELOG.md
- src/joints/jolt_cone_twist_joint_impl_3d.cpp
- src/joints/jolt_cone_twist_joint_impl_3d.hpp
- src/joints/jolt_generic_6dof_joint_impl_3d.cpp
- src/joints/jolt_generic_6dof_joint_impl_3d.hpp
- src/joints/jolt_hinge_joint_impl_3d.cpp
- src/joints/jolt_hinge_joint_impl_3d.hpp
- src/joints/jolt_joint_impl_3d.cpp
- src/joints/jolt_joint_impl_3d.hpp
- src/joints/jolt_pin_joint_impl_3d.cpp
- src/joints/jolt_pin_joint_impl_3d.hpp
- src/joints/jolt_slider_joint_impl_3d.cpp
- src/joints/jolt_slider_joint_impl_3d.hpp
- src/misc/utility_functions.hpp
- src/objects/jolt_body_impl_3d.cpp
- src/objects/jolt_body_impl_3d.hpp
- src/precompiled.hpp
- src/servers/jolt_physics_server_3d.cpp
Fixes #333.
Fixes #343.
Fixes #344.
Fixes #393.
This is a major refactoring of how joints are built at runtime.
This changes all the joints to be rebuilt in the same manner as what `Generic6DOFJoint` has been doing until now. On top of this `JoltBodyImpl3D` will now also keep track of any joints connected to it, so that it can destroy/rebuild the joints whenever it goes through a space change, meaning when the underlying Jolt body is destroyed/created.
This helps resolve some crashes and other weird errors whenever you would do things like disable/remove a body that's currently connected to a joint.
I also snuck in changes to how limits are dealt with for hinges and sliders, so that they are now as flexible in their limits as what `Generic6DOFJoint` has been until now, where it shifts the …
> Refactored joints to accommodate for space changes

- src/servers/jolt_globals.cpp
This removes the setting of `JPH::Trace`, which I believe is meant to serve as a way for Jolt to log stuff in the host application.
Since this doesn't seem to be used for anything important, I figured I might as well remove the setting of it for non-debug builds and rely on the no-op default implementation instead.
> Removed setting of Jolt's `Trace` function for non-debug builds

- CHANGELOG.md
- src/objects/jolt_area_impl_3d.hpp
- src/objects/jolt_body_impl_3d.hpp
- src/objects/jolt_object_impl_3d.cpp
- src/objects/jolt_object_impl_3d.hpp
Fixes #414.
As described in the linked issue, this changes the way kinematic bodies are moved. Previously they would be moved like any other body, using `JPH::BodyInterface::SetPositionAndRotation`, but this doesn't actually apply any linear/angular velocity to the kinematic body, resulting in there not being any real collision response between it and dynamic bodies.
This PR instead makes it so kinematic bodies are moved using `JPH::Body::MoveKinematic`, which will set the appropriate linear/angular velocity.
> Fixed issue with kinematic bodies not moving as they should

- src/joints/jolt_cone_twist_joint_impl_3d.cpp
- src/joints/jolt_cone_twist_joint_impl_3d.hpp
- src/joints/jolt_generic_6dof_joint_impl_3d.cpp
- src/joints/jolt_generic_6dof_joint_impl_3d.hpp
- src/joints/jolt_hinge_joint_impl_3d.cpp
- src/joints/jolt_hinge_joint_impl_3d.hpp
- src/joints/jolt_joint_impl_3d.cpp
- src/joints/jolt_joint_impl_3d.hpp
- src/joints/jolt_pin_joint_impl_3d.cpp
- src/joints/jolt_pin_joint_impl_3d.hpp
- src/joints/jolt_slider_joint_impl_3d.cpp
- src/joints/jolt_slider_joint_impl_3d.hpp
- src/servers/jolt_physics_server_3d.cpp
Related to #418.
In order to allow for joint limits outside of what Jolt allows for I've been shifting the reference frames of the two bodies connected to the joint. I had however been doing this in world-space using a reference frame that's cached when the joint is first created. This for some reason seemed fine to me at the time, but this obviously creates problem when you decide to change the limits after the whole setup has actually started moving around.
This PR changes all that to instead do the reference frame shifting in local-space. It also unifies the shifting to now happen in one place, which is the new `JoltJointImpl3D::shift_reference_frames` method.
> Fixed joint misalignment when changing limits after moving

- src/joints/jolt_generic_6dof_joint_impl_3d.cpp
- src/joints/jolt_hinge_joint_impl_3d.cpp
- src/joints/jolt_joint_impl_3d.cpp
- src/joints/jolt_slider_joint_impl_3d.cpp
Complements #424.
It looks like I not only got the "order of operations" wrong for the shifting of the joint reference frames, but also the hinge joint didn't shift the correct axis.
This fixes all that.
> Fixed mistakes in the reference frame shifting for joints

- src/joints/jolt_joint_impl_3d.cpp
Complements #424 and fixes #427.
When (for example) attaching a `RigidBody3D` to a scaled `StaticBody3D` by a joint, the `RigidBody3D` would become displaced from its starting position relative to the scale of the `StaticBody3D`.
This PR changes `JoltJointImpl3D::shift_reference_frames` to take the body's scales into account.
> Fixed issue with joints not accounting for scaled bodies

- src/joints/jolt_cone_twist_joint_impl_3d.cpp
- src/joints/jolt_cone_twist_joint_impl_3d.hpp
- src/joints/jolt_generic_6dof_joint_impl_3d.cpp
- src/joints/jolt_generic_6dof_joint_impl_3d.hpp
- src/joints/jolt_hinge_joint_impl_3d.cpp
- src/joints/jolt_hinge_joint_impl_3d.hpp
- src/joints/jolt_pin_joint_impl_3d.cpp
- src/joints/jolt_pin_joint_impl_3d.hpp
- src/joints/jolt_slider_joint_impl_3d.cpp
- src/joints/jolt_slider_joint_impl_3d.hpp
This was in part extracted from #430.
This is just bringing the joints in line with a convention I've already been applying to the object classes, where reactive changes typically involve a `*_changed` method being invoked after the relevant state changes, which in turn performs whatever subsequent state changes are needed, usually through one or more `update_*` methods.
> Refactored joints to apply changes in a more reactive way

- CHANGELOG.md
- src/objects/jolt_body_impl_3d.cpp
- src/objects/jolt_body_impl_3d.hpp
Fixes #432.
This fixes an issue where `AnimatableBody3D` would de-sync from its underlying body when moved.
Apparently `AnimatableBody3D` pretends to be a `StaticBody3D` but is in fact kinematic. On top of this it does some strange stuff where it deliberately sets the transform on the underlying physics body but then [immediately reverts it](https://github.com/godotengine/godot/blob/72b59325cf7beba7e6e9170cf6023a079fd58672/scene/3d/physics_body_3d.cpp#L358-L362), just for the physics server to sync it back and have it be set again. Since I had assumed that only dynamic bodies were the ones able to move on their own, and therefore the only type that needs to be synced, I had not been syncing kinematic bodies.
This PR fixes all this by simply allowing kinematic bodies to sync their state.
> Fixed issue with `AnimatableBody3D` not synchronizing its state

- src/misc/math.hpp
I've been getting some asserts from Jolt about non-normalized quaternions in certain scenes, and changing `Math::decompose` to include the orthogonalization part of the Gram-Schmidt orthonormalization seems to help with that.
> Added orthogonalization to `decompose`

- CHANGELOG.md
- src/objects/jolt_area_impl_3d.hpp
- src/objects/jolt_body_impl_3d.cpp
- src/objects/jolt_body_impl_3d.hpp
- src/objects/jolt_object_impl_3d.cpp
- src/objects/jolt_object_impl_3d.hpp
Related to #433.
This fixes an issue where if you moved a kinematic body in one step and then stopped moving it in the next step, the underlying Jolt body would maintain the previous velocity and just keep moving, causing de-sync.
This PR fixes this in part by refactoring when/how kinematic bodies are moved. This turned out to be slightly complicated though...
Until now we've been calling Jolt's `MoveKinematic` on every transform change, which is what sets the velocities for the body. However, this creates a problem since we need to reset these velocities at some point, but still be able use them when stepping the simulation, as well as be able to report them back to the engine when synchronizing state.
Let's say we decide to reset the velocities after each state synchronization. This …
> Fixed kinematic bodies not resetting velocities between steps

- src/objects/jolt_area_impl_3d.cpp
- src/objects/jolt_area_impl_3d.hpp
- src/objects/jolt_body_impl_3d.cpp
- src/objects/jolt_body_impl_3d.hpp
- src/objects/jolt_object_impl_3d.cpp
- src/objects/jolt_object_impl_3d.hpp
- src/spaces/jolt_space_3d.cpp
I figured since we've already gone through the trouble of getting the Jolt body in methods like `JoltSpace3D::call_queries`, `JoltSpace3D::pre_step` and `JoltSpace3D::post_step` we might as well pass them on to the functions they're calling as well, which might help with performance a tiny bit. If nothing else it looks a bit cleaner.
> Refactored away some unnecessary body accessors

- src/objects/jolt_body_impl_3d.cpp
- src/objects/jolt_body_impl_3d.hpp
Complements #434 and #436.
The above mentioned changes introduced a couple of minor regressions.
The first regression being that #434 didn't update `kinematic_transform` when changing modes, so when a body would freeze into kinematic mode it would move back to wherever it was last in kinematic mode, which in the case of the first freeze would typically be `(0, 0, 0)`.
The second regression being that #436 didn't set `sync_state` to `true` in the correct place for kinematic bodies, leading to kinematic movements happening in `_process` to snap back to wherever they were previously.
The first regression is fixed in this PR by updating the `kinematic_transform` whenever a change to kinematic mode happens.
The second regression is fixed in this PR by instead comparing the previous and current …
> Fixed some regressions with kinematic bodies

- src/objects/jolt_body_impl_3d.cpp
This prevents any force/torque/impulse from being applied to the underlying Jolt body whenever the body is in either kinematic or static mode.
As far as I can tell this was already a no-op, but this was firing off a bunch of asserts within Jolt in debug builds, so I figured it'd be best to be explicit about it.
> Disallowed force/torque on static and kinematic bodies

- src/objects/jolt_body_impl_3d.cpp
- src/objects/jolt_object_impl_3d.cpp
This is another regression with kinematic bodies, caused by #434, where the initial transform for kinematic bodies wasn't correct, because `kinematic_transform` wasn't being updated by transform changes that happened before the body entered the space.
> Fixed kinematic bodies not starting with correct transform

- src/spaces/jolt_debug_renderer_3d.cpp
This fixes a long-standing issue where `JoltDebugGeometry3D` would always use the lowest-detailed LOD for the various triangle meshes that it makes use of, like spheres, cylinders, etc.
> Fixed broken LOD levels in debug renderer

- CHANGELOG.md
- src/joints/jolt_generic_6dof_joint_impl_3d.cpp
- src/joints/jolt_hinge_joint_impl_3d.cpp
- src/joints/jolt_joint_impl_3d.cpp
- src/joints/jolt_slider_joint_impl_3d.cpp
Related to #418, #424 and #425.
This PR fixes a multitude of issues related to the shifting of reference frames for joints, which is done to accommodate for Godot's much more flexible joint limits.
> Fixed issues related to reference frame shifting for joints

- CHANGELOG.md
- src/objects/jolt_body_impl_3d.cpp
Related to #443.
This PR changes the "Lock Rotation" property on `RigidBody3D` to utilize infinite inertia, like Godot Physics does, instead of using the same 6DOF constraint that's used for axis-locking. This seems to completely eliminate the ability to "budge" the lock.
This trick doesn't seem applicable to axis-locks though, since they need to lock you in world-space whereas this inertia trick locks you in local-space.
> Changed rotation lock to utilize infinite inertia

- cmake/GodotJoltExternalJolt.cmake
Fixes #443.
This bumps Jolt from godot-jolt/jolt@8d3008e21baff6ce774b821adc73618bb3b891af to godot-jolt/jolt@b40883585c503a8eb7c9eb85fa923a964f8a314f (see diff [here](https://github.com/godot-jolt/jolt/compare/8d3008e21baff6ce774b821adc73618bb3b891af...b40883585c503a8eb7c9eb85fa923a964f8a314f)).
- Springs for 6DOF constraints
- Soft limits for hinge and 6DOF constraints
- Bugfix in friction approximation (needed for [#443](https://github.com/godot-jolt/godot-jolt/issues/443))
> Updated Jolt to b40883585c

- CHANGELOG.md
- docs/settings.md
- src/servers/jolt_project_settings.cpp
- src/servers/jolt_project_settings.hpp
- src/shapes/jolt_box_shape_impl_3d.cpp
- src/shapes/jolt_convex_polygon_shape_impl_3d.cpp
- src/shapes/jolt_cylinder_shape_impl_3d.cpp
This introduces a new project setting, `physics/jolt_3d/collisions/use_shape_margins`, which allows you to disable shape margins entirely, trading in performance for accuracy, thereby making things like collision normals on `BoxShape3D`, `CylinderShape3D` and `ConvexPolygonShape3D` more intuitive.
> Added project setting for disabling shape margins entirely

- CHANGELOG.md
- src/objects/jolt_body_impl_3d.cpp
- src/objects/jolt_body_impl_3d.hpp
Apparently Godot Physics allow kinematic bodies to have their `_integrate_forces` method invoked on every tick if it uses contact monitoring with a non-zero amount of contacts.
This PR brings Godot Jolt up-to-speed with that.
> Fixed kinematic bodies not being able to monitor contacts

- cmake/GodotJoltExternalJolt.cmake
This bumps Jolt from godot-jolt/jolt@b40883585c503a8eb7c9eb85fa923a964f8a314f to godot-jolt/jolt@31a4fb3d5bd82cb11f3db9775ed828083d454782 (see diff [here](https://github.com/godot-jolt/jolt/compare/b40883585c503a8eb7c9eb85fa923a964f8a314f...31a4fb3d5bd82cb11f3db9775ed828083d454782)).
- Ability to override mass and inertia from `JPH::ContactListener` (needed for [#400](https://github.com/godot-jolt/godot-jolt/issues/400))
> Updated Jolt to 31a4fb3d5b

- CHANGELOG.md
- README.md
- src/spaces/jolt_contact_listener_3d.cpp
- src/spaces/jolt_contact_listener_3d.hpp
Fixes #400.
This changes collision layers/masks to behave less like they did in Godot 3 and more like they do in Godot 4, where having an asymmetric layer/mask setup will result in the body whose mask does not contain the layer of the other body effectively having infinite inertia/mass in the context of that collision.
> Added collision response override for asymmetrical collisions

- cmake/GodotJoltExternalJolt.cmake
This bumps Jolt from godot-jolt/jolt@31a4fb3d5bd82cb11f3db9775ed828083d454782 to godot-jolt/jolt@c24af412ff419c567b30ff96f6f77d85e88f5876 (see diff [here](https://github.com/godot-jolt/jolt/compare/31a4fb3d5bd82cb11f3db9775ed828083d454782...c24af412ff419c567b30ff96f6f77d85e88f5876)).
- Sensors can now detect static bodies through body flag `SensorDetectsStatic` (needed for [#391](https://github.com/godot-jolt/godot-jolt/issues/391) and [#397](https://github.com/godot-jolt/godot-jolt/issues/397))
> Updated Jolt to c24af412ff

- cmake/GodotJoltExternalJolt.cmake
This bumps Jolt from godot-jolt/jolt@c24af412ff419c567b30ff96f6f77d85e88f5876 to godot-jolt/jolt@99bf29c110b6bda786f3252b3dc74b5ef66c4588 (see diff [here](https://github.com/godot-jolt/jolt/compare/c24af412ff419c567b30ff96f6f77d85e88f5876...99bf29c110b6bda786f3252b3dc74b5ef66c4588)).
- `JPH::HeightFieldShape` now registers collision functions for convex shapes (needed for [#391](https://github.com/godot-jolt/godot-jolt/issues/391) and [#397](https://github.com/godot-jolt/godot-jolt/issues/397))
> Updated Jolt to 99bf29c110

- CHANGELOG.md
- README.md
- docs/settings.md
- src/objects/jolt_area_impl_3d.cpp
- src/servers/jolt_project_settings.cpp
- src/servers/jolt_project_settings.hpp
- src/spaces/jolt_layer_mapper.cpp
Fixes #391.
Fixes #397.
This adds the project setting `physics/jolt_3d/collisions/areas_detect_static_bodies` to allow `Area3D` to detect overlaps with `StaticBody3D`, as well as bodies frozen with `FREEZE_MODE_STATIC`, with a potentially heavy performance/memory cost.
> Added support for areas detecting static bodies

- CHANGELOG.md
- src/objects/jolt_body_impl_3d.cpp
Complements #434.
This fixes an issue where things like `get_platform_velocity` on `CharacterBody3D` would always report a zero velocity.
`get_platform_velocity` relies on kinematic bodies having an up-to-date velocity when you call `move_and_slide`, which you'd normally do in `_physics_process`, since it fetches the kinematic body's velocity from the collision data. Until now I had been clearing the velocity right after the state synchronization (and `_integrate_forces`), which meant the velocities would be zeroed out during `_physics_process`. This changes the zeroing out to happen as part of `pre_step` instead.
> Fixed kinematic bodies reporting zero velocity in collisions

- CHANGELOG.md
- src/spaces/jolt_physics_direct_space_state_3d.cpp
This changes the `cast_motion` method in `PhysicsDirectSpaceState3D` to return `[1.0, 1.0]` when no collision was detected, to match Godot Physics.
> Changed `cast_motion` to return results even when no hit

- src/joints/jolt_cone_twist_joint_impl_3d.cpp
- src/joints/jolt_cone_twist_joint_impl_3d.hpp
- src/joints/jolt_generic_6dof_joint_impl_3d.cpp
- src/joints/jolt_generic_6dof_joint_impl_3d.hpp
- src/joints/jolt_hinge_joint_impl_3d.cpp
- src/joints/jolt_hinge_joint_impl_3d.hpp
- src/joints/jolt_pin_joint_impl_3d.cpp
- src/joints/jolt_pin_joint_impl_3d.hpp
- src/joints/jolt_slider_joint_impl_3d.cpp
- src/joints/jolt_slider_joint_impl_3d.hpp
- src/precompiled.hpp
Stems from #446.
This changes `SliderJoint3D` and `HingeJoint3D` to use `JPH::FixedConstraint` as the backing constraint when their lower and upper limits are the same. This helps silence some asserts from within Jolt, that can arise as the joints are being initialized, about how sliders/hinges with fixed limits are better suited as a `FixedConstraint`.
I also refactored the other joints to rebuild themselves in a similar manner, even if they only have one backing constraint, for the sake of consistency.
> Refactored joints to allow different backing constraints

- src/joints/jolt_hinge_joint_impl_3d.cpp
- src/joints/jolt_hinge_joint_impl_3d.hpp
- src/joints/jolt_slider_joint_impl_3d.cpp
- src/joints/jolt_slider_joint_impl_3d.hpp
Complements #469.
Since hinges (and sliders) now can have different backing constraints, always casting the underlying Jolt reference to `JPH::HingeConstraint` when changing the motor settings is obviously a bad idea.
This PR fixes all that.
> Fixed heap corruption when using motor with fixed hinge

- cmake/GodotJoltExternalJolt.cmake
- src/spaces/jolt_space_3d.cpp
This bumps Jolt from godot-jolt/jolt@99bf29c110b6bda786f3252b3dc74b5ef66c4588 to godot-jolt/jolt@a3d5318748fa234fff2340fbed110d0603a27ba9 (see diff [here](https://github.com/godot-jolt/jolt/compare/99bf29c110b6bda786f3252b3dc74b5ef66c4588...a3d5318748fa234fff2340fbed110d0603a27ba9)).
- Support for angular surface velocity (which allows for improving [#331](https://github.com/godot-jolt/godot-jolt/issues/331))
> Updated Jolt to a3d5318748

- CHANGELOG.md
- src/objects/jolt_body_impl_3d.cpp
This fixes a bug where if you had a body using `CENTER_OF_MASS_MODE_CUSTOM` and then switched over to `CENTER_OF_MASS_MODE_AUTO` (while it was connected to a scene tree) you wouldn't see any actual difference. This was because the shapes didn't get rebuilt, and since the center-of-mass override in Jolt is a decorator shape that meant the new center-of-mass never got applied until something else would trigger a shape rebuild.
> Fixed `center_of_mass_mode` not always applying properly

- CHANGELOG.md
- README.md
- src/joints/jolt_generic_6dof_joint_impl_3d.cpp
- src/joints/jolt_generic_6dof_joint_impl_3d.hpp
Pulled out of #430.
This adds support for all the spring-related properties in `Generic6DOFJoint3D`, which consist of the following:
- `G6DOF_JOINT_LINEAR_SPRING_STIFFNESS`
- `G6DOF_JOINT_LINEAR_SPRING_DAMPING`
- `G6DOF_JOINT_LINEAR_SPRING_EQUILIBRIUM_POINT`
- `G6DOF_JOINT_ANGULAR_SPRING_STIFFNESS`
- `G6DOF_JOINT_ANGULAR_SPRING_DAMPING`
- `G6DOF_JOINT_ANGULAR_SPRING_EQUILIBRIUM_POINT`
> Added support for springs in `Generic6DOFJoint3D`

- CHANGELOG.md
- cmake/GodotJoltExternalGodotCpp.cmake
- examples/project.godot
- godot-jolt.gdextension
- src/objects/jolt_body_impl_3d.cpp
- src/objects/jolt_body_impl_3d.hpp
- src/objects/jolt_object_impl_3d.cpp
- src/objects/jolt_physics_direct_body_state_3d.cpp
- src/objects/jolt_physics_direct_body_state_3d.hpp
- src/register_types.cpp
- src/servers/jolt_physics_server_3d.cpp
- src/servers/jolt_physics_server_3d.hpp
- src/spaces/jolt_contact_listener_3d.cpp
- src/spaces/jolt_contact_listener_3d.hpp
- src/spaces/jolt_physics_direct_space_state_3d.cpp
- src/spaces/jolt_physics_direct_space_state_3d.hpp
- src/spaces/jolt_query_filter_3d.cpp
- src/spaces/jolt_query_filter_3d.hpp
This bumps godot-cpp from godot-jolt/godot-cpp@78f709c74450d5dcfe1a3510dede8d5b67e42502 aka 4.0.3-stable to godot-jolt/godot-cpp@f5077b47711589c8fa6c3d4a907572c58fc6d9f6 aka 4.1-stable (see diff [here](https://github.com/godot-jolt/godot-cpp/compare/78f709c74450d5dcfe1a3510dede8d5b67e42502...f5077b47711589c8fa6c3d4a907572c58fc6d9f6)).
Fixes #270.
Fixes #336.
Fixes #337.
> Updated godot-cpp to 4.1

- cmake/GodotJoltExternalJolt.cmake
- src/objects/jolt_body_impl_3d.cpp
This bumps Jolt from godot-jolt/jolt@a3d5318748fa234fff2340fbed110d0603a27ba9 to godot-jolt/jolt@ea83565e6121a9d268932e403c0bf8ae5b688b90 (see diff [here](https://github.com/godot-jolt/jolt/compare/a3d5318748fa234fff2340fbed110d0603a27ba9...ea83565e6121a9d268932e403c0bf8ae5b688b90)).
- Ability to specify which DOFs a body has (needed for [#483](https://github.com/godot-jolt/godot-jolt/pull/483))
- Discarding slivers when building a mesh shape (needed for [#485](https://github.com/godot-jolt/godot-jolt/issues/485))
Fixes #485.
> Updated Jolt to ea83565e61

- CHANGELOG.md
- README.md
- src/objects/jolt_body_impl_3d.cpp
- src/objects/jolt_body_impl_3d.hpp
- src/shapes/jolt_custom_ray_shape.cpp
- src/shapes/jolt_custom_ray_shape.hpp
This replaces the current `JPH::SixDOFConstraint` implementation of the `axis_lock_*` and `lock_rotation` properties with the new `JPH::EAllowedDOFs`.
It also implements axis-locking for kinematic bodies.
> Replaced 6DOF axis-locking with proper one

- src/joints/jolt_cone_twist_joint_impl_3d.cpp
- src/joints/jolt_cone_twist_joint_impl_3d.hpp
- src/joints/jolt_generic_6dof_joint_impl_3d.cpp
- src/joints/jolt_generic_6dof_joint_impl_3d.hpp
- src/joints/jolt_hinge_joint_impl_3d.cpp
- src/joints/jolt_hinge_joint_impl_3d.hpp
- src/joints/jolt_joint_impl_3d.cpp
- src/joints/jolt_joint_impl_3d.hpp
- src/joints/jolt_pin_joint_impl_3d.cpp
- src/joints/jolt_pin_joint_impl_3d.hpp
- src/joints/jolt_slider_joint_impl_3d.cpp
- src/joints/jolt_slider_joint_impl_3d.hpp
- src/servers/jolt_physics_server_3d.cpp
This changes the way joints copy over some of the `JoltJointImpl3D` properties when changing type, like the `RID` and whether the bodies should have collisions with eachother disabled.
Previously this would be explicitly copied over in every `_joint_make_*` method, which was somewhat error-prone. Now instead the old joint reference gets passed into the respective joint constructor and the data gets copied in the `JoltJointImpl3D` constructor instead.
> Refactored the way joints are copied

- src/misc/bind_macros.hpp
- src/spaces/jolt_debug_geometry_3d.cpp
This makes some minor changes to the `BIND_PROPERTY*` macros that are used within `_bind_methods`.
- Added a `BIND_PROPERTY_HINTED` macro
- Changed `BIND_PROPERTY_ENUM` to instead use the new `BIND_PROPERTY_HINTED`
- Changed all `BIND_PROPERTY` macros to take a string name instead of an identifier
> Refactored property bind macros

- cmake/GodotJoltExternalGodotCpp.cmake
This bumps godot-cpp from godot-jolt/godot-cpp@f5077b47711589c8fa6c3d4a907572c58fc6d9f6 aka 4.1-stable to godot-jolt/godot-cpp@6478e0f9f778dd70c1364d6a1ffaf2d1a44a16a4 aka 4.1-stable (see diff [here](https://github.com/godot-jolt/godot-cpp/compare/f5077b47711589c8fa6c3d4a907572c58fc6d9f6...6478e0f9f778dd70c1364d6a1ffaf2d1a44a16a4)).
This disables the [automatic removal](https://github.com/godotengine/godot-cpp/blob/749b0b9ae03ecac470027b17c6414e7a0e730923/src/godot.cpp#L405) of editor plugins, which is currently causing a use-after-free and is not needed for the use-cases of this extension.
> Updated godot-cpp to 6478e0f9f7 (4.1)

- src/joints/jolt_cone_twist_joint_impl_3d.cpp
- src/joints/jolt_generic_6dof_joint_impl_3d.cpp
- src/joints/jolt_hinge_joint_impl_3d.cpp
- src/joints/jolt_joint_3d.cpp
- src/joints/jolt_joint_3d.hpp
- src/joints/jolt_joint_gizmo_plugin_3d.cpp
- src/joints/jolt_joint_gizmo_plugin_3d.hpp
- src/joints/jolt_joint_impl_3d.cpp
- src/joints/jolt_joint_impl_3d.hpp
- src/joints/jolt_pin_joint_3d.cpp
- src/joints/jolt_pin_joint_3d.hpp
- src/joints/jolt_pin_joint_impl_3d.cpp
- src/joints/jolt_pin_joint_impl_3d.hpp
- src/joints/jolt_slider_joint_impl_3d.cpp
- src/misc/bind_macros.hpp
- src/precompiled.hpp
- src/register_types.cpp
- src/servers/jolt_editor_plugin.cpp
- src/servers/jolt_editor_plugin.hpp
- src/servers/jolt_physics_server_3d.cpp
- src/servers/jolt_physics_server_3d.hpp
Fixes #346.
This adds a substitute node for `PinJoint3D`, called `JoltPinJoint3D`, that matches the `PinJoint3D` interface, while adding a couple of things on top, which are as follows:
- The ability to enable/disable the joint, using its `enabled` property
- The ability to fetch its last applied impulse, using its `get_linear_impulse` method
- The ability to override the solver velocity/position iterations for that specific joint
The first and second points together allow for creating breakable joints.
Note that this also introduces an editor plugin, which is responsible for setting the editor icons for these new joint nodes, as well as registering a new gizmo plugin, which draws the editor gizmos for them.
> Added `JoltPinJoint3D` along with editor/gizmo plugin

- src/joints/jolt_joint_3d.cpp
- src/joints/jolt_joint_3d.hpp
- src/joints/jolt_pin_joint_3d.cpp
Since `JoltPinJoint3D` is effectively a superset of `PinJoint3D`, I figured it might be useful to be able to still use `JoltPinJoint3D` when switching over to Godot Physics, just without the Jolt-specific functionality.
This PR does exactly that, by no-op'ing anything Jolt-specific when not using `JoltPhysicsServer3D`, like enabling/disabling the joint, or using `get_linear_impulse`.
Note that this is mostly meant to be a development feature, to do things like sanity check that the two implementations behave in a similar manner, so it will still emit an error about there not being a Jolt-based physics server available.
> Allowed `JoltPinJoint3D` to be used with Godot Physics

- CHANGELOG.md
- src/spaces/jolt_physics_direct_space_state_3d.cpp
- src/spaces/jolt_physics_direct_space_state_3d.hpp
> Fixed `body_test_motion` crashing when passing a null `result`

- CMakeLists.txt
- src/joints/jolt_joint_3d.cpp
- src/misc/bind_macros.hpp
- src/spaces/jolt_debug_geometry_3d.cpp
This changes the `BIND_METHOD` macro, aka `ClassDB::bind_method` to overload based on the number of arguments passed to it, which now allows for passing the names of the method's arguments, which means the arguments won't show up as `_unnamed_arg*` in the editor anymore, for things like `JoltDebugGeometry3D` and the custom joints.
> Added proper binding of method arguments

- src/misc/bind_macros.hpp
All this does is allow:
```cpp
BIND_PROPERTY("some_property", Variant::FLOAT, "suffix:m/s");
```
... as opposed to doing:
```cpp
BIND_PROPERTY_HINTED("some_property", Variant::FLOAT, PROPERTY_HINT_NONE, "suffix:m/s");
```
This of course allows for more than just suffixes, but that is its only relevance right now.
> Refactored bind macros to allow normal suffixed properties

- src/joints/jolt_hinge_joint_3d.cpp
- src/joints/jolt_hinge_joint_3d.hpp
- src/joints/jolt_hinge_joint_impl_3d.cpp
- src/joints/jolt_hinge_joint_impl_3d.hpp
- src/joints/jolt_joint_3d.cpp
- src/joints/jolt_joint_3d.hpp
- src/joints/jolt_joint_gizmo_plugin_3d.cpp
- src/register_types.cpp
- src/servers/jolt_physics_server_3d.cpp
- src/servers/jolt_physics_server_3d.hpp
Fixes #347.
This adds a substitute node for `HingeJoint3D`, called `JoltHingeJoint3D`, that mostly matches the `HingeJoint3D` interface, with the following differences:
- You can enable/disable the joint, using its `enabled` property
- You can fetch its last applied impulses, using its `get_linear_impulse` and `get_angular_impulse` methods
- You can override the solver velocity/position iterations for the joint
- You specify the motor limit in terms of max torque, and not max torque impulse, since an impulse is timestep-dependent
- You control the soft limits in terms of frequency/damping, and not bias/softness/restitution
The first and second point together allow for creating breakable joints.
There are also a couple of other Jolt-specific features that can/will be added to this later, …
> Added `JoltHingeJoint3D`

- src/joints/jolt_hinge_joint_3d.cpp
- src/joints/jolt_hinge_joint_3d.hpp
- src/joints/jolt_hinge_joint_impl_3d.cpp
- src/joints/jolt_hinge_joint_impl_3d.hpp
- src/joints/jolt_pin_joint_3d.cpp
- src/joints/jolt_pin_joint_3d.hpp
- src/joints/jolt_pin_joint_impl_3d.cpp
- src/joints/jolt_pin_joint_impl_3d.hpp
- src/servers/jolt_physics_server_3d.cpp
- src/servers/jolt_physics_server_3d.hpp
To better line up with the naming scheme Godot uses, I decided to rename the `get_linear_impulse` and `get_angular_impulse` methods found in the new substitute joints (`JoltPinJoint3D` and `JoltHingeJoint3D`) to instead be `get_impulse` and `get_torque_impulse` respectively.
> Renamed joint impulse methods

- CHANGELOG.md
- src/servers/jolt_physics_server_3d.cpp
This had apparently been left out by mistake.
> Implemented `body_is_omitting_force_integration`

- CHANGELOG.md
- src/joints/jolt_hinge_joint_3d.cpp
- src/joints/jolt_hinge_joint_3d.hpp
- src/joints/jolt_hinge_joint_impl_3d.cpp
- src/joints/jolt_hinge_joint_impl_3d.hpp
- src/joints/jolt_pin_joint_3d.cpp
- src/joints/jolt_pin_joint_3d.hpp
- src/joints/jolt_pin_joint_impl_3d.cpp
- src/joints/jolt_pin_joint_impl_3d.hpp
- src/servers/jolt_physics_server_3d.cpp
- src/servers/jolt_physics_server_3d.hpp
This changes the `get_impulse` and `get_torque_impulse` methods for `JoltPinJoint3D` and `JoltHingeJoint3D` to instead be called `get_applied_force` and `get_applied_torque` and to have the timestep integrated accordingly. They've also had their return types changed, from a `Vector3` to a `float`, instead representing the magnitude of the force/torque.
> Refactored joint impulse vectors to be magnitudes instead

- src/joints/jolt_pin_joint_3d.cpp
- src/joints/jolt_pin_joint_3d.hpp
Complements #510.
It seems I forgot to rename the actual `PinJoint3D` method `get_impulse` to `get_applied_force`, so this PR does just that.
> Renamed the `get_impulse` method in `PinJoint3D`

- src/joints/jolt_slider_joint_3d.cpp
- src/joints/jolt_slider_joint_3d.hpp
- src/joints/jolt_slider_joint_impl_3d.cpp
- src/joints/jolt_slider_joint_impl_3d.hpp
- src/register_types.cpp
- src/servers/jolt_physics_server_3d.cpp
- src/servers/jolt_physics_server_3d.hpp
Fixes #349.
This adds a substitute node for `SliderJoint3D`, called `JoltSliderJoint3D`, that mostly matches the `SliderJoint3D` interface, with the following differences:
- You can enable/disable the joint, using its `enabled` property
- You can fetch its last applied force/torque, using `get_applied_force()` and `get_applied_torque()`
- You can override the solver velocity/position iterations for the joint
- You control the soft limits in terms of frequency/damping, instead of softness/restitution/damping
- You can configure a motor
- You can _not_ rotate around the sliding axis
The first and second point together allow for creating breakable joints.
There are also a couple of other Jolt-specific features that can/will be added to this later, like max friction force and positional …
> Added `JoltSliderJoint3D`

- src/joints/jolt_cone_twist_joint_3d.cpp
- src/joints/jolt_cone_twist_joint_3d.hpp
- src/joints/jolt_cone_twist_joint_impl_3d.cpp
- src/joints/jolt_cone_twist_joint_impl_3d.hpp
- src/register_types.cpp
- src/servers/jolt_physics_server_3d.cpp
- src/servers/jolt_physics_server_3d.hpp
Fixes #348.
This adds a substitute node for `ConeTwistJoint3D`, called `JoltConeTwistJoint3D`, that mostly matches the `ConeTwistJoint3D` interface, with the following differences:
- You can enable/disable the joint, using its `enabled` property
- You can fetch its last applied force/torque, using `get_applied_force()` and `get_applied_torque()`
- You can override the solver velocity/position iterations for the joint
- You can configure a motor for all three axes
- You can _not_ configure any motion parameters, like bias, softness and relaxation
The first and second point together allow for creating breakable joints.
There are also a couple of other Jolt-specific features that can/will be added to this later, like max friction torque and positional motors with springs, but I'm mostly …
> Added `JoltConeTwistJoint3D`

- src/servers/jolt_physics_server_3d.cpp
Complements #518.
Apparently I had left out the actual bindings in `JoltPhysicsServer3D` for the stuff related to `JoltConeTwistJoint3D`, like the enum constants and the various server methods, so this PR fixes that.
> Added physics server bindings for `JoltConeTwistJoint3D`

- src/joints/jolt_generic_6dof_joint.cpp
- src/joints/jolt_generic_6dof_joint.hpp
- src/joints/jolt_generic_6dof_joint_impl_3d.cpp
- src/joints/jolt_generic_6dof_joint_impl_3d.hpp
- src/misc/bind_macros.hpp
- src/register_types.cpp
- src/servers/jolt_physics_server_3d.cpp
- src/servers/jolt_physics_server_3d.hpp
Fixes #350.
This adds a substitute node for `Generic6DOFJoint3D`, called `JoltGeneric6DOFJoint3D`, that mostly matches the `Generic6DOFJoint3D` interface, with the following differences:
- You can enable/disable the joint, using its `enabled` property
- You can fetch its last applied force/torque, using `get_applied_force()` and `get_applied_torque()`
- You can override the solver velocity/position iterations for the joint
- You configure soft limits using a limit spring, instead of softness, restitution, damping and ERP
- You configure springs using frequency/damping instead of stiffness/damping
- The "force limits" are referred to as "max force" and "max torque", for consistency across joints
The first and second point together allow for creating breakable joints.
There are also a …
> Added `JoltGeneric6DOFJoint3D`

- src/joints/jolt_joint_3d.cpp
When using one of the new substitute joints and altering the node structure of either of the two bodies it refers to, either by renaming or reparenting the bodies, you would sometimes end up with a warning on the joint node along the lines of "Node A must be of type PhysicsBody3D".
This turned out to be a result of the dirty check that was performed in `JoltJoint3D::set_node_a` and `JoltJoint3D::set_node_b`. For whatever reason these setters end up being called twice with the same node path when doing stuff like renaming a body, and only on the second call is the change actually committed and the node path valid.
This PR fixes this problem by simply removing the dirty check in `set_node_a` and `set_node_b`, allowing the joint to be rebuilt even if the node path is the same.
> Fixed joints emitting warnings when restructuring its bodies

- src/joints/jolt_joint_3d.cpp
When duplicating an instanced scene containing any of the new substitute joints, a ton of errors would be emitted saying stuff about `!is_inside_tree()` and how its referenced bodies were in different spaces.
This turned out to be because the joints were trying to set themselves up before actually being connected to the scene tree, which doesn't make a whole lot of sense.
This PR fixes this by incorporating `is_inside_tree()` in `JoltJoint3D::_validate`.
> Fixed errors when duplicating instanced scene containing joints

- cmake/GodotJoltExternalJolt.cmake
- src/spaces/jolt_debug_renderer_3d.cpp
- src/spaces/jolt_debug_renderer_3d.hpp
This bumps Jolt from godot-jolt/jolt@ea83565e6121a9d268932e403c0bf8ae5b688b90 to godot-jolt/jolt@8f5df4d52cf224f2c2fc99a5130625d9d250ec52 (see diff [here](https://github.com/godot-jolt/jolt/compare/ea83565e6121a9d268932e403c0bf8ae5b688b90...8f5df4d52cf224f2c2fc99a5130625d9d250ec52)).
- The ability to specify solver priority for constraints
- Optimizations
- Bug fixes
> Updated Jolt to 8f5df4d52c

- cmake/GodotJoltExternalGodotCpp.cmake
This bumps godot-cpp from godot-jolt/godot-cpp@6478e0f9f778dd70c1364d6a1ffaf2d1a44a16a4 aka 4.1-stable to godot-jolt/godot-cpp@a69c980bfbb4dcd851eb2cf29080a62c8428c735 aka 4.1.1-stable (see diff [here](https://github.com/godot-jolt/godot-cpp/compare/6478e0f9f778dd70c1364d6a1ffaf2d1a44a16a4...a69c980bfbb4dcd851eb2cf29080a62c8428c735)).
This also removes any aggressive floating-point optimizations (`-ffast-math` etc.) when building godot-cpp, to hopefully prevent any future issues similar to #536.
> Updated godot-cpp to 4.1.1

- CHANGELOG.md
- CMakeLists.txt
Fixes #536.
This removes any compiler flags that enable aggressive floating-point optimizations, meaning `-ffast-math` and `/fp:fast` for GCC/Clang and MSVC respectively.
This should hopefully eliminate any weird discrepancies between compilers that might appear as a result of these flags.
> Disabled aggressive floating-point optimizations

- cmake/GodotJoltExternalJolt.cmake
- src/shapes/jolt_custom_empty_shape.hpp
- src/shapes/jolt_custom_motion_shape.hpp
- src/shapes/jolt_custom_ray_shape.hpp
- src/shapes/jolt_custom_user_data_shape.hpp
- src/spaces/jolt_body_accessor_3d.cpp
- src/spaces/jolt_contact_listener_3d.cpp
This bumps Jolt from godot-jolt/jolt@8f5df4d52cf224f2c2fc99a5130625d9d250ec52 to godot-jolt/jolt@153291b7c6e294d727c707fd0734c038cc2fdce0 (see diff [here](https://github.com/godot-jolt/jolt/compare/8f5df4d52cf224f2c2fc99a5130625d9d250ec52...153291b7c6e294d727c707fd0734c038cc2fdce0)).
- Support for soft-body physics
- Support for non-power-of-two `JPH::HeightFieldShape`
> Updated Jolt to 153291b7c6

- cmake/GodotJoltExternalJolt.cmake
This bumps Jolt from godot-jolt/jolt@153291b7c6e294d727c707fd0734c038cc2fdce0 to godot-jolt/jolt@0dbba692a8eee68f306433283f38028c67616d0b (see diff [here](https://github.com/godot-jolt/jolt/compare/153291b7c6e294d727c707fd0734c038cc2fdce0...0dbba692a8eee68f306433283f38028c67616d0b)).
- Support for moving triangle data into `JPH::MeshShapeSettings`
> Updated Jolt to 0dbba692a8

- CHANGELOG.md
- README.md
- src/shapes/jolt_height_map_shape_impl_3d.cpp
- src/shapes/jolt_height_map_shape_impl_3d.hpp
Fixes #502.
This removes a couple of the restrictions on `HeightMapShape3D`, namely:
- We now allow for non-power-of-two dimensions, thanks to Jolt dealing with that internally.
- We now allow for non-square dimensions, by falling back to `JPH::MeshShape` in such cases.
- We now allow for an empty list of heights, which lines up better with `ConcavePolygonShape3D`.
- We now allow for fewer than 16 heights, by falling back to `JPH::MeshShape` in such cases.
> Removed restrictions on `HeightMapShape3D`

- cmake/GodotJoltExternalJolt.cmake
This bumps Jolt from godot-jolt/jolt@0dbba692a8eee68f306433283f38028c67616d0b to godot-jolt/jolt@12adfda9621f3f568b7c68a665d718fffa1d701c (see diff [here](https://github.com/godot-jolt/jolt/compare/0dbba692a8eee68f306433283f38028c67616d0b...12adfda9621f3f568b7c68a665d718fffa1d701c)).
- Support for changing the threshold angle for active edges
> Updated Jolt to 12adfda962

- src/shapes/jolt_concave_polygon_shape_impl_3d.cpp
- src/shapes/jolt_height_map_shape_impl_3d.cpp
Fixes #508.
Fixes #524.
This changes the active edge threshold from the default of 5 degrees to 50 degrees, meaning more triangle (and height map) edges will be considered inactive and thereby not cause any "ghost collisions".
> Changed the active edge threshold from 5 degrees to 50 degrees

- CHANGELOG.md
- src/spaces/jolt_physics_direct_space_state_3d.cpp
- src/spaces/jolt_physics_direct_space_state_3d.hpp
Fixes #529.
This introduces a minimum penetration depth for the contacts reported by `test_body_motion`, similar to how Godot Physics does it, which alleviates problems with `move_and_slide` where even after recovery you could end up still overlapping with the wall you're sliding against ever so slightly, which `floor_block_on_wall` would interpret as being trapped in a corner and would subsequently stop the character.
> Fixed issue with `move_and_slide` getting stuck while sliding

- CHANGELOG.md
- src/joints/jolt_generic_6dof_joint_impl_3d.cpp
- src/joints/jolt_hinge_joint_impl_3d.cpp
It appears that a not-so-innocent commit of mine (7495de47ad10f87f72b404df0018622a61ea89b5) that I thought was harmless, actually changed the direction by which motors rotated, causing a regression.
Instead of reverting it I've decided to simply flip the motor direction for hinge joints instead, which has the nice upside of now being consistent with the 6DOF joint's motor direction, which is also flipped.
> Fixed hinge motors rotating the wrong way

- src/spaces/jolt_physics_direct_space_state_3d.cpp
This is more of a theoretical problem than an actual one, but while rifling through `test_body_motion` I realized that we're actually skipping the cast phase entirely when using a zero motion vector. This makes sense for `cast_motion`, since it ignores any initial overlaps anyway, but it doesn't make as much sense for `test_body_motion` which doesn't ignore initial overlaps.
Granted, the recovery phase should almost always push you away far enough that you never get a collision in the cast phase with a zero motion vector, but since this is technically a discrepancy with how Godot Physics works I figured it's best to rectify that and plug any potential edge-cases that might be lurking here.
Note that this only applies when passing `false` to `recovery_as_collision`.
> Fixed kinematic collisions potentially reporting no collision

- src/spaces/jolt_physics_direct_space_state_3d.cpp
I wasn't too happy with the value for the minimum contact depth introduced in #559.
While `margin * 0.05` is how this is implemented in Godot Physics, I struggled to see the point in involving the margin in this calculation at all, so I decided to change it to instead be hardcoded to 0.0001, or 0.1 mm.
> Changed the minimum contact depth for kinematic collisions

- .github/workflows/analyze.yml
In the interest of shaving down the CI time I'm removing the x86 clang-tidy step.
Seeing as how I've yet to see a single discrepancy between the x86 and x64 clang-tidy runs in the 1000+ CI runs that have completed so far, I think it's safe to rely on just the x64 one going forward.
> Removed the 32-bit clang-tidy step from CI

- CHANGELOG.md
- docs/settings.md
- src/servers/jolt_project_settings.cpp
- src/servers/jolt_project_settings.hpp
- src/spaces/jolt_physics_direct_space_state_3d.cpp
Fixes #530.
This adds a new project setting to the "Kinematics" category called "Ignore Internal Edges", which defaults to being enabled, and will allow for disabling the overriding of collision normals that happens as part of Jolt's active/inactive edge detection, resulting in edge normals that look more like what they do with Godot Physics.
> Added "Ignore Internal Edges" project setting

- CHANGELOG.md
- src/shapes/jolt_height_map_shape_impl_3d.cpp
Fixes #566.
This changes the triangulation of `HeightMapShape3D` to match the one that Godot Physics uses.
> Fixed the triangulation of `HeightMapShape3D`

- cmake/GodotJoltExternalJolt.cmake
This bumps Jolt from godot-jolt/jolt@12adfda9621f3f568b7c68a665d718fffa1d701c to godot-jolt/jolt@5d382fc0f71411dacf0c1f6f93fe0d2612fed45e (see diff [here](https://github.com/godot-jolt/jolt/compare/12adfda9621f3f568b7c68a665d718fffa1d701c...5d382fc0f71411dacf0c1f6f93fe0d2612fed45e)).
- Bugfix in contact normal calculation in EPA algorithm
Fixes #536.
> Updated Jolt to 5d382fc0f7

- cmake/GodotJoltExternalJolt.cmake
This bumps Jolt from godot-jolt/jolt@5d382fc0f71411dacf0c1f6f93fe0d2612fed45e to godot-jolt/jolt@d558166ebdfa37269670a3dd3ac804c2e04462fe (see diff [here](https://github.com/godot-jolt/jolt/compare/5d382fc0f71411dacf0c1f6f93fe0d2612fed45e...d558166ebdfa37269670a3dd3ac804c2e04462fe)).
- Constraints check to see if inverse effective mass is zero to avoid producing NaNs
Fixes #558.
> Updated Jolt to d558166ebd

- cmake/GodotJoltExternalJolt.cmake
This bumps Jolt from godot-jolt/jolt@d558166ebdfa37269670a3dd3ac804c2e04462fe to godot-jolt/jolt@58445d6c2633d2f25df0aa54898bc4249b37f4e8 (see diff [here](https://github.com/godot-jolt/jolt/compare/d558166ebdfa37269670a3dd3ac804c2e04462fe...58445d6c2633d2f25df0aa54898bc4249b37f4e8)).
- Revert of jrouwe/JoltPhysics@5d382fc0f71411dacf0c1f6f93fe0d2612fed45e
> Updated Jolt to 58445d6c26

- .github/workflows/analyze.yml
- .github/workflows/build-linux.yml
- .github/workflows/build-macos.yml
- .github/workflows/build-windows.yml
- .github/workflows/package.yml
This bumps the `actions/checkout` action for all CI workflows from v3 to v4.
> Updated `actions/checkout` to v4

- cmake/GodotJoltExternalJolt.cmake
This bumps Jolt from godot-jolt/jolt@58445d6c2633d2f25df0aa54898bc4249b37f4e8 to godot-jolt/jolt@886e4e2b6e8e375491f36e10301f9a7025ceec4d (see diff [here](https://github.com/godot-jolt/jolt/compare/58445d6c2633d2f25df0aa54898bc4249b37f4e8...886e4e2b6e8e375491f36e10301f9a7025ceec4d)).
- Reduced tolerance for early out when contact normal equals surface normal in active edge detection
- Fixed flipped normals in EPA penetration depth algorithm
Fixes #536.
> Updated Jolt to 886e4e2b6e

- cmake/GodotJoltExternalJolt.cmake
This bumps Jolt from godot-jolt/jolt@886e4e2b6e8e375491f36e10301f9a7025ceec4d to godot-jolt/jolt@577c84920434b41995616acaf5714a2111ebb43d (see diff [here](https://github.com/godot-jolt/jolt/compare/886e4e2b6e8e375491f36e10301f9a7025ceec4d...577c84920434b41995616acaf5714a2111ebb43d)).
- Added `JobSystem::Job::GetName()`
> Updated Jolt to 577c849204

- CHANGELOG.md
- src/misc/math.hpp
- src/precompiled.hpp
- src/servers/jolt_physics_server_3d.cpp
- src/spaces/jolt_job_system.cpp
- src/spaces/jolt_job_system.hpp
Fixes #507.
This adds a number of timings to the "Physics 3D" category in the "Profiler" tab in Godot's debugger.
The timings reported are the time it took to execute the various jobs that Jolt schedules, which currently consist of things like:
- `DetermineActiveConstraints`
- `PostIntegrateVelocity`
- `PreIntegrateVelocity`
- `FinalizeIslands`
- `IntegrateVelocity`
- `SolveVelocityConstraints`
- `ApplyGravity`
- `BodySetIslandIndex`
- `UpdateBroadPhasePrepare`
- `UpdateBroadPhaseFinalize`
- `FindCollisions`
- `SolvePositionConstraints`
- `ContactRemovedCallbacks`
- `ResolveCCDContacts`
- `UpdateSoftBodies`
- `SetupVelocityConstraints`
- `BuildIslandsFromConstraints`
- `FindCollisions`
> Added profiler timings

- CHANGELOG.md
- src/objects/jolt_body_impl_3d.cpp
This changes `body_set_force_integration_callback` to behave like it does with Godot Physics, where the number of parameters in the callback has to line up with the number of arguments passed to `body_set_force_integration_callback`.
Until now the `_my_integration` method in this (somewhat forced) example would not have been called:
```gdscript
extends RigidBody3D
func _my_integration(state):
pass
func _ready():
PhysicsServer3D.body_set_force_integration_callback(self, _my_integration)
```
... because you always had to have a `userdata` parameter in the callback. Now instead you only add the `userdata` parameter to the callback if `userdata` is also provided to `body_set_force_integration_callback`, like so:
```gdscript
extends RigidBody3D
func _my_integration(state, userdata):
pass
func …
```
> Changed force integration callback to match Godot Physics

- CHANGELOG.md
- src/spaces/jolt_physics_direct_space_state_3d.cpp
- src/spaces/jolt_physics_direct_space_state_3d.hpp
Related to #530.
This omits the usage of `mActiveEdgeMovementDirection` from the collision check in `body_test_motion` (a.k.a. `move_and_collide`).
I've yet to see any clear benefit from using this, and a couple of edge-cases seem to indicate that it has more of a negative rather than positive impact on `move_and_collide`, so I'm removing it for the time being.
> Removed direction from edge detection during kinematic collisions

- CHANGELOG.md
- src/objects/jolt_area_impl_3d.hpp
Fixes #584.
This fixes an issue with `Area3D`, where if you had `monitoring` disabled and bodies already overlapping, it wouldn't report any enter events once `monitoring` was enabled.
> Fixed `Area3D` not catching enters when not monitoring

- src/spaces/jolt_debug_geometry_3d.cpp
- src/spaces/jolt_debug_geometry_3d.hpp
This makes it easier to see which edges are active and which ones are not.
> Added drawing of triangle outlines to `JoltDebugGeometry3D`

- CHANGELOG.md
- src/misc/utility_macros.hpp
- src/precompiled.hpp
- src/servers/jolt_physics_server_3d.cpp
- src/servers/jolt_physics_server_3d.hpp
This registers `JoltPhysicsServer3D` as an actual engine singleton, which allows for things like `JoltPhysicsServer3D.pin_joint_get_applied_force(my_joint)`, as opposed to having to do some kind of casting of the regular `PhysicsServer3D` (if that's even possible?) or using the even more questionable option of `PhysicsServer3D.call("pin_joint_get_applied_force", my_joint)`
> Added registering of `JoltPhysicsServer3D` as a singleton

- cmake/GodotJoltExternalJolt.cmake
This bumps Jolt from godot-jolt/jolt@577c84920434b41995616acaf5714a2111ebb43d to godot-jolt/jolt@dd1d4a670c1dd73f7ec8dbaa0cabf9162a31e159 (see diff [here](https://github.com/godot-jolt/jolt/compare/577c84920434b41995616acaf5714a2111ebb43d...dd1d4a670c1dd73f7ec8dbaa0cabf9162a31e159)).
- Added non-settings constructor to `OffsetCenterOfMassShape`
> Updated Jolt to dd1d4a670c

- CHANGELOG.md
- src/objects/jolt_body_impl_3d.cpp
Fixes #594.
This fixes an issue where if you changed the center-of-mass in any way (either explicitly or by adding another shape) while the body was attached to a joint, the joint wouldn't have its reference frames updated and would effectively shift the body relative to the joint.
> Fixed joints not updating on center-of-mass changes

- CHANGELOG.md
- src/spaces/jolt_contact_listener_3d.cpp
Fixes #582.
This changes how collision layers/masks work with `Area3D`, and is effectively the `Area3D` equivalent of #457.
Until now `Area3D` has behaved like bodies did prior to #457, meaning overlaps were detected if `(area_mask & object_layer) || (object_mask & area_layer)`, but with this PR you will instead only get a reported overlap if `area_mask & object_layer`.
Note that this opens up for another issue, which is that changing the collision mask of an `Area3D` while an affected body is overlapping it, or changing that overlapping body's collision layer, will not correctly report an exit like it does in Godot Physics. I'll try to figure out some solution for that later.
> Changed `Area3D` layers/masks to support asymmetrical setups

- src/servers/jolt_physics_server_3d.cpp
Some of the parameter names for the bound joint methods in `JoltPhysicsServer3D` were missing. This PR addresses that.
> Fixed parameter names for joint methods in `JoltPhysicsServer3D`

- src/servers/jolt_editor_plugin.cpp
- src/servers/jolt_editor_plugin.hpp
- src/servers/jolt_physics_server_3d.cpp
- src/servers/jolt_physics_server_3d.hpp
- src/spaces/jolt_space_3d.cpp
- src/spaces/jolt_space_3d.hpp
This changes the "Dump Snapshots" menu option (as well as accompanying server methods) to be referred to as "Dump Debug Snapshots" instead.
I figured this better communicates that it's not really a useful general-purpose feature, and more of a debugging/development feature. I suppose it also opens up for some hypothetical future `space_dump_snapshot` method that doesn't filter out the custom shapes, if such a thing would happen to be useful.
CC: @jrouwe
> Renamed "Dump Snapshots" to "Dump Debug Snapshots"

- CHANGELOG.md
- src/objects/jolt_body_impl_3d.cpp
This changes the behavior of any callback that's passed to the `body_set_force_integration_callback` method of `PhysicsServer3D`, where previously it would always be invoked every physics tick, whereas now it behaves like `_integrate_forces` does, where it's only invoked when synchronizing state, i.e. when the body has moved in some way.
> Changed custom integration to only be called on state sync

- src/objects/jolt_body_impl_3d.cpp
- src/objects/jolt_body_impl_3d.hpp
Fixes #602.
This changes the updating of gravity (which is typically retrieved through `PhysicsDirectBodyState3D.total_gravity`) from only happening as part of `_pre_step_rigid`, which only applied to dynamic bodies, to now also happen in `_pre_step_kinematic`, which lets kinematic bodies like `CharacterBody3D` also use it.
> Added support for total gravity for kinematic bodies

- src/objects/jolt_area_impl_3d.hpp
- src/spaces/jolt_contact_listener_3d.cpp
- src/spaces/jolt_contact_listener_3d.hpp
Related to #586.
As a result of #586 there's no longer any need to track whether areas should be listened for in the contact listener, since they always will be. This means we can remove the relevant early-out in `_try_add_area_overlap` and have `JoltAreaImpl3D::generates_contacts()` return `false` instead, saving us from having to store the areas every tick. 
I also stumbled upon a mistake in `_try_override_collision_response`, where the collision layers/masks were being looked up through the physics space, when it could just as well be retrieved from the bodies that were being passed in as parameters.
> Removed redundancy related to contact listener

- src/objects/jolt_area_impl_3d.cpp
- src/objects/jolt_area_impl_3d.hpp
- src/objects/jolt_body_impl_3d.cpp
- src/objects/jolt_body_impl_3d.hpp
- src/objects/jolt_group_filter.cpp
- src/spaces/jolt_contact_listener_3d.cpp
It seems that #605 largely (and mistakenly) undid the parts of #595 that were relevant (at the time) for #582, by regressing the behavior of collision/layers masks for `Area3D` in a way where they once again would report overlaps if another `Area3D` had the first area's layer in its mask.
This PR addresses that by to some degree undoing #605 by re-introducing filtering into `_flush_area_enters`.
Re-introducing filtering into `_flush_area_enters` means that #604 will also regress with regards to `Area3D` versus `Area3D`, so some other solution needs to be thought of there.
> Fixed broken asymmetric collisions between areas

- CHANGELOG.md
- src/spaces/jolt_contact_listener_3d.cpp
Fixes #582 (for real this time).
This changes the evaluation of area overlaps that happens in the contact listener to dismiss any contacts that aren't actually the result of overlapping shapes.
> Fixed issue with `Area3D` picking up speculative contacts

- cmake/GodotJoltExternalJolt.cmake
- src/shapes/jolt_custom_decorated_shape.hpp
- src/shapes/jolt_custom_empty_shape.hpp
- src/shapes/jolt_custom_motion_shape.hpp
- src/shapes/jolt_custom_ray_shape.hpp
This bumps Jolt from godot-jolt/jolt@dd1d4a670c1dd73f7ec8dbaa0cabf9162a31e159 to godot-jolt/jolt@15e41af13629b6b471d62ae11921c1a4f4aeeb03 (see diff [here](https://github.com/godot-jolt/jolt/compare/dd1d4a670c1dd73f7ec8dbaa0cabf9162a31e159...15e41af13629b6b471d62ae11921c1a4f4aeeb03)).
- Multi-threaded soft bodies
- Minor optimization to `JPH::Body::GetInverseInertia`
> Updated Jolt to godot-jolt/jolt@15e41af136

- CHANGELOG.md
- src/objects/jolt_body_impl_3d.cpp
Fixes #614.
This changes how the offset passed to the `apply_force` and `apply_impulse` methods of `RigidBody3D` and `PhysicsDirectBodyState3D` is interpreted.
Until now the offset has been interpreted as an offset relative to the body's center-of-mass, but [the documentation](https://docs.godotengine.org/en/stable/classes/class_rigidbody3d.html#class-rigidbody3d-method-apply-force) (and the behavior in Godot Physics) clearly indicate that the offset is relative to the body's origin, so this PR changes exactly that.
> Fixed non-central forces/impulses being applied incorrectly

- src/spaces/jolt_space_3d.cpp
EPhysicsUpdateError is a bitfield. Multiple errors can trigger in the same update.
> Fixed small bug in physics update error handling

- src/servers/jolt_physics_server_3d.cpp
- src/spaces/jolt_space_3d.cpp
This moves where the warning about this extension's inability to run on a separate thread is emitted.
Previously this was emitted in `PhysicsServer3DExtension::_init`, but this ends up being too early in the application flow, causing the warning to only ever be emitted to stdout and not the editor log.
Now instead it's emitted in the physics space constructor, which is late enough in the application flow for `EditorLog` to be initialized and registered as an error handler, leading to the warning being more prominent.
> Moved warning about separate thread not being supported

- CHANGELOG.md
- src/shapes/jolt_convex_polygon_shape_impl_3d.cpp
This changes the implementation for `ConvexPolygonShape3D` to allow for 0 points without emitting any errors about failing to build the shape.
This brings `ConvexPolygonShape3D` in line with `ConcavePolygonShape3D` and `HeightMapShape3D`.
> Changed `ConvexPolygonShape3D` to allow for 0 points

- cmake/GodotJoltExternalJolt.cmake
This bumps Jolt from godot-jolt/jolt@15e41af13629b6b471d62ae11921c1a4f4aeeb03 to godot-jolt/jolt@9d63f5a2d1b9e426a54dce6c8979e22ff6004eba (see diff [here](https://github.com/godot-jolt/jolt/compare/15e41af13629b6b471d62ae11921c1a4f4aeeb03...9d63f5a2d1b9e426a54dce6c8979e22ff6004eba)).
- Bugfix for `JPH::RotatedTranslatedShape::GetPosition`
- Optimizations for the "indexification" in `JPH::MeshShape`
Fixes #621.
> Updated Jolt to 9d63f5a2d1

- cmake/GodotJoltExternalJolt.cmake
This bumps Jolt from godot-jolt/jolt@9d63f5a2d1b9e426a54dce6c8979e22ff6004eba to godot-jolt/jolt@7df682edda5dee5f0445ceba27513f9e623dd758 (see diff [here](https://github.com/godot-jolt/jolt/compare/9d63f5a2d1b9e426a54dce6c8979e22ff6004eba...7df682edda5dee5f0445ceba27513f9e623dd758)).
- Setting frequency/stiffness to 0 for springs will now effectively disable them rather than lock them up.
> Updated Jolt to 7df682edda

- CHANGELOG.md
- docs/settings.md
- src/servers/jolt_project_settings.cpp
- src/servers/jolt_project_settings.hpp
- src/shapes/jolt_concave_polygon_shape_impl_3d.cpp
- src/shapes/jolt_height_map_shape_impl_3d.cpp
Fixes #634.
This adds a new project setting called "Active Edge Threshold" that determines the cut-off angle for Jolt's active edge detection, which is what helps prevent collisions with triangle edges.
This has until now been hardcoded at 50 degrees (per #546) but with different projects having different tolerances to the trade-offs involved in changing this I will go ahead and make it configurable through a project setting instead.
> Added project setting for the active edge threshold

- src/servers/jolt_editor_plugin.cpp
It appears that the theming API had a breaking change in 4.2 that causes `get_editor_interface()->get_base_control()->get_theme()` to return null. You're now instead meant to do `get_editor_interface()->get_editor_theme()`, but since this new API isn't available in the 4.1 bindings that we're using we're forced to instead just skip adding the icons for the substitute joint nodes.
Fixes #600.
Fixes #619.
Fixes #627.
Fixes #629.
> Fixed crash in editor plugin when running with Godot 4.2

- cmake/GodotJoltExternalGodotCpp.cmake
- src/joints/jolt_generic_6dof_joint.hpp
- src/servers/jolt_physics_server_3d.hpp
- src/spaces/jolt_debug_geometry_3d.hpp
This bumps godot-cpp from godot-jolt/godot-cpp@a69c980bfbb4dcd851eb2cf29080a62c8428c735 aka 4.1.1-stable to godot-jolt/godot-cpp@de9291384f6885eea67ef640864edf07b06f0ffe aka 4.1.2-stable (see diff [here](https://github.com/godot-jolt/godot-cpp/compare/a69c980bfbb4dcd851eb2cf29080a62c8428c735...de9291384f6885eea67ef640864edf07b06f0ffe)).
> Updated godot-cpp to 4.1.2

- src/servers/jolt_physics_server_3d.cpp
Fixes #645.
This changes `JoltPhysicsServer3D::_body_get_direct_state` to no longer emit an error if you pass it an invalid RID, as `move_and_slide` expects this method to be able to return null without error in such cases, as seen [here](https://github.com/godotengine/godot/blob/a574c0296b38d5f786f249b12e6251e562c528cc/scene/3d/physics_body_3d.cpp#L1191-L1199).
> Fixed null error after freeing a `move_and_slide` platform

- src/spaces/jolt_contact_listener_3d.cpp
- src/spaces/jolt_contact_listener_3d.hpp
Fixes #649.
This changes how the "Visible Collision Shapes" debug rendering behaves when you have overlaps between an `Area3D` and a `RigidBody3D`, `CharacterBody3D` or `StaticBody3D`.
Previously it would add any and all contact points as generated by Jolt as a debug contact, including those generated by `Area3D`, but now instead it will omit all contacts whenever either of the two bodies is an `Area3D`, to better match how the debug rendering behaves in Godot Physics.
> Removed adding of debug contacts for area/sensor overlaps

- cmake/GodotJoltExternalJolt.cmake
Related to #353 and #354.
This bumps Jolt from godot-jolt/jolt@7df682edda5dee5f0445ceba27513f9e623dd758 to godot-jolt/jolt@912bdbafb9fa8b155c99a510a270a18e9bb7d494 (see diff [here](https://github.com/godot-jolt/jolt/compare/7df682edda5dee5f0445ceba27513f9e623dd758...912bdbafb9fa8b155c99a510a270a18e9bb7d494)).
- Added support for Android ARM32/x86 architectures
- Added support for iOS versions older than iOS 13
- Added support for macOS versions older than macOS 10.15 (Catalina)
- Fixed warnings produced with Android NDK 26.1.10909125
> Updated Jolt to 912bdbafb9

- .github/workflows/package.yml
- scripts/ci_sign_macos.ps1
This reverts #665.
I realized that the certificate used to sign macOS builds are specifically meant for macOS binaries distributed outside of the App Store, and as such is likely just nonsense in the context of an iOS framework. With that in mind, I decided to just remove the signing for iOS altogether.
While I might be able to sign with an "Apple Distribution" certificate, there's really no point in going through the hassle of managing a separate certificate for something that will be overwritten as soon as the consumer of the framework deploys their app.
> Removed iOS code-signing

- cmake/GodotJoltExternalJolt.cmake
This bumps Jolt from godot-jolt/jolt@912bdbafb9fa8b155c99a510a270a18e9bb7d494 to godot-jolt/jolt@d8e0fec253f3e3f32c1accbe58427cd47a93cd40 (see diff [here](https://github.com/godot-jolt/jolt/compare/912bdbafb9fa8b155c99a510a270a18e9bb7d494...d8e0fec253f3e3f32c1accbe58427cd47a93cd40)).
- Enabled optimizations for the Distribution config on Android
> Updated Jolt to d8e0fec253

- CHANGELOG.md
- src/objects/jolt_area_impl_3d.cpp
This fixes an issue where if you'd set the `gravity_point_unit_distance` of an `Area3D` to zero, it would always result in that `Area3D` contributing a zero gravity vector. Now instead it will result in a constant gravity (as specified by the `gravity` property) pointing towards the center of the area, which is how Godot Physics behaves as well.
> Fixed issue with point gravity being zero when distance is zero

- cmake/GodotJoltExternalJolt.cmake
This bumps Jolt from godot-jolt/jolt@d8e0fec253f3e3f32c1accbe58427cd47a93cd40 to godot-jolt/jolt@a1a68107c15c83d8e47987b680dfaba34acc4a8d (see diff [here](https://github.com/godot-jolt/jolt/compare/d8e0fec253f3e3f32c1accbe58427cd47a93cd40...a1a68107c15c83d8e47987b680dfaba34acc4a8d)).
- Adds the `OVERRIDE_CXX_FLAGS` CMake option to allow Android to use largely the same CMake code path as other Unix-based platforms
> Updated Jolt to a1a68107c1

- CHANGELOG.md
- cmake/GodotJoltExternalJolt.cmake
This bumps Jolt from godot-jolt/jolt@a1a68107c15c83d8e47987b680dfaba34acc4a8d to godot-jolt/jolt@1fef92352095d501675e8514c4c7a7400c6d370c (see diff [here](https://github.com/godot-jolt/jolt/compare/a1a68107c15c83d8e47987b680dfaba34acc4a8d...1fef92352095d501675e8514c4c7a7400c6d370c)).
- Fixed mass scaling not applied for CCD objects & during solve position constraints
> Updated Jolt to 1fef923520

- CHANGELOG.md
- src/objects/jolt_body_impl_3d.cpp
This fixes an issue where if you provided a callback to the `body_set_force_integration_callback` method of `PhysicsServer3D` for a body that was explicitly created through the physics server then it could still sometimes get called while the body is sleeping.
> Fixed custom integration callback being called while sleeping

- cmake/GodotJoltExternalJolt.cmake
This bumps Jolt from godot-jolt/jolt@1fef92352095d501675e8514c4c7a7400c6d370c to godot-jolt/jolt@4ff703d11506290383fc82e926f1eaad728f0e01 (see diff [here](https://github.com/godot-jolt/jolt/compare/1fef92352095d501675e8514c4c7a7400c6d370c...4ff703d11506290383fc82e926f1eaad728f0e01)).
- Reduced memory usage for contact points
> Updated Jolt to 4ff703d115

- cmake/GodotJoltSetup.cmake
When running the configure step for any of the Android configurations on Windows while in any of the Visual Studio command prompts, you would be met with an error saying "Mismatched target architectures".
This isn't meant to happen when cross-compiling for Android, since the Visual Studio toolchain isn't used at all in that case, so it shouldn't really matter which command prompt you're building from.
This PR fixes that by making the error exclusive to `MSVC` targets.
> Fixed error when building for Android from Visual Studio prompt

- cmake/GodotJoltExternalGodotCpp.cmake
This bumps godot-cpp from godot-jolt/godot-cpp@de9291384f6885eea67ef640864edf07b06f0ffe aka 4.1.2-stable to godot-jolt/godot-cpp@2b277cbf1be5f42959268011b29a9947a17e2282 aka 4.1.3-stable (see diff [here](https://github.com/godot-jolt/godot-cpp/compare/de9291384f6885eea67ef640864edf07b06f0ffe...2b277cbf1be5f42959268011b29a9947a17e2282)).
> Updated godot-cpp to 4.1.3

- CHANGELOG.md
- src/servers/jolt_physics_server_3d.cpp
- src/spaces/jolt_job_system.cpp
- src/spaces/jolt_job_system.hpp
Fixes #554.
Fixes #684.
This fixes an issue where if you had many active physics spaces you would eventually end up in a deadlock/freeze, due to the job system running out of available jobs.
The solution was simply to reclaim any pending jobs after stepping every physics space, rather than after having stepped all of them.
> Fixed deadlock when having multiple active physics spaces

- src/objects/jolt_body_impl_3d.cpp
- src/objects/jolt_object_impl_3d.cpp
Does what it says on the tin.
Until now, when trying to do things like applying forces/impulses to a body outside of a physics space, you've been met with the somewhat cryptic error `Parameter "space" is null`.
Now instead you'll get an actual explanation of what the problem is and what object is affected.
> Improved error messages for methods requiring a physics space

- CHANGELOG.md
- src/shapes/jolt_height_map_shape_impl_3d.cpp
- src/shapes/jolt_height_map_shape_impl_3d.hpp
As discussed in #688.
This changes `HeightMapShape3D` to unconditionally use the same double-sided decorator shape that `ConcavePolygonShape3D` uses when its `backface_collision` property is set, which lines up with how Godot Physics behaves.
> Changed `HeightMapShape3D` to be double-sided

- CHANGELOG.md
- src/objects/jolt_body_impl_3d.cpp
Fixes #693.
This fixes a discrepancy with Godot Physics where after a body has moved between physics spaces (like when reparenting) it would until now not clear its `sync_state` flag and thereby invoke the state synchronization callback, which would lead to the physics server effectively overwriting any pending `NOTIFICATION_TRANSFORM_CHANGED`, like the one pending as a result of the local transform having been set by its new parent.
> Fixed global transform not being preserved when reparenting

- src/objects/jolt_body_impl_3d.cpp
This isn't an actual problem that I've run into yet, but it struck me as potentially problematic.
When changing spaces of a kinematic body the kinematic transform wouldn't be updated, so if the body ended up having a different global transform in its new space then that would likely be interpreted as a movement and thus (erroneously) change the body's velocity for that tick.
This adds a reset of the kinematic transform when entering a new space.
> Fixed potentially stale kinematic transform when changing spaces

- CHANGELOG.md
- src/objects/jolt_area_impl_3d.cpp
- src/objects/jolt_area_impl_3d.hpp
- src/objects/jolt_body_impl_3d.cpp
- src/objects/jolt_body_impl_3d.hpp
- src/objects/jolt_object_impl_3d.cpp
- src/objects/jolt_object_impl_3d.hpp
Fixes #491.
This changes methods like `get_velocity_at_local_position`, `get_rest_info`, `body_test_motion`, `move_and_collide` and `move_and_slide` to correctly incorporate surface velocities in their reported velocities for bodies that use surface velocities.
> Fixed surface velocities not being added to point velocity

- CMakeLists.txt
- cmake/GodotJoltPrelude.cmake
- cmake/GodotJoltVersionInfo.cmake
This moves the `/Version.cmake` file introduced in #699 to `/cmake/GodotJoltVersionInfo.cmake`.
> Moved version info to a CMake module

- cmake/GodotJoltExternalJolt.cmake
This bumps Jolt from godot-jolt/jolt@4ff703d11506290383fc82e926f1eaad728f0e01 to godot-jolt/jolt@1939b954913ba77a61cb1c651cb0028456d748f6 (see diff [here](https://github.com/godot-jolt/jolt/compare/4ff703d11506290383fc82e926f1eaad728f0e01...1939b954913ba77a61cb1c651cb0028456d748f6)).
- Added `JPH::BodyInterface::SetUseManifoldReduction`
> Updated Jolt to 1939b95491

- src/objects/jolt_body_impl_3d.cpp
This fixes an issue, which is technically only relevant since #705, where if you enabled contact reporting (by changing `max_contacts_reported` to be non-zero) while you were mid-contact with some other body, you wouldn't receive reports of all the shape indices as expected.
> Fixed `max_contacts_reported` not invalidating contacts

- cmake/GodotJoltExternalJolt.cmake
- src/joints/jolt_joint_impl_3d.cpp
- src/spaces/jolt_space_3d.cpp
This bumps Jolt from godot-jolt/jolt@1939b954913ba77a61cb1c651cb0028456d748f6 to godot-jolt/jolt@8d1f587da49809bafe6eba54cd89301a8a820e95 (see diff [here](https://github.com/godot-jolt/jolt/compare/1939b954913ba77a61cb1c651cb0028456d748f6...8d1f587da49809bafe6eba54cd89301a8a820e95)).
- Changes the solver iteration overrides for joints to allow for values lower than the default/global values.
- Allows for asymmetrical limits for `JPH::SixDOFConstraint`.
- Allows for pyramidal limits for `JPH::SixDOFConstraint` and `JPH::SwingTwistConstraint`.
- Bugfix to indexification that happens when creating `JPH::MeshShape`.
> Updated Jolt to 8d1f587da4

- CHANGELOG.md
- src/joints/jolt_cone_twist_joint_impl_3d.cpp
- src/joints/jolt_generic_6dof_joint_impl_3d.cpp
Related to jrouwe/JoltPhysics#777.
This changes `Generic6DOFJoint3D` and `ConeTwistJointImpl3D` to use `JPH::ESwingType::Pyramid` for the new "swing type" that was introduced to Jolt recently. This effectively changes the shape of the angular limits to that of a pyramid, as opposed to the default cone shape.
This better matches how Godot Physics behaves, as well as how Bullet behaved in Godot 3.
> Changed 6DOF and cone-twist joint to use pyramid limits

- cmake/GodotJoltExternalJolt.cmake
This bumps Jolt from godot-jolt/jolt@8d1f587da49809bafe6eba54cd89301a8a820e95 to godot-jolt/jolt@38e6435777e4cd81f8598b777e6c4961656cffec (see diff [here](https://github.com/godot-jolt/jolt/compare/8d1f587da49809bafe6eba54cd89301a8a820e95...38e6435777e4cd81f8598b777e6c4961656cffec)).
- Allows `SixDOFConstraintSettings::SetLimitedAxis` to accept identical min/max limits.
> Updated Jolt to 38e6435777

- CHANGELOG.md
- src/joints/jolt_generic_6dof_joint_impl_3d.cpp
This removes the shifting of reference frames that was previously being done, where the reference frame of node A would be shifted in order to center the limits at 0, as this ended up causing a number of issues.
It would result in issues like having weird "limit shapes" when you incorporated both linear and angular limits, as well as problems with things like the "Equilibrium Point" properties, as the equilibrium points would erroneously be moved whenever you used asymmetrical limits.
Now instead the above mentioned centering is handled by Jolt internally, thanks to some recent changes, and we can instead throw pretty much any limits we want at the joint.
> Removed manual shifting of reference frames for 6DOF joints

- CHANGELOG.md
- src/joints/jolt_generic_6dof_joint_impl_3d.cpp
It turned out that as a result of the discrepancy between Bullet (in Godot 3) and Godot Physics when it comes to single-body joints, as described in #725, and me having used Bullet as a reference when implementing the equilibrium point, I had mistook the direction in which the equilibrium point is meant to go.
This PR inverts the direction to correct for this.
> Inverted direction of 6DOF equilibrium point

- CHANGELOG.md
- src/joints/jolt_joint_gizmo_plugin_3d.cpp
This changes the linear limits visualization for the editor gizmos of `JoltSliderJoint3D` as well as `JoltGeneric6DOFJoint3D` to be mirrored compared to what they were previously, so that the lower and upper limits swap places.
Until now the visualization of the linear limits has deliberately been inverted, where linear limits of something like [0, 5] would show a range of movement in the negative of that axis. This was to match how the corresponding gizmo would behave in both Godot 3 and Godot 4.
However, given that `node_a` dictates the space for the linear limits, it would stand to argue that if `node_a` is made static and `node_b` is not, then the visualized range-of-motion should correspond with how `node_b` is able to move, which has not been the case until now.
Besides getting rid …
> Mirrored linear limits gizmo for applicable joints

- CHANGELOG.md
- src/joints/jolt_generic_6dof_joint_impl_3d.cpp
- src/joints/jolt_joint_impl_3d.cpp
This changes the rotation order for all places within the joints where euler angles are converted into matrices/quaternions, from the default YXZ to XYZ, to match the rotation order that Jolt (as well as Bullet and Godot Physics) uses internally for the 6DOF joint.
While this technically affects `JoltJointImpl3D::_shift_reference_frames`, this change has no real impact there, since the 6DOF joints no longer rely on shifting the reference frames, as of #724. The only real change, which is technically a breaking one, is with the 6DOF spring equilibrium.
> Fixed rotation order of euler angles within joints

- src/joints/jolt_generic_6dof_joint_impl_3d.cpp
- src/joints/jolt_joint_impl_3d.cpp
Complements #728.
This changes the `EulerOrder` that's passed into any usage of `Basis::set_euler` with in the joints from XYZ to ZYX.
As it turns out, the `EulerOrder` you pass into Godot's `Basis::set_euler` is not in fact the order of rotations, but the order of the matrix multiplications, so to get an XYZ rotation order you must pass in `EULER_ORDER_ZYX`.
> Fixed rotation order of euler angles within joints for real

- CHANGELOG.md
- src/shapes/jolt_shape_instance_3d.cpp
Hopefully fixes #722.
This changes the move assignment operator in `JoltShapeInstance3D` to correctly hand off the old values to the temporary in order for the temporary to correctly decrement the reference counter for the actual `JoltShapeImpl3D`.
While I haven't been able to confirm this, this was most likely the cause for the crash, as you could otherwise potentially end up with "leaks" in the reference counting that would cause a crash once the shape was destroyed.
> Fixed move assignment operator in `JoltShapeInstance3D`

- CHANGELOG.md
- src/precompiled.hpp
- src/shapes/jolt_height_map_shape_impl_3d.cpp
Fixes #688.
Complements #691.
This changes a number of things related to `HeightMapShape3D`:
1. Non-square height maps had been left out of [#691](https://github.com/godot-jolt/godot-jolt/pull/691) and thus weren't using back-face collision, which is now fixed.
2. Non-square height maps (and technically 3x3 height maps) didn't support holes, which they now do.
3. Holes can now be specified using NaN instead of `FLT_MAX`, to line up with the undocumented support for holes in Godot.
> Added proper support for holes to `HeightMapShape3D`

- cmake/GodotJoltExternalGodotCpp.cmake
This bumps godot-cpp from godot-jolt/godot-cpp@c0dd7eeada027006d4ebed62a44ac9378d4147d3 aka 4.2-stable to godot-jolt/godot-cpp@43d02f2d7c0a051d7134904168ce92615d11713e aka 4.2-stable (see diff [here](https://github.com/godot-jolt/godot-cpp/compare/c0dd7eeada027006d4ebed62a44ac9378d4147d3...43d02f2d7c0a051d7134904168ce92615d11713e)).
Fixes #735.
> Updated godot-cpp to 43d02f2d7c (4.2-stable)

- CHANGELOG.md
- cmake/GodotJoltExternalJolt.cmake
- src/objects/jolt_area_impl_3d.cpp
- src/spaces/jolt_contact_listener_3d.cpp
This bumps Jolt from godot-jolt/jolt@38e6435777e4cd81f8598b777e6c4961656cffec to godot-jolt/jolt@3755a33ffd279a3d926a6d71ae077b4faa1c1f12 (see diff [here](https://github.com/godot-jolt/jolt/compare/38e6435777e4cd81f8598b777e6c4961656cffec...3755a33ffd279a3d926a6d71ae077b4faa1c1f12)).
- Fixes issue with sensors utilizing speculative contact distance
- Fixes issue with hinge constraints enforcing the wrong limit
- Fixes NaN propagation when bodies with locked axes collide with static bodies
- Replaces `mSensorDetectsStatic` flag in favor of `mCollideKinematicVsNonDynamic`
Fixes #733.
Fixes #734.
> Updated Jolt to 36869b03a0

- CHANGELOG.md
- docs/settings.md
- src/objects/jolt_body_impl_3d.cpp
- src/objects/jolt_body_impl_3d.hpp
- src/servers/jolt_project_settings.cpp
- src/servers/jolt_project_settings.hpp
Fixes #682.
This adds a new project setting called "Report All Kinematic Contacts", which will allow for contacts to be reported in collisions between kinematic bodies and other kinematic/static bodies, as opposed to only between kinematic and dynamic bodies, much like how things work in Godot Physics.
Given that this uses the same solution as "Areas Detect Static Bodies" it also comes with the exact same performance warning with regards to overlapping with complex static geometry.
> Added support for kinematic vs kinematic/static contact reporting

- cmake/GodotJoltExternalJolt.cmake
This bumps Jolt from godot-jolt/jolt@36869b03a0f0f542ab56575265a33dda9706fa8d to godot-jolt/jolt@36d1418f5c2fa7bc4851793cd28354224b64f36f (see diff [here](https://github.com/godot-jolt/jolt/compare/36869b03a0f0f542ab56575265a33dda9706fa8d...36d1418f5c2fa7bc4851793cd28354224b64f36f)).
- Fixes broken 32-bit Linux builds by adding the `-mfpmath=sse` flag
> Updated Jolt to 36d1418f5c

- cmake/GodotJoltExternalJolt.cmake
This bumps Jolt from godot-jolt/jolt@36d1418f5c2fa7bc4851793cd28354224b64f36f to godot-jolt/jolt@4a74ff08e4c4f1e6cd6020b4f929ffca517d088b (see diff [here](https://github.com/godot-jolt/jolt/compare/36d1418f5c2fa7bc4851793cd28354224b64f36f...4a74ff08e4c4f1e6cd6020b4f929ffca517d088b)).
- `SetLinearVelocity` now locks/clears any non-allowed DOFs
> Updated Jolt to 4a74ff08e4

- src/objects/jolt_body_impl_3d.cpp
- src/objects/jolt_body_impl_3d.hpp
As talked about in #734, Jolt assumes that the user will not apply forces/impulses/velocities on any currently locked axes, so this PR makes sure to explicitly clear those to avoid any problems with that.
> Added clearing of locked axes when changing velocities/forces

- CHANGELOG.md
- CMakeLists.txt
- cmake/templates/info_ios.plist.in
- cmake/templates/info_macos.plist.in
Supersedes #710.
This adds a new `Info.plist` template specific to iOS, which adds the missing `MinimumOSVersion` key, allowing one to actually create release builds when this extension is bundled.
I also threw in the `DTPlatformName` key on both macOS and iOS, which seems to be something that Godot adds for its [automatically generated](https://github.com/godotengine/godot/blob/d5ad37afcd44f4ba953e3473b5ab3afb18068134/platform/ios/export/export_plugin.cpp#L1180-L1203) `Info.plist` in the case where an extension only provides a `.dylib` file.
> Added separate `Info.plist` for iOS

- src/precompiled.hpp
- src/shapes/jolt_height_map_shape_impl_3d.cpp
- src/spaces/jolt_physics_direct_space_state_3d.cpp
This replaces the `std::isnan` usage introduced in #731 with Godot's `Math::is_nan`. It also replaces an occurrence of `Math_LN2` that should've been `Mathf_LN2`.
> Corrected some math functions/constants

- src/spaces/jolt_physics_direct_space_state_3d.cpp
Apparently `JPH::TransformedShape` has a convenience method for performing collision checks against it, which will deal with all the scaled stuff, as well as allowing you to pass in a base offset.
I figured the base offset might help a teeny tiny bit with precision, or at the very least make the code cleaner, since we don't have to use the more verbose `JPH::CollisionDispatch::sCollideShapeVsShape` anymore.
> Added base offset to `_cast_motion_impl`

- CHANGELOG.md
- src/shapes/jolt_custom_ray_shape.cpp
Fixes #759.
This changes `JoltCustomRayShape`, which powers `SeparationRayShape3D`, to not use `mTreatConvexAsSolid` for its internal ray-cast. This fixes a deliberate discrepancy between this extension and Godot Physics, which apparently prevented users from having a ray shape that could go through perpendicular convex walls and not collide inside it, as seen in #759.
> Changed `SeparationRayShape3D` to not treat convex as solid

- cmake/GodotJoltExternalJolt.cmake
This bumps Jolt from godot-jolt/jolt@4a74ff08e4c4f1e6cd6020b4f929ffca517d088b to godot-jolt/jolt@cc49e07d7c4eb854a60cb21ea0abdfcc93511410 (see diff [here](https://github.com/godot-jolt/jolt/compare/4a74ff08e4c4f1e6cd6020b4f929ffca517d088b...cc49e07d7c4eb854a60cb21ea0abdfcc93511410)).
- New enhanced internal edge removal algorithm
- Vertex radius for soft bodies
- Soft bodies no longer collide with sensors
> Updated Jolt to cc49e07d7c

- src/containers/inline_vector.hpp
- src/misc/utility_functions.hpp
- src/objects/jolt_area_impl_3d.cpp
- src/objects/jolt_body_impl_3d.cpp
- src/objects/jolt_physics_direct_body_state_3d.cpp
- src/shapes/jolt_box_shape_impl_3d.cpp
- src/shapes/jolt_cylinder_shape_impl_3d.cpp
- src/spaces/jolt_physics_direct_space_state_3d.cpp
- src/spaces/jolt_space_3d.cpp
Related to #763.
This replaces the custom `min`, `max` and `clamp` functions found in `utility_functions.hpp` with the `MIN`, `MAX` and `CLAMP` functions provided by godot-cpp.
It also replaces all usages of the C `abs` function with godot-cpp's `ABS`.
> Replaced some utility functions with Godot ones

- cmake/GodotJoltExternalJolt.cmake
This bumps Jolt from godot-jolt/jolt@cc49e07d7c4eb854a60cb21ea0abdfcc93511410 to godot-jolt/jolt@7d8dea5196d54fbe2a3132217aac171d440de4bb (see diff [here](https://github.com/godot-jolt/jolt/compare/cc49e07d7c4eb854a60cb21ea0abdfcc93511410...7d8dea5196d54fbe2a3132217aac171d440de4bb)).
- Soft body bug fixes
> Updated Jolt to godot-jolt/jolt@7d8dea5196

- CHANGELOG.md
- docs/settings.md
- src/objects/jolt_body_impl_3d.cpp
- src/precompiled.hpp
- src/servers/jolt_project_settings.cpp
- src/servers/jolt_project_settings.hpp
- src/shapes/jolt_custom_motion_shape.cpp
- src/shapes/jolt_custom_motion_shape.hpp
- src/spaces/jolt_physics_direct_space_state_3d.cpp
- src/spaces/jolt_query_collectors.hpp
Fixes #530.
Fixes #587.
Fixes #764.
Fixes #771.
This adds a project setting for enabling Jolt's new "enhanced internal edge removal", which helps alleviate ghost collisions.
Note that this applies not only to `RigidBody3D` but also physics queries like `move_and_collide` and `move_and_slide`, which means `CharacterBody3D` benefits from this as well.
> Added project setting for enhanced internal edge removal

- cmake/GodotJoltExternalJolt.cmake
This bumps Jolt from godot-jolt/jolt@7d8dea5196d54fbe2a3132217aac171d440de4bb to godot-jolt/jolt@4615f9ca7fc15e3a114986a5c7339933be56e8a1 (see diff [here](https://github.com/godot-jolt/jolt/compare/7d8dea5196d54fbe2a3132217aac171d440de4bb...4615f9ca7fc15e3a114986a5c7339933be56e8a1)).
- Fixes division by zero in `JPH::Body::GetBodyCreationSettings`
> Updated Jolt to 4615f9ca7f

- cmake/GodotJoltExternalJolt.cmake
This bumps Jolt from godot-jolt/jolt@4615f9ca7fc15e3a114986a5c7339933be56e8a1 to godot-jolt/jolt@7cb5d1d627b134c63dc594cec89c4ba47a3e975c (see diff [here](https://github.com/godot-jolt/jolt/compare/4615f9ca7fc15e3a114986a5c7339933be56e8a1...7cb5d1d627b134c63dc594cec89c4ba47a3e975c)).
- Fixes double-precision Android ARM32 builds
- Fixes macOS 10.12/10.13 double-precision builds
> Updated Jolt to 7cb5d1d627

- src/spaces/jolt_physics_direct_space_state_3d.cpp
This fixes a precision truncation in `test_body_motion`, and thus `move_and_collide` and `move_and_slide` as well.
> Fixed precision issue in `test_body_motion`

- src/spaces/jolt_physics_direct_space_state_3d.cpp
- src/spaces/jolt_physics_direct_space_state_3d.hpp
Fixes #355.
This fixes an issue where `cast_motion` (and thus `ShapeCast3D`) would write `float` fractions to what was actually `real_t` pointers on the Godot side of things, resulting in largely nonsense fractions being returned in double-precision builds.
> Fixed broken `cast_motion` in double-precision builds

- cmake/GodotJoltExternalJolt.cmake
- src/objects/jolt_body_impl_3d.cpp
- src/objects/jolt_body_impl_3d.hpp
This bumps Jolt from godot-jolt/jolt@7cb5d1d627b134c63dc594cec89c4ba47a3e975c to godot-jolt/jolt@eef0d0be7cdee82602eca4607b94eae44e0de478 (see diff [here](https://github.com/godot-jolt/jolt/compare/7cb5d1d627b134c63dc594cec89c4ba47a3e975c...eef0d0be7cdee82602eca4607b94eae44e0de478)).
- `JPH::EAllowedDOFs` now applies in global-space rather than local-space.
> Updated Jolt to eef0d0be7c

- cmake/GodotJoltExternalGodotCpp.cmake
- src/spaces/jolt_physics_direct_space_state_3d.cpp
- src/spaces/jolt_physics_direct_space_state_3d.hpp
This bumps godot-cpp from godot-jolt/godot-cpp@caec7a1feecd56a1db3c4dfd1aa6b4e68c81d010 aka 4.2-stable to godot-jolt/godot-cpp@550f91b2dc38ccf200d7ff1435910f5e2a60f1d6 aka 4.2-stable (see diff [here](https://github.com/godot-jolt/godot-cpp/compare/caec7a1feecd56a1db3c4dfd1aa6b4e68c81d010...550f91b2dc38ccf200d7ff1435910f5e2a60f1d6)).
This changes double-precision builds to use a separate/dedicated `extension_api.json`, which more appropriately reflects the API exposed by double-precision builds of Godot.
This also removes the need for the hack introduced in #782.
> Updated godot-cpp to 550f91b2dc (4.2-stable)

- CHANGELOG.md
- src/objects/jolt_body_impl_3d.cpp
Fixes #798.
This fixes two issues with inertia.
The first issue being that `JoltBodyImpl3D::get_inverse_inertia()` (and thus `PhysicsDirectBodyState3D.inverse_inertia`) was not correctly implemented, as `JPH::MotionProperties::GetInverseInertiaDiagonal()` did not in fact return the local-space inverse inertia diagonal as reported by Godot. Now instead we use `JPH::MotionProperties::GetLocalSpaceInverseInertia()`.
The second issue being that this extension did not support partial custom inertia like Godot Physics does, where you can leave one or two components at zero and have it use the automatically calculated value for those specific components.
> Fixed some issues with inertia

- cmake/GodotJoltExternalJolt.cmake
- src/objects/jolt_soft_body_impl_3d.cpp
This bumps Jolt from godot-jolt/jolt@045a87e23052a6d550619ac0e9e401d96e40e9e9 to godot-jolt/jolt@91272baecbc274941186db6f1e3be118af856ce3 (see diff [here](https://github.com/godot-jolt/jolt/compare/045a87e23052a6d550619ac0e9e401d96e40e9e9...91272baecbc274941186db6f1e3be118af856ce3)).
- Bugfixes related to one-way collisions
- Changed soft-body edge constraints to use a stiffness coefficient rather than compliance (inverse stiffness)
> Updated Jolt to 91272baecb

- cmake/GodotJoltExternalJolt.cmake
- src/objects/jolt_soft_body_impl_3d.cpp
This bumps Jolt from godot-jolt/jolt@91272baecbc274941186db6f1e3be118af856ce3 to godot-jolt/jolt@e60de1aa544dbdb77916b5ef410f2563e2b313bd (see diff [here](https://github.com/godot-jolt/jolt/compare/91272baecbc274941186db6f1e3be118af856ce3...e60de1aa544dbdb77916b5ef410f2563e2b313bd)).
- Changed soft-body edge constraints to use a compliance (inverse stiffness) rather than a stiffness coefficient
> Updated Jolt to e60de1aa54

- src/misc/math.hpp
- src/misc/type_conversions.hpp
I managed to somewhat reliably trigger a Jolt assertion about the quaternion passed into `JPH::Body::MoveKinematic` not being normalized in a particular project/scene.
As far as I can tell this was just the accumulation of numerical inaccuracies, but which turned out to be enough to trigger the `1.0e-5f` threshold Jolt uses for its `JPH::Quat::IsNormalized()`.
This PR addresses this by simply normalizing the result from `Basis::get_quaternion()`.
While looking into it I decided to also refactor the Gram-Schmidt decomposition that's used to separate the scale from the rest of the transform, as required by Jolt, as I'm pretty sure the previous implementation was not entirely correct, since it assumed that the scale of the basis vectors would remain the same even after orthogonalization, …
> Fixed quaternions not being normalized on rare occasions

- CHANGELOG.md
- src/objects/jolt_body_impl_3d.cpp
- src/objects/jolt_shaped_object_impl_3d.cpp
- src/spaces/jolt_physics_direct_space_state_3d.cpp
This adds error-handling to the following methods:
- `PhysicsServer3D::body_set_state` (`BODY_STATE_TRANSFORM`)
- `PhysicsServer3D::body_set_shape_transform`
- `PhysicsServer3D::body_test_motion`
- `PhysicsDirectSpaceState3D::intersect_shape`
- `PhysicsDirectSpaceState3D::cast_motion`
- `PhysicsDirectSpaceState3D::collide_shape`
- `PhysicsDirectSpaceState3D::rest_info`
... to make sure that the transform passed in isn't singular, i.e. doesn't have a determinant of zero. This should catch errors such as passing a transform/basis with one or more zero-scaled axes, before they have a chance to propagate into the simulation, where they eventually cause the dreaded `instance_set_transform: Condition "!v.is_finite()" is true` error.
> Added error-handling for zero-scaled transforms

- .clang-format
- .clang-tidy
- .github/actions/setup-linux/action.yml
- .github/actions/setup-macos/action.yml
- docs/building.md
- docs/hacking.md
- scripts/ci_setup_linux.ps1
This updates the minimum versions for the various toolchains, namely:
- Linux
- GCC: 11 -> 13
- Clang: 15 -> 16
- macOS
- Xcode: 14.3 -> 15.2
The `clang-format` and `clang-tidy` configurations have been updated accordingly, which should work on Windows as well, as it should be on LLVM 17 by now.
> Updated toolchains

- cmake/GodotJoltExternalJolt.cmake
This bumps Jolt from godot-jolt/jolt@e60de1aa544dbdb77916b5ef410f2563e2b313bd to godot-jolt/jolt@d1936c8506f7b1d321e84a42e8bcdfd2f11bda5a (see diff [here](https://github.com/godot-jolt/jolt/compare/e60de1aa544dbdb77916b5ef410f2563e2b313bd...d1936c8506f7b1d321e84a42e8bcdfd2f11bda5a)).
- Fix for numerical issue with cylinder vs nearly parallel triangle
Fixes #789.
> Updated Jolt to d1936c8506

- CHANGELOG.md
- src/objects/jolt_shaped_object_impl_3d.cpp
- src/shapes/jolt_custom_empty_shape.cpp
- src/shapes/jolt_custom_empty_shape.hpp
This fixes an issue where if you had a body without any shapes (or simply no enabled/valid shapes) it wouldn't apply any custom center-of-mass that might be set on the body.
This also changes the default inertia for shapeless bodies to be the same as in Godot Physics, meaning `(1, 1, 1)`.
Godot Physics seems to (perhaps unintentionally) support this use-case of simply not having any shapes while still overriding the center-of-mass and inertia to more predictably control its behavior when force/torque is applied to it.
This PR should hopefully get us closer to some kind of parity in that regard.
> Fixed some issues with shapeless bodies

- CHANGELOG.md
- src/objects/jolt_body_impl_3d.cpp
- src/objects/jolt_physics_direct_body_state_3d.cpp
Fixes #827.
This disables Jolt's application of damping for `RigidBody3D` and replaces it with custom (but same) damping which is instead done _before_ any force integration, as opposed to after.
This way of doing it seems to yield more consistent results across different update frequencies when using high (>1) damping values.
> Fixed damping being inconsistent at different update frequencies

- cmake/GodotJoltExternalJolt.cmake
- src/spaces/jolt_debug_geometry_3d.cpp
This bumps Jolt from godot-jolt/jolt@d1936c8506f7b1d321e84a42e8bcdfd2f11bda5a to godot-jolt/jolt@cf22ca9e16c63805fa6285ae855522e82587469d (see diff [here](https://github.com/godot-jolt/jolt/compare/d1936c8506f7b1d321e84a42e8bcdfd2f11bda5a...cf22ca9e16c63805fa6285ae855522e82587469d)).
- Optimizations for soft bodies
> Updated Jolt to cf22ca9e16

- CHANGELOG.md
- src/objects/jolt_area_impl_3d.cpp
- src/objects/jolt_body_impl_3d.cpp
- src/objects/jolt_object_impl_3d.cpp
- src/objects/jolt_soft_body_impl_3d.cpp
- src/servers/jolt_physics_server_3d.cpp
- src/servers/jolt_physics_server_3d.hpp
- src/spaces/jolt_physics_direct_space_state_3d.cpp
- src/spaces/jolt_space_3d.cpp
- src/spaces/jolt_space_3d.hpp
Fixes #833.
This adds a call to `JPH::PhysicsSystem::OptimizeBroadPhase()` when performing any physics query after having added 128 bodies or more to that particular physics space, without having actually stepped it first. This is largely only applicable to editor viewport physics spaces.
Without this optimization pass you could end up with a broad-phase structure such that any physics query would max out the fixed-size stack that's used while traversing the broad-phase, leading to incomplete/incorrect results.
To help achieve this I've moved/refactored the responsibility of creation/destruction of Jolt bodies to the space itself.
> Added broad-phase optimization to physics queries

- src/objects/jolt_body_impl_3d.cpp
I was going through the `TODO(mihe)` tags and noticed this one. The calculation that's there currently is quite expensive (`GetMassProperties` does quite a lot of things) and I think the calculation is quite trivial since Jolt also splits the inertia in a diagonal matrix and a rotation matrix.
Note: Code is totally untested as I don't know how to test it!
> Simplified `JoltBodyImpl3D::get_principal_inertia_axes`

- cmake/GodotJoltExternalJolt.cmake
- src/servers/jolt_globals.cpp
This bumps Jolt from godot-jolt/jolt@3e13b2c097905c8ca77d98813389b56cc200932e to godot-jolt/jolt@3ae9520be65c60d0524692be01c0b35d7648d150 (see diff [here](https://github.com/godot-jolt/jolt/compare/3e13b2c097905c8ca77d98813389b56cc200932e...3ae9520be65c60d0524692be01c0b35d7648d150)).
> Updated Jolt to 3ae9520be6

- src/servers/jolt_project_settings.cpp
Fixes #832.
This changes the step size for the `solver/contact_speculative_distance` and `solver/contact_allowed_penetration` project settings from 0.001 to 0.00001.
> Decreased step size for contact project settings

- src/objects/jolt_body_impl_3d.cpp
- src/objects/jolt_body_impl_3d.hpp
- src/objects/jolt_shaped_object_impl_3d.cpp
- src/spaces/jolt_physics_direct_space_state_3d.cpp
This refactors the error handling introduced in #809 and #810 a bit, by allowing it to carry on with an identity basis/scale instead of just erroring out completely.
This is necessary for methods like `JoltShapedObjectImpl3D::add_shape` (which wasn't doing any error handling at all until now) since not adding the shape at all is going to create a lot more problems down the line.
I also modified the error messages a bit to hopefully make this clearer.
> Refactored scale error handling

- scripts/ci_setup_linux.ps1
Apparently the APT repository that I've been manually adding to get access to later GCC versions (and equivalent `*-multilib`) in the Linux setup script was not the appropriate one for the packages I was hoping to install from it, and instead this just happened to work thanks to GitHub providing this repository in its runner already.
GitHub has now pulled this repository from their runners and as a result all the Linux CI builds are failing one way or another.
This PR (hopefully) fixes that by adding the correct repository.
> Fixed failing Linux CI builds

- src/spaces/jolt_space_3d.cpp
As a result of #765 and #828 the snapshots were a bit broken, due to gravity scale and damping on the Jolt body effectively always being 0.
This fixes that, by copying over the correct values from our custom integration.
> Fixed snapshots not storing the correct gravity/damping

- cmake/GodotJoltExternalMimalloc.cmake
This bumps mimalloc from godot-jolt/mimalloc@43ce4bd7fd34bcc730c1c7471c99995597415488 (2.1.2) to godot-jolt/mimalloc@a1b284de0aecc0ea0e8846656fd01043253b84bb (2.1.6) (see diff [here](https://github.com/godot-jolt/mimalloc/compare/43ce4bd7fd34bcc730c1c7471c99995597415488...a1b284de0aecc0ea0e8846656fd01043253b84bb)).
> Updated mimalloc to a1b284de0a (2.1.6)

- CHANGELOG.md
- src/spaces/jolt_physics_direct_space_state_3d.cpp
- src/spaces/jolt_physics_direct_space_state_3d.hpp
Fixes #626.
Fixes #643.
This applies the change to `PhysicsServer3D.body_test_motion` that was suggested by @yosoyfreeman in #812, which effectively reverts the hack introduced by #559 and replaces its depth-based contact discard with an angle-based one instead.
Note that this also impacts `PhysicsBody3D.move_and_collide` as well as `PhysicsBody3D.test_move` and of course `CharacterBody3D.move_and_slide`.
This will possibly lead to a regression in ghost collisions for some scenarios, like the one seen in #529, but the downsides of #559 have proved to be too great to keep it around.
> Changed `body_test_motion` to discard by angle rather than depth

- src/spaces/jolt_physics_direct_space_state_3d.cpp
Apparently the penetration axis passed to `JPH::PruneContactPoints` has to be normalized. This PR fixes that.
> Fixed Jolt assertion when generating contact manifolds

- CHANGELOG.md
- src/joints/jolt_joint_gizmo_plugin_3d.cpp
Fixes #855.
This flips the rotation for the way angular limits are drawn for the substitute joint gizmos, meaning it now lines up with the way these limits actually behave.
This should ideally have been done as part of #725, as I had originally (and arguably incorrectly) made this gizmo to suit the way single-body joints worked previously, which has been changed as of #725.
> Flipped rotation for joint's angular limit gizmo

- src/shapes/jolt_box_shape_impl_3d.cpp
- src/shapes/jolt_capsule_shape_impl_3d.cpp
- src/shapes/jolt_concave_polygon_shape_impl_3d.cpp
- src/shapes/jolt_convex_polygon_shape_impl_3d.cpp
- src/shapes/jolt_cylinder_shape_impl_3d.cpp
- src/shapes/jolt_height_map_shape_impl_3d.cpp
- src/shapes/jolt_separation_ray_shape_impl_3d.cpp
- src/shapes/jolt_shape_impl_3d.cpp
- src/shapes/jolt_shape_impl_3d.hpp
- src/shapes/jolt_sphere_shape_impl_3d.cpp
- src/shapes/jolt_world_boundary_shape_impl_3d.cpp
This changes the setting of shape data (and margins) to not have any effect when setting the same value as what was previously set.
Until now this has always caused a rebuild of the entire compound shape, regardless of value, which can be somewhat wasteful, especially when there are complex compound shapes involved.
> Added early-out when setting shape data with same value

- cmake/GodotJoltExternalJolt.cmake
This bumps Jolt from godot-jolt/jolt@3ae9520be65c60d0524692be01c0b35d7648d150 to godot-jolt/jolt@deeb4bca047308ddd48345c2d906ed1c9ae487ca (see diff [here](https://github.com/godot-jolt/jolt/compare/3ae9520be65c60d0524692be01c0b35d7648d150...deeb4bca047308ddd48345c2d906ed1c9ae487ca)).
- Adds `JPH::BodyInterface::ResetSleepTimer`
- Adds `ENABLE_OBJECT_STREAM` CMake option
> Updated Jolt to deeb4bca04

- src/objects/jolt_body_impl_3d.cpp
Fixes #866.
This makes sure that the sleep timer for `RigidBody3D` is reset whenever it's woken up.
> Fixed sleep timer not resetting when applying force/torque

- src/containers/local_vector.hpp
- src/objects/jolt_body_impl_3d.cpp
Fixes #868.
This adds error checks to `JoltBodyImpl3D::set_max_contacts_reported`, `LocalVector::resize` and `LocalVector::reserve` to make sure we don't try to cast a negative value to a `size_t`.
> Fixed crash when setting a negative `max_contacts_reported`

- src/register_types.cpp
Currently internal editor-only classes like `JoltJointGizmoPlugin3D` and `JoltEditorPlugin` show up in the list of node types when you try to add a node, which they shouldn't.
This also hides `JoltDebugGeometry3D` in all distributed builds.
> Changed editor-specific classes to register as internal

- src/objects/jolt_soft_body_impl_3d.cpp
Related to #868.
When running [Qarminer](https://github.com/qarmin/Qarminer) on latest `master` it triggered some crashes in `SoftBody3D`, where the shared soft body data sometimes hadn't been initialized when calling certain soft body methods.
I don't believe these crashes were likely to cause any trouble in real-world code, but this should make it more robust either way.
> Added null checks to `JoltSoftBodyImpl3D`

- src/servers/jolt_physics_server_3d.cpp
The `generic_6dof_joint_set_jolt_param`, `generic_6dof_joint_set_jolt_flag` and respective getter methods on `JoltPhysicsServer3D` had left out the `axis` parameter name, causing subsequent parameters (`flag` and `value`) to be offset and the last parameter to be labeled as unknown.
> Fixed parameter names for 6DOF methods

- src/objects/jolt_body_impl_3d.cpp
Since we no longer (as of #783) need to defer the calculation of mass properties in order to twiddle with the inverse inertia to accommodate for global-space axis-locking, we can now remove this hack.
> Removed now pointless deferring of mass properties

- docs/settings.md
- src/servers/jolt_project_settings.cpp
Some of the project settings that have been added since the last release felt a bit out-of-place in terms of their categories.
It didn't seem necessary to have soft bodies be its own category, especially since regular bodies aren't grouped as such, so `soft_bodies/point_margin` is now `collisions/soft_body_point_margin` instead.
The `solver/body_pair_cache_*` settings that were added in #865 are now instead `collisions/body_pair_cache_*`, since I figured it has more to do with caching collision results rather than solving for them.
CC @MemoriesIn8bit (this will break stuff for you)
> Moved some of the newer project settings around a bit

- cmake/GodotJoltExternalJolt.cmake
- src/objects/jolt_body_impl_3d.cpp
This bumps Jolt from godot-jolt/jolt@deeb4bca047308ddd48345c2d906ed1c9ae487ca to godot-jolt/jolt@343687a61493b1f0642b97b4b7fd05484acc3048 (see diff [here](https://github.com/godot-jolt/jolt/compare/deeb4bca047308ddd48345c2d906ed1c9ae487ca...343687a61493b1f0642b97b4b7fd05484acc3048)).
- Changes `JPH::BodyInterface::ActivateBody` to also reset sleep timer.
> Updated Jolt to 343687a614

- src/objects/jolt_body_impl_3d.cpp
It seems that #879 broke axis-locking completely, as we now never actually properly initialize `JPH::BodyCreationSettings::mAllowedDOFs`. This fixes that.
> Fixed broken axis-locking

- cmake/templates/info_ios.plist.in
- cmake/templates/info_macos.plist.in
When exporting macOS builds in Godot 4.3 you'll be met with a warning message saying "Info.plist missing or invalid, new Info.plist generated", which seems to be because of godotengine/godot#87908, which checks to make sure that there are a certain set of `CF*` keys in the extension framework's `Info.plist`.
Godot Jolt was missing one of these keys, namely `CFBundleSupportedPlatforms`, and as such its `Info.plist` was considered invalid.
> Added `CFBundleSupportedPlatforms` to `Info.plist`

- CHANGELOG.md
- src/objects/jolt_shaped_object_impl_3d.cpp
- src/shapes/jolt_concave_polygon_shape_impl_3d.cpp
- src/shapes/jolt_concave_polygon_shape_impl_3d.hpp
- src/shapes/jolt_custom_double_sided_shape.cpp
- src/shapes/jolt_height_map_shape_impl_3d.cpp
- src/shapes/jolt_height_map_shape_impl_3d.hpp
- src/shapes/jolt_shape_impl_3d.cpp
- src/shapes/jolt_shape_impl_3d.hpp
Fixes #897.
This fixes an issue where an `Area3D` would sometimes fail to detect an overlap with a `ConcavePolygonShape3D`.
The issue stemmed from the collision resulting in only back-face hits, which meant that the `ConcavePolygonShape3D` had to have the `backface_collision` property enabled for the overlap to be reigstered.
This PR fixes this by wrapping every `Area3D` in the `JoltCustomDoubleSidedShape` decorator shape, which forces every collision with said shape to respect back-face collisions, meaning it's no longer dependent on the `ConcavePolygonShape3D` having it enabled.
> Changed `Area3D` to always collide with back-faces

- src/shapes/jolt_custom_double_sided_shape.cpp
With #899 having made it possible for two shapes decorated with `JoltCustomDoubleSidedShape` to collide with eachother, and me having used `JPH::CollisionDispatch::sReversedCollideShape` for part of the collision dispatch, you could end up endlessly reversing the reversal of the reversal of the reversal, etc. which led to a stack overflow.
This fixes that by not relying on `JPH::CollisionDispatch::sReversedCollideShape` and instead implementing the dispatch functions for both the scenario where the double-sided shape is shape 1 as well as shape 2.
I also removed the cast dispatch functions, since `JoltCustomDoubleSidedShape` will never be used in the context of a shape-cast anyway.
> Fixed stack overflow when two double-sided shapes collide

- .github/actions/cmake-configure/action.yml
Related to #902.
Due to the Emscripten toolchain file apparently using uninitialized variables the only realistic option is allow disabling the strict CMake warnings for those builds.
This PR allows for that by adding a new `strict` parameter to the `cmake-configure` action.
> Added ability to omit strict CMake warnings for CI builds

- src/objects/jolt_body_impl_3d.cpp
It doesn't make a whole lot of sense to have `PhysicsDirectBodyState3D.get_velocity_at_local_position` emit an error if you tried calling it without a physics space. It makes more sense to just return a zero vector instead, which is what this PR does.
> Changed point velocity to default to zero instead of error

- cmake/GodotJoltExternalJolt.cmake
This bumps Jolt from godot-jolt/jolt@343687a61493b1f0642b97b4b7fd05484acc3048 to godot-jolt/jolt@fda5b4aa5a9f6651efc8bc1fda5be9e927a14e92 (see diff [here](https://github.com/godot-jolt/jolt/compare/343687a61493b1f0642b97b4b7fd05484acc3048...fda5b4aa5a9f6651efc8bc1fda5be9e927a14e92)).
- Fixes SIMD not being enabled for 32-bit x86 builds on non-Windows platforms
- Fixes bug in ray-casting against soft bodies
- Improves enhanced internal edge detection
Fixes #587 (for real this time).
> Updated Jolt to fda5b4aa5a

- CHANGELOG.md
- src/joints/jolt_joint_impl_3d.cpp
Fixes #913.
This refactors `JoltJointImpl3D::get_space` to fix some broken logic in how it selects the space when dealing with two-body joints.
Previously the code assumed that if one of the spaces were invalid then it's a single-body joint and the other space would be fine to return. However, when we have a two-body joint where one of the bodies is disabled, then we'll end up in that same scenario, and we want this method to return `nullptr` in that case, to signify that we don't want to continue building this joint.
This PR fixes that by returning `nullptr` in the case where we have a two-body joint with only one valid space.
> Fixed crash when re-enabling processing for joint bodies

- cmake/GodotJoltExternalJolt.cmake
This bumps Jolt from godot-jolt/jolt@fda5b4aa5a9f6651efc8bc1fda5be9e927a14e92 to godot-jolt/jolt@d50bee9d983303d77c1a8ae6b2380a77203cfc52 (see diff [here](https://github.com/godot-jolt/jolt/compare/fda5b4aa5a9f6651efc8bc1fda5be9e927a14e92...d50bee9d983303d77c1a8ae6b2380a77203cfc52)).
- Adds `JPH::Shape::MakeScaleValid`
- Fixes Emscripten builds
> Updated Jolt to d50bee9d98

- CHANGELOG.md
- src/objects/jolt_area_impl_3d.cpp
- src/objects/jolt_area_impl_3d.hpp
- src/objects/jolt_body_impl_3d.cpp
- src/objects/jolt_body_impl_3d.hpp
Fixes #773 (finally).
When reusing a `RigidBody3D`, `CharacterBody3D` or `AnimatableBody3D` inbetween scene changes, or when moving them between different `World3D`, and said body was overlapping with an `Area3D`, you would end up getting a use-after-free because the bodies would never end up receiving the relevant overlap event and thus hang on to a bunch of stale pointers. This often manifested as an "Unhandled override mode" error with a bunch of random numbers, due to the body accessing random (freed) memory.
This PR fixes that by having bodies to go through their list of areas when changing physics space and forcing them to unregister the overlap, and then clearing the list of areas entirely.
> Fixed use-after-free when reusing bodies that overlapped areas

- src/misc/math.cpp
- src/misc/math.hpp
Apparently #808 broke negative scaling, due to me replacing the usage of `Basis::get_scale` in `Math::decompose` with some "manual" calculations, but in the process forgetting to actually incorporate the sign of the determinant like `Basis::get_scale` does.
This PR fixes this issue by doing exactly that.
I also moved `Math::decompose` into an actual `*.cpp` file, since it really has no business being force-inlined anymore.
> Fixed negative scaling

- cmake/GodotJoltExternalJolt.cmake
- src/servers/jolt_globals.cpp
This bumps Jolt from godot-jolt/jolt@d50bee9d983303d77c1a8ae6b2380a77203cfc52 to godot-jolt/jolt@4084c13b676a2e7ebf9662b47dcb949179b8c4a1 (see diff [here](https://github.com/godot-jolt/jolt/compare/d50bee9d983303d77c1a8ae6b2380a77203cfc52...4084c13b676a2e7ebf9662b47dcb949179b8c4a1)).
- Adds default overrides for `IsValidScale` and `MakeValidScale` to `JPH::DecoratedShape`
- Fixes `ScaledShape::MakeScaleValid`
> Updated Jolt to 4084c13b67

- src/joints/jolt_cone_twist_joint_3d.cpp
- src/joints/jolt_cone_twist_joint_impl_3d.cpp
- src/joints/jolt_generic_6dof_joint.cpp
- src/joints/jolt_generic_6dof_joint_impl_3d.cpp
- src/joints/jolt_hinge_joint_3d.cpp
- src/joints/jolt_hinge_joint_impl_3d.cpp
- src/joints/jolt_joint_gizmo_plugin_3d.cpp
- src/joints/jolt_pin_joint_impl_3d.cpp
- src/joints/jolt_slider_joint_3d.cpp
- src/joints/jolt_slider_joint_impl_3d.cpp
- src/misc/error_macros.hpp
- src/objects/jolt_area_impl_3d.cpp
- src/objects/jolt_body_impl_3d.cpp
- src/objects/jolt_object_impl_3d.cpp
- src/objects/jolt_soft_body_impl_3d.cpp
- src/spaces/jolt_layer_mapper.cpp
- src/spaces/jolt_motion_filter_3d.cpp
- src/spaces/jolt_query_filter_3d.cpp
- src/spaces/jolt_space_3d.cpp
- src/spaces/jolt_temp_allocator.cpp
All the "Unhandled ..." errors are currently a bit vague as to whether they're the user's fault or not, and it's also not super clear that it's originating from this extension.
This PR fixes that by making them all use some new macros that explicitly mentions that this is a bug that shouldn't happen and that it should be reported in this repo.
> Added more explicit message to errors that shouldn't happen

- src/misc/math.hpp
- src/objects/jolt_body_impl_3d.cpp
- src/objects/jolt_shaped_object_impl_3d.cpp
- src/shapes/jolt_shape_impl_3d.cpp
- src/shapes/jolt_shape_impl_3d.hpp
- src/spaces/jolt_physics_direct_space_state_3d.cpp
Fixes #912.
This refactors the error-handling for scaling introduced in #810.
The current usage of `JPH::Shape::IsValidScale` poses some problems in the context of Godot, since the tolerance of `JPH::Shape::IsValidScale` is (understandably) quite small, and Godot doesn't do any sort of automatic orthonormalization of its transforms, which means that it doesn't take many frames for something like the rotation of a `CharacterBody3D` to start messing with the orthogonality of its transforms, thereby resulting in weird scaling and potentially causing `JPH::Shape::IsValidScale` to fail.
The technically correct resolution to this would of course be for the user to just orthonormalize its transforms, or for this extension to disregard scaling completely (like Godot Physics does), but given the …
> Improved error-handling for scaling

- src/joints/jolt_cone_twist_joint_impl_3d.cpp
- src/joints/jolt_generic_6dof_joint_impl_3d.cpp
- src/joints/jolt_hinge_joint_impl_3d.cpp
- src/joints/jolt_joint_impl_3d.cpp
- src/joints/jolt_joint_impl_3d.hpp
- src/joints/jolt_pin_joint_impl_3d.cpp
- src/joints/jolt_slider_joint_impl_3d.cpp
Modifying a joint, like changing the equilibrium point of a sprung joint, while the bodies connected to it are sleeping, won't actually wake up to reflect its new value.
This PR fixes that by waking up both bodies when any modification is done to any joint.
> Added waking of bodies when modifying joints

- src/shapes/jolt_custom_decorated_shape.hpp
With `JPH::DecoratedShape` now overriding `IsValidScale` there's no longer any need for `JoltCustomDecoratedShape` to do so.
> Removed redundant override of `JPH::Shape::IsValidScale`

- cmake/GodotJoltExternalJolt.cmake
This bumps Jolt from godot-jolt/jolt@4084c13b676a2e7ebf9662b47dcb949179b8c4a1 to godot-jolt/jolt@b53b830ca8cd8dff1daffafefa2a6db8a514dfc4 (see diff [here](https://github.com/godot-jolt/jolt/compare/4084c13b676a2e7ebf9662b47dcb949179b8c4a1...b53b830ca8cd8dff1daffafefa2a6db8a514dfc4)).
- Changes/fixes related to Emscripten builds
- Disables exceptions by default for all platforms
- Disables RTTI by default for all platforms (but we unfortunately need to enable it)
> Updated Jolt to b53b830ca8

- CHANGELOG.md
- src/joints/jolt_joint_gizmo_plugin_3d.cpp
This effectively reverts #862. In hindsight this change just made things weird in a different way (arguably worse), rather than fixing anything.
The actual problem of #855 is that the gizmo doesn't take the reference frames of the bodies into account when drawing, so will never really represent the true start and end point of the angular limits.
I'm not sure this can ever really be fixed to make every arrangement intuitive, but that's a problem for another day.
> Flipped rotation for joint's angular limit gizmo again

- cmake/GodotJoltExternalGodotCpp.cmake
This bumps godot-cpp from godot-jolt/godot-cpp@0680a37de26a1489f9a75f4ad9b4da5d280d9012 aka 4.3-beta1 to godot-jolt/godot-cpp@8e99c4b79422265e123080a144a9c3bd814abe54 aka 4.3-stable (see diff [here](https://github.com/godot-jolt/godot-cpp/compare/0680a37de26a1489f9a75f4ad9b4da5d280d9012...8e99c4b79422265e123080a144a9c3bd814abe54)).
> Updated godot-cpp to 4.3-stable

- CHANGELOG.md
- src/objects/jolt_soft_body_impl_3d.cpp
- src/objects/jolt_soft_body_impl_3d.hpp
See #909.
This changes the following physics server methods to also wake up the soft body:
- `soft_body_set_simulation_precision`
- `soft_body_set_total_mass`
- `soft_body_set_damping_coefficient`
- `soft_body_move_point`
... which affects the following `SoftBody3D` properties:
- `simulation_precision`
- `total_mass`
- `damping_coefficient`
... as well as when attachments move pinned `SoftBody3D` points.
> Fixed issues with `SoftBody3D` not waking up as it should

- src/objects/jolt_area_impl_3d.cpp
- src/objects/jolt_body_impl_3d.cpp
- src/objects/jolt_object_impl_3d.cpp
- src/objects/jolt_object_impl_3d.hpp
- src/objects/jolt_shaped_object_impl_3d.cpp
- src/objects/jolt_soft_body_impl_3d.cpp
The current way of checking whether the object (body/area) is actually inside a space, by checking to see whether `space` is null, is somewhat incomplete, as there is technically a limbo state where `space` is set but `jolt_id` isn't, resulting in errors being emitted.
This PR adds a new `in_space()` method to also check that the `jolt_id` is valid.
> Changed in-space check to also consider Jolt ID

- src/objects/jolt_body_impl_3d.cpp
- src/objects/jolt_shaped_object_impl_3d.cpp
- src/objects/jolt_shaped_object_impl_3d.hpp
- src/shapes/jolt_box_shape_impl_3d.cpp
- src/shapes/jolt_box_shape_impl_3d.hpp
- src/shapes/jolt_capsule_shape_impl_3d.cpp
- src/shapes/jolt_capsule_shape_impl_3d.hpp
- src/shapes/jolt_concave_polygon_shape_impl_3d.cpp
- src/shapes/jolt_concave_polygon_shape_impl_3d.hpp
- src/shapes/jolt_convex_polygon_shape_impl_3d.cpp
- src/shapes/jolt_convex_polygon_shape_impl_3d.hpp
- src/shapes/jolt_cylinder_shape_impl_3d.cpp
- src/shapes/jolt_cylinder_shape_impl_3d.hpp
- src/shapes/jolt_height_map_shape_impl_3d.cpp
- src/shapes/jolt_height_map_shape_impl_3d.hpp
- src/shapes/jolt_separation_ray_shape_impl_3d.cpp
- src/shapes/jolt_separation_ray_shape_impl_3d.hpp
- src/shapes/jolt_shape_impl_3d.hpp
- src/shapes/jolt_shape_instance_3d.cpp
- src/shapes/jolt_shape_instance_3d.hpp
- src/shapes/jolt_sphere_shape_impl_3d.cpp
- src/shapes/jolt_sphere_shape_impl_3d.hpp
- src/shapes/jolt_world_boundary_shape_impl_3d.hpp
- src/spaces/jolt_broad_phase_layer.hpp
- src/spaces/jolt_layer_mapper.cpp
- src/spaces/jolt_motion_filter_3d.cpp
- src/spaces/jolt_query_filter_3d.cpp
Related to #941.
This adds a new broad phase layer called `BODY_STATIC_BIG`, which is meant to be for bodies whose AABB exceeds (the very arbitrary) 900 meters in size on any axis. This should hopefully help keep the spatial partitioning of the standard `BODY_STATIC` layer a bit more balanced/optimized, especially when adding the upcoming `WorldBoundaryShape3D` to a scene.
> Added dedicated broad phase layer for big static objects

- cmake/GodotJoltExternalJolt.cmake
This bumps Jolt from godot-jolt/jolt@b53b830ca8cd8dff1daffafefa2a6db8a514dfc4 to godot-jolt/jolt@ff50a7a800111b16aa5fcf8a8ab21beda66d64ca (see diff [here](https://github.com/godot-jolt/jolt/compare/b53b830ca8cd8dff1daffafefa2a6db8a514dfc4...ff50a7a800111b16aa5fcf8a8ab21beda66d64ca)).
- Adds `JPH::PlaneShape`
> Updated Jolt to ff50a7a800

- CHANGELOG.md
- README.md
- docs/settings.md
- examples/scenes/shapes/shapes.tscn
- src/misc/type_conversions.hpp
- src/objects/jolt_body_impl_3d.cpp
- src/objects/jolt_shaped_object_impl_3d.cpp
- src/precompiled.hpp
- src/servers/jolt_project_settings.cpp
- src/servers/jolt_project_settings.hpp
- src/shapes/jolt_world_boundary_shape_impl_3d.cpp
- src/shapes/jolt_world_boundary_shape_impl_3d.hpp
Fixes #104.
This implements `WorldBoundaryShape3D` using the newly introduced `JPH::PlaneShape` as the underlying Jolt shape.
This also brings with it a project setting for setting the effective size of this plane, which by default is set to 2000 meters.
> Added support for `WorldBoundaryShape3D`

- CHANGELOG.md
- src/objects/jolt_body_impl_3d.cpp
- src/objects/jolt_physics_direct_body_state_3d.cpp
- src/objects/jolt_shaped_object_impl_3d.cpp
- src/objects/jolt_shaped_object_impl_3d.hpp
Fixes #947.
It seems that there's been a long-standing discrepancy with Godot Physics when it comes to the `center_of_mass` property of `PhysicsDirectBodyState3D`, where we've been reporting an absolute global-space position rather than a relative global-space one like Godot Physics does (and states in its documentation).
This PR changes this to instead match Godot Physics.
> Fixed center-of-mass not being a relative global position

- cmake/GodotJoltExternalJolt.cmake
This bumps Jolt from godot-jolt/jolt@ff50a7a800111b16aa5fcf8a8ab21beda66d64ca to godot-jolt/jolt@c572b8f0a6d843752a415614dfbdecacf9b3a34e (see diff [here](https://github.com/godot-jolt/jolt/compare/ff50a7a800111b16aa5fcf8a8ab21beda66d64ca...c572b8f0a6d843752a415614dfbdecacf9b3a34e)).
- Fixes #945
> Updated Jolt to c572b8f0a6

- cmake/GodotJoltExternalJolt.cmake
This bumps Jolt from godot-jolt/jolt@c572b8f0a6d843752a415614dfbdecacf9b3a34e to godot-jolt/jolt@c08b9e83b90481adb04df81dcfbdf9da3852a935 (see diff [here](https://github.com/godot-jolt/jolt/compare/c572b8f0a6d843752a415614dfbdecacf9b3a34e...c08b9e83b90481adb04df81dcfbdf9da3852a935)).
- Adds ability to store per-triangle user data in `JPH::MeshShape`
> Updated Jolt to c08b9e83b9

- CHANGELOG.md
- README.md
- docs/settings.md
- src/servers/jolt_project_settings.cpp
- src/servers/jolt_project_settings.hpp
- src/shapes/jolt_concave_polygon_shape_impl_3d.cpp
- src/spaces/jolt_physics_direct_space_state_3d.cpp
- src/spaces/jolt_physics_direct_space_state_3d.hpp
Fixes #702.
This adds support for the `face_index` field found in the result `Dictionary` of `intersect_ray`, also known as `get_collision_face_index()` in the `RayCast3D` node.
Note that this feature is opt-in through a new project setting called `physics/jolt_3d/queries/enable_ray_cast_face_index`, as this feature adds roughly an additional 25% extra memory to every `ConcavePolygonShape3D`.
> Added support for `face_index` to ray-casts

- CHANGELOG.md
- src/objects/jolt_soft_body_impl_3d.cpp
- src/objects/jolt_soft_body_impl_3d.hpp
Probably fixes #951.
There was some problematic error-checking happening in `JoltSoftBodyImpl3D` with regards to checking for valid pin indices, and whether we're actually (properly) inside of a physics space or not, which in some cases could lead to a crash even.
This PR should address all that.
I also threw in some refactoring to clean up some code duplication (`_pin_vertices`).
> Fixed crash when changing mesh of soft body with pinned vertices

- CHANGELOG.md
- src/joints/jolt_cone_twist_joint_3d.cpp
- src/joints/jolt_generic_6dof_joint.cpp
- src/joints/jolt_hinge_joint_3d.cpp
- src/servers/jolt_project_settings.cpp
Fixes #961.
This replaces all usage of the `radians` property hint with the newer `radians_as_degrees`, as the former seems to have been deprecated, causing `DISABLE_DEPRECATED` builds of Godot to display any angle property in radians as opposed to degrees.
> Replaced `radians` property hints with `radians_as_degrees`

- cmake/GodotJoltExternalJolt.cmake
- src/shapes/jolt_custom_ray_shape.cpp
- src/spaces/jolt_physics_direct_space_state_3d.cpp
This bumps Jolt from godot-jolt/jolt@c08b9e83b90481adb04df81dcfbdf9da3852a935 to godot-jolt/jolt@8187798876e0753b25ef6c6b9a308bf2d1255b8a (see diff [here](https://github.com/godot-jolt/jolt/compare/c08b9e83b90481adb04df81dcfbdf9da3852a935...8187798876e0753b25ef6c6b9a308bf2d1255b8a)).
- Splits `RayCastSettings::mBackFaceMode` into `mBackFaceModeTriangles` and `mBackFaceModeConvex`.
> Updated Jolt to 8187798876

- CHANGELOG.md
- README.md
- src/objects/jolt_shaped_object_impl_3d.cpp
- src/servers/jolt_project_settings.cpp
- src/servers/jolt_project_settings.hpp
- src/shapes/jolt_concave_polygon_shape_impl_3d.cpp
- src/shapes/jolt_concave_polygon_shape_impl_3d.hpp
- src/shapes/jolt_custom_double_sided_shape.cpp
- src/shapes/jolt_custom_double_sided_shape.hpp
- src/shapes/jolt_custom_ray_shape.cpp
- src/shapes/jolt_height_map_shape_impl_3d.cpp
- src/shapes/jolt_shape_impl_3d.cpp
- src/shapes/jolt_shape_impl_3d.hpp
- src/spaces/jolt_physics_direct_space_state_3d.cpp
Fixes #273.
Fixes #542.
Fixes #644.
Fixes #655.
Fixes #869.
Fixes #946.
Fixes #957.
In the interest of becoming more compatible with Godot Physics (as discussed [here](https://github.com/godotengine/godot-proposals/issues/7308#issuecomment-2307521547) and [here](https://github.com/godot-jolt/godot-jolt/issues/957)) and with Jolt now differentiating between triangle back-faces and convex back-faces, this PR addresses these two discrepancies mentioned in `README.md`:
> - Ray-casts using `hit_back_faces` will hit the back/inside of all shapes, not only concave ones
> [...]
> - Ray-casts are not affected by the `backface_collision` property of `ConcavePolygonShape3D`
Now instead these will behave as with Godot Physics, meaning:
1. `hit_back_faces` will no longer hit the back/inside of convex …
> Changed ray-casting to behave more like in Godot Physics

- cmake/GodotJoltExternalJolt.cmake
This bumps Jolt from godot-jolt/jolt@8187798876e0753b25ef6c6b9a308bf2d1255b8a to godot-jolt/jolt@754f3bce701e1fe6514d31f4b7f071f6af54e664 (see diff [here](https://github.com/godot-jolt/jolt/compare/8187798876e0753b25ef6c6b9a308bf2d1255b8a...754f3bce701e1fe6514d31f4b7f071f6af54e664)).
- Fixes #951.
> Updated Jolt to 754f3bce70

- src/spaces/jolt_physics_direct_space_state_3d.cpp
Related to #954.
This adds a mention of `ShapeCast3D` to the scaling errors that are emitted from `cast_motion` and `get_rest_info`, in case someone isn't using these two methods directly but instead rely entirely on `ShapeCast3D`.
> Improved error message for invalid scaling of `ShapeCast3D`

- CMakePresets.json
Related to #971.
For whatever reason the `${hostSystemName}` conditions in the build presets are not only entirely redundant now (since it seems to infer the condition from the configuration preset) but they also seem to actively break things, as the build presets don't actually show up in places like the VS Code CMake Tools extension when just using `CMakePresets.json` and not `CMakeUserPresets.json`.
This PR therefore removes them entirely.
> Removed redundant host system conditions from build presets

- CHANGELOG.md
- src/shapes/jolt_custom_double_sided_shape.cpp
It turns out that not registering any shape-casting handler with Jolt's `JPH::CollisionDispatch` for `JoltCustomDoubleSidedShape` meant that any attempt to CCD against a `ConcavePolygonShape3D` with `backface_collision` enabled would effectively nullify any benefit of the CCD operation.
This fixes that by implementing a shape-casting handler for `JoltCustomDoubleSidedShape`
> Added support for performing CCD against a double-sided shape

- CHANGELOG.md
- src/shapes/jolt_custom_ray_shape.cpp
- src/shapes/jolt_custom_ray_shape.hpp
- src/spaces/jolt_motion_filter_3d.cpp
Fixes #992.
This primarily fixes the issue of not being able to use `SeparationRayShape3D` for a `RigidBody3D` that had CCD enabled. It achieves this by providing a no-op implementation for any shape-casting[^1] involving the shape, which achieves a similar effect to what Godot Physics is doing with CCD for `SeparationRayShape3D`. I also added a non-zero (but very small) inner radius to the shape, in order to stop Jolt's asserts from triggering.
Besides that I also found some other minor issues, which I've included here:
1. There was a discrepancy with Godot Physics with regards to the filtering that happens in `body_test_motion` for `SeparationRayShape3D` using `slide_on_slope`, which may or may not have resulted in strange collision results when `slide_on_slope` was enabled.
2. There …
> Fixed various issues with `SeparationRayShape3D`

- cmake/GodotJoltExternalJolt.cmake
This bumps Jolt from godot-jolt/jolt@f15b519d629bdad9645c3fcee3baddff1a02dda7 to godot-jolt/jolt@a72422a24a89698f82bec45af00a45eca232636d (see diff [here](https://github.com/godot-jolt/jolt/compare/f15b519d629bdad9645c3fcee3baddff1a02dda7...a72422a24a89698f82bec45af00a45eca232636d)).
> Updated Jolt to a72422a24a

- cmake/toolchains/android/Common.cmake
It seems that CMake 3.31 has dropped support for projects that declare compatibility with CMake versions older than 3.10.
This causes problems with the Android NDK, which declares compatibility with CMake 3.6 and newer.
To get around this we disable deprecation warnings/errors entirely for Android builds.
> Silenced CMake deprecation errors when building for Android

- src/objects/jolt_body_impl_3d.cpp
When setting component C, the rest of the elements on row/column C of the inertia tensor should be zeroed
Fixes #1012
> Fixed override of the inertia diagonal

- cmake/GodotJoltExternalJolt.cmake
This bumps Jolt from godot-jolt/jolt@a72422a24a89698f82bec45af00a45eca232636d to godot-jolt/jolt@7e59df4e8f676fb8ed6c68d610543ce6ba3248c8 (see diff [here](https://github.com/godot-jolt/jolt/compare/a72422a24a89698f82bec45af00a45eca232636d...7e59df4e8f676fb8ed6c68d610543ce6ba3248c8)).
- Fixes issue with bodies gaining more energy than intended due to restitution
- Optimizations for creation of `ConcavePolygonShape3D`
- Adds `JPH::NarrowPhase::CollideShapeWithInternalEdgeRemoval`
> Updated Jolt to 7e59df4e8f

- CHANGELOG.md
- docs/settings.md
- src/objects/jolt_body_impl_3d.cpp
- src/servers/jolt_project_settings.cpp
- src/servers/jolt_project_settings.hpp
- src/shapes/jolt_custom_ray_shape.cpp
- src/spaces/jolt_physics_direct_space_state_3d.cpp
- src/spaces/jolt_physics_direct_space_state_3d.hpp
- src/spaces/jolt_query_collectors.hpp
Fixes #1014.
This pull request mainly does two things:
1. It fixes the incorrect use of Jolt's enhanced internal edge removal in the context of shape queries hitting multiple bodies, where `JPH::InternalEdgeRemovingCollector` apparently has to be flushed inbetween every body. This is now done using the new `CollideShapeWithInternalEdgeRemoval` method.
2. It splits the current "Use Enhanced Internal Edge Detection" setting into three settings, in order to be able to distinctly control its use for `RigidBody3D`, kinematic queries (`move_and_slide`, etc.) and shape queries (`intersect_shape`, etc.), since its effects on shape queries can be undesirable when not using them for kinematic movement purposes.
3. It changes the default value of this setting for queries to be off, in order to …
> Fixed issues related to enhanced internal edge removal

- src/spaces/jolt_contact_listener_3d.cpp
- src/spaces/jolt_contact_listener_3d.hpp
- src/spaces/jolt_job_system.cpp
I have until now relied on the default memory ordering (`std::memory_order_seq_cst`) for all atomic operations, which is used for the debug contacts in `JoltContactListener3D` and the completed jobs list in `JoltJobSystem`. While this is mostly fine on x86, it is apparently not the case on ARM, which supposedly uses a weaker memory model.
This PR changes the orderings to hopefully be more appropriate for ARM as well.
(Whether this manifests into any real noticeable difference I can't say. I doubt it.)
> Changed memory ordering for atomics

- CHANGELOG.md
- src/joints/jolt_cone_twist_joint_impl_3d.hpp
- src/joints/jolt_generic_6dof_joint_impl_3d.hpp
- src/joints/jolt_hinge_joint_impl_3d.hpp
- src/joints/jolt_slider_joint_impl_3d.hpp
It seems that #983 actually broke springs for the normal `Generic6DOFJoint3D` entirely, as this newly introduced force/torque limit defaulted to zero, and since `Generic6DOFJoint3D` doesn't have any way of setting it to non-zero you'd end up with a completely moot spring.
This PR fixes that by defaulting these spring limits to `FLT_MAX` instead, in the underlying implementation of all joints.
I also threw in the same change for the motor force/torque limits.
> Set better defaults for joint motor/spring limits

- src/objects/jolt_body_impl_3d.cpp
- src/objects/jolt_body_impl_3d.hpp
Hi there 👋
Here's a fix for an issue where [linear_damp](https://docs.godotengine.org/en/latest/classes/class_rigidbody3d.html#class-rigidbody3d-property-linear-damp) and [angular_damp](https://docs.godotengine.org/en/latest/classes/class_rigidbody3d.html#class-rigidbody3d-property-angular-damp) are not updated when either [linear_damp_mode](https://docs.godotengine.org/en/latest/classes/class_rigidbody3d.html#class-rigidbody3d-property-linear-damp-mode) or [angular_damp_mode](https://docs.godotengine.org/en/latest/classes/class_rigidbody3d.html#class-rigidbody3d-property-angular-damp-mode) is changed at runtime.
Previously, [linear_damp](https://docs.godotengine.org/en/latest/classes/class_rigidbody3d.html#class-rigidbody3d-property-linear-damp) and …
> Added updating of damping when switching damping mode

- .github/workflows/analyze.yml
- .github/workflows/build-android.yml
- .github/workflows/build-linux.yml
- .github/workflows/package.yml
- CHANGELOG.md
- README.md
The Ubuntu 20.04 runner images for GitHub Actions have been deprecated and will undergo brownouts soon, so we must update to Ubuntu 22.04.
Note that this means that we also _package_ Linux builds using Ubuntu 22.04, which means we'll end up depending on a later version of glibc, effectively raising the minimum system requirements for the extension. The glibc minimum required version will be bumped from version 2.31 to version 2.35.
> Updated Linux CI jobs to run on Ubuntu 22.04

- CHANGELOG.md
- src/objects/jolt_area_impl_3d.cpp
- src/objects/jolt_area_impl_3d.hpp
- src/objects/jolt_body_impl_3d.cpp
- src/objects/jolt_body_impl_3d.hpp
Supersedes #1031.
Reverts #1029.
Reverts parts of #201.
This changes the calculation of total damping for dynamic and kinematic bodies to be done every physics step, as opposed to only when the set of overlapping areas changed, or when certain properties changed.
This brings things more in line with how Godot Physics behaves, and with how the calculation for gravity behaves as well.
Note that this does introduce some amount of unnecessary overhead, but it's likely to be small for bodies not overlapping with any areas.
> Changed updating of total damping to be done every tick

- cmake/GodotJoltExternalJolt.cmake
This bumps Jolt from godot-jolt/jolt@c93401ea6577af6ae052f7c22cda6067a30333f3 to godot-jolt/jolt@600dae51122682afb1df96c392c4acb7f7e31836 (see diff [here](https://github.com/godot-jolt/jolt/compare/c93401ea6577af6ae052f7c22cda6067a30333f3...600dae51122682afb1df96c392c4acb7f7e31836)).
- Some minor bug fixes.
> Updated Jolt to 600dae5112

- .github/actions/setup-macos/action.yml
It seems I somehow entered the wrong Xcode version for the CI jobs in #1071, and put in version 15.2 instead of 16.4.
> Fixed Xcode version for macOS-based CI jobs

- cmake/GodotJoltExternalJolt.cmake
This bumps Jolt from godot-jolt/jolt@a18d475653c579c319bcf7b350f199ab437cafce to godot-jolt/jolt@2c6b713fe09bdfb9ec440616f9db84747461470f (see diff [here](https://github.com/godot-jolt/jolt/compare/a18d475653c579c319bcf7b350f199ab437cafce...2c6b713fe09bdfb9ec440616f9db84747461470f)).
- Bug fix to the active edge calculation of `ConcavePolygonShape3D`.
> Updated Jolt to 2c6b713fe0

- CHANGELOG.md
- src/objects/jolt_soft_body_impl_3d.cpp
Backport of godotengine/godot#106366.
> This fixes a discrepancy between godot physics and Jolt physics where in Jolt a vertex pinned to a body only gets its velocity updated while in godot it gets its position updated. This causes it to lag one frame behind.
> Fixed issue where soft bodies would lag behind moving attachments

- CHANGELOG.md
- src/objects/jolt_soft_body_impl_3d.cpp
Backport of godotengine/godot#107832.
> The code previously iterated through each face and set all vertices to that face's normal. This resulted in each vertex getting the normal from just one face that it belonged to (whichever face was last in this array). This caused weird shading artifacts.
>
> This fixes the code so that the vertex normal is now the average normal of all faces that it belongs to. This results in "smooth shading" behavior for soft body meshes. This is still somewhat undesirable if the input mesh was using flat shading, but it looks less bad than the previous behavior of picking a normal at random from one attached face.
>
> This matches the behavior of GodotPhysicsServer3D.
> Fixed soft body vertex normal calculation

- cmake/GodotJoltExternalJolt.cmake
This bumps Jolt from godot-jolt/jolt@2c6b713fe09bdfb9ec440616f9db84747461470f to godot-jolt/jolt@b385bc3d7683a03edcc794c67c297bd7a3d1974f (see diff [here](https://github.com/godot-jolt/jolt/compare/2c6b713fe09bdfb9ec440616f9db84747461470f...b385bc3d7683a03edcc794c67c297bd7a3d1974f)).
- Bug fix for `JPH::SixDOFConstraint`, allowing the rotation axes to all be locked while also locking one or more of those same axes for either of the two bodies.
> Updated Jolt to b385bc3d76

- CHANGELOG.md
- src/objects/jolt_body_impl_3d.cpp
- src/objects/jolt_body_impl_3d.hpp
- src/precompiled.hpp
- src/spaces/jolt_body_activation_listener_3d.cpp
- src/spaces/jolt_body_activation_listener_3d.hpp
- src/spaces/jolt_space_3d.cpp
- src/spaces/jolt_space_3d.hpp
Backport of godotengine/godot#108544.
> This effectively makes it so that a physics body's state synchronization (which includes things like calling `_integrate_forces`) is called at the next physics frame not only if it was awake _before_ the simulation was stepped, but also if it was woken up _during_ the simulation step.
> 
> This is done by making use of Jolt's `JPH::BodyActivationListener`, which as the name suggests invokes callbacks if the body was put to sleep or awakened, letting us queue up a body for synchronization if it was in fact awakened.
> 
> Without this we would end up calling the state synchronization (and thus `_integrate_forces`) two physics frames after the collision happened, at which point we would already have removed the contacts, assuming it was a single-frame …
> Fixed contacts not being reported on first physics frame
