- examples/scenes/shapes/entities/height_map/height_map.gd
- src/containers/hash_map.hpp
- src/containers/hash_set.hpp
- src/containers/local_vector.hpp
- src/jolt_area_3d.cpp
- src/jolt_body_3d.cpp
- src/jolt_body_3d.hpp
- src/jolt_collision_object_3d.cpp
- src/jolt_collision_object_3d.hpp
- src/jolt_contact_listener.cpp
- src/jolt_empty_shape.cpp
- src/jolt_empty_shape.hpp
- src/jolt_override_user_data_shape.cpp
- src/jolt_override_user_data_shape.hpp
- src/jolt_physics_direct_body_state_3d.cpp
- src/jolt_physics_direct_space_state_3d.cpp
- src/jolt_ray_shape.cpp
- src/jolt_shape_3d.cpp
- src/jolt_shape_3d.hpp
- src/jolt_shape_3d.inl
- src/jolt_shape_instance_3d.hpp
- src/jolt_space_3d.cpp
- src/misc/utility_functions.hpp
See the list of commits for a breakdown of said cleanup.
> Cleaned up a couple of things

- src/jolt_ray_shape.cpp
This PR improves on the implementation of the `SeparationRayShape3D` shape with the following changes:
1. Added support for the `margin` parameter of `body_test_motion`, also known as the "Safe Margin" property on `CharacterBody3D`.
2. Changed the calculation of penetration depth, which previously could never be negative, which it will be if the hit is within the margin.
3. Made use of the query collector's early-out fraction to discard redundant calculations/hits.
4. Refactored variable names.
> Improved implementation of `SeparationRayShape3D`

- src/jolt_physics_direct_space_state_3d.cpp
The introduction of shape margins in #239 seems to have broken the shape-casting, which now needs to compensate for these shape margins when producing the safe and unsafe fractions. This applies to both `cast_motion` as well as `body_test_motion`.
> Fixed broken shape-casting when using non-zero shape margins

- README.md
- docs/settings.md
Writing this much text inside Markdown tables was not really feasible, so I ended up (unfortunately) writing it using Markdown's inline HTML instead.
> Added documentation for the project settings

- CHANGELOG.md
- CMakeLists.txt
> Bumped the version to `0.1.0-rc1`

- .github/workflows/analyze.yml
- .github/workflows/build-linux.yml
- .github/workflows/build-macos.yml
- .github/workflows/build-windows.yml
This saves us from having to wait for many lengthy CI runs whenever a change is made after changes have been made to the documentation or the examples.
> Added CI filters for changes to documentation and examples

- CHANGELOG.md
I figured this made sense to use considering Godot uses this format as well.
> Changed the CHANGELOG to use the "Keep a Changelog" format

- CMakeLists.txt
> Bumped the version to 0.1.0-rc3

- src/joints/jolt_pin_joint_impl_3d.cpp
> Added missing locks in pin joint

- src/joints/jolt_cone_twist_joint_impl_3d.cpp
- src/joints/jolt_cone_twist_joint_impl_3d.hpp
- src/joints/jolt_hinge_joint_impl_3d.cpp
- src/joints/jolt_hinge_joint_impl_3d.hpp
- src/joints/jolt_slider_joint_impl_3d.cpp
- src/joints/jolt_slider_joint_impl_3d.hpp
Part of #418 and related to #421.
> Added more missing explicit locking in joints

- CHANGELOG.md
- src/joints/jolt_slider_joint_impl_3d.cpp
Does exactly what it says on the tin.
> Fixed inability to have a fixed slider joint

- src/objects/jolt_body_impl_3d.cpp
Complements #448.
So it turned out Clang builds did not like my usage of `INFINITY` for the rotation lock implementation in #448, and started generating a bunch of NaNs that quickly blew up the whole simulation.
This PR addresses this by instead doing exactly what Jolt does in its `TwoDFunnelTest` and sets the inverse inertia directly using `JPH::Body::SetInverseInertia`, instead of trying to do it through `JPH::MassProperties::mInertia`.
> Fixed crash when using rotation lock in Clang builds

- CHANGELOG.md
- src/misc/math.hpp
> Fixed not being able to negatively scale bodies/shapes

- CMakeLists.txt
- cmake/GodotJoltExternalMimalloc.cmake
- src/containers/local_vector.hpp
- src/containers/rid_owner.hpp
- src/joints/jolt_cone_twist_joint_impl_3d.cpp
- src/joints/jolt_generic_6dof_joint_impl_3d.cpp
- src/joints/jolt_hinge_joint_impl_3d.cpp
- src/joints/jolt_joint_impl_3d.cpp
- src/joints/jolt_joint_impl_3d.hpp
- src/joints/jolt_pin_joint_impl_3d.cpp
- src/joints/jolt_slider_joint_impl_3d.cpp
- src/misc/math.hpp
- src/objects/jolt_body_impl_3d.cpp
- src/objects/jolt_body_impl_3d.hpp
- src/objects/jolt_object_impl_3d.hpp
- src/servers/jolt_physics_server_3d.cpp
- src/spaces/jolt_contact_listener_3d.cpp
- src/spaces/jolt_contact_listener_3d.hpp
- src/spaces/jolt_layer_mapper.cpp
- src/spaces/jolt_motion_filter_3d.cpp
- src/spaces/jolt_motion_filter_3d.hpp
These are largely cosmetic changes or changes with a very low impact. See the list of commits for a breakdown of the changes.
> Cleaned up some minor imperfections

- src/joints/jolt_cone_twist_joint_3d.cpp
- src/joints/jolt_hinge_joint_3d.hpp
- src/joints/jolt_joint_3d.cpp
- src/joints/jolt_slider_joint_3d.hpp
- src/register_types.cpp
These are largely cosmetic changes or changes with a very low impact. See the list of commits for a breakdown of the changes.
> Cleaned up some more stuff related to custom joints

- CHANGELOG.md
- docs/settings.md
- src/servers/jolt_project_settings.cpp
- src/servers/jolt_project_settings.hpp
- src/spaces/jolt_physics_direct_space_state_3d.cpp
Related to #530.
Reverts #560.
I'm not all that happy with this setting, so I'm gonna leave it out for now.
> Reverted "Ignore Internal Edges" project setting

- cmake/GodotJoltExternalLibrary.cmake
Effectively reverts #678.
It turned out that this new support for changing the `GIT_TAG` of an `UPDATE_DISCONNECTED` external project in CMake 3.27 was only for commits that were known at the time of the `git clone`, so as soon as you referenced newer commits you'd run into an error.
This reintroduces the hack that was used previously, but modified in a way to only support CMake 3.27 or newer.
> Reintroduced incremental build hack for external projects

- README.md
- src/precompiled.hpp
- src/spaces/jolt_contact_listener_3d.cpp
- src/spaces/jolt_contact_listener_3d.hpp
- src/spaces/jolt_space_3d.cpp
This adds the ability to have a soft body assume infinite mass when its `collision_mask` doesn't contain the `collision_layer` of the body it's colliding with, and vice versa.
> Added asymmetrical/one-way collisions to soft bodies

- src/servers/jolt_physics_server_3d.cpp
Fixes #816 
This is my first ever contribution to an open source project, so please let me know if I'm doing anything wrong!
> Fixed `body_get_direct_state` returning non-null with no space

- src/objects/jolt_body_impl_3d.cpp
#828 broke the integration of gravity, due to me changing it from just being applied to the velocity directly to instead being applied through `JPH::Body::AddForce`, which is obviously wrong since that takes mass into account, which gravity shouldn't.
> Fixed broken gravity integration

- src/objects/jolt_shaped_object_impl_3d.cpp
This was something left over from #925.
> Fixed scale error-check in `set_shape_transform`

- src/joints/jolt_cone_twist_joint_impl_3d.cpp
- src/joints/jolt_generic_6dof_joint_impl_3d.cpp
- src/joints/jolt_hinge_joint_impl_3d.cpp
- src/joints/jolt_slider_joint_impl_3d.cpp
* Hinge and slider joints weren't including the lambda of the limits
* Including motor lambda for all joints
Fixes #993
> Fix reported joint force/torque not being correct when sprung
